export default `
 <h2>Name</h2>
<p>The Surah taken its name from the word <em>at takathur</em> in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Abu Hayyan and Shaukani say that this Surah, according to all commentators, is Makki, and this same is the well known view according to Iman Suyuti. However, there are some traditions, on the basis of which it is considered a Madani Surah, and they are as follows:</p>
<p>Ibn Abi Hatim has cited Abu Buraidah as saying that this Surah was sent down concerning the two tribes, Bani Harithah and Bani al-Harth, of the Ansar. The two tribes had first recounted the glories and illustrious deeds of their living men; then they had gone to the grave yard and bragged of the glorious deeds of their dead. Thereupon the Divine Revelation <em>Alhakum at takathur</em> came down. But, if the practice of the Companions and their successors concerning the occasions of revelation, is kept in view, this tradition is no argument to prove that Surah At Takathur was sent down on that very occasion, but it shows that this Surah fully applied to the act of the two tribes.</p>
<p>Imam Bukhari and Ibn Jarir have cited this view of Hadrat Ubayy bin Ka'ab: "We took the Holy Prophet saying: “If the son of Adam had two valleys full of wealth, he would long for a third valley; the son of Adam's belly cannot be filled but by earth, to be from the Quran until <em>Alhakum at takathur</em> was sent down.”</p>
<p>This <em>Hadith</em> has been regarded as an argument for Surah At-Takathur to be a Madani Surah on the ground that Hadrat Ubayy had become a Muslim in Madinah. But Hadrat Ubayy's this statement does not indicate in what sense the Companions regarded this saying of the Holy Prophet (upon whom be peace) as belonging to the Quran. If it means that they regarded it as a verse of the Quran, it cannot be acceptable, for a great majority of the Companions consisted of the men who were well aware of each and every word of the Quran; they could not have the misunderstanding that the <em>Hadith</em> was a verse of the Quran. And if its belonging to the Quran is taken to mean its being derived from the Quran, the tradition can also mean that when the Companions who entered Islam in Madinah, heard this Surah for the first time from the Holy Prophet, they thought that it had been revealed just then, and then about the Holy Prophet's above saying they formed the idea that it was derived from
this very Surah.</p>
<p>Ibn Jarir Tirmidhi, Ibn al Mundhir and other traditionists have related this view of Hadrat Ali: "We were in doubt about the torment of the grave until <em>Alhakum at takathur</em> was sent down." This view has been regarded as an argument for Surah At-Takathur to be Madani on the ground that the torment of the grave was first mentioned at Madinah; no mention of it was ever made at Makkah. But this is wrong. In the Makki Surahs of the Quran, the torment of the grave has been mentioned at many places so clearly that there can he no room for any such doubt; for example, see Al- An'am: 93, An-Nahl: 28, Al-Muminun: 99-100, Al-Mu'min: 45-46, which are all Makki Surahs. Therefore, if anything is proved by Hadrat Ali's saying, it is that Surah At-Takathur had been revealed before the revelation of the above mentioned Makki Surahs and its revelation had removed the Companions doubt about the torment of the grave.</p>
<p>That is why, in spite of these traditions, a great majority of the commentators are agreed that this Surah is Makki. In our opinion this is not only a Makki Surah but in view of its contents and style it is one of the earliest Surahs to be revealed at Makkah.</p>
<h2>Theme and Subject Matter</h2>
<p>In it the people have been warned of the evil consequences of world worship because of which they spend their lives in acquiring more and more of worldly wealth, material benefits and pleasures, and position and power, till death, and in vying with one another and bragging and boasting about their acquisitions. This one pursuit has so occupied them that they are left with no time or opportunity for pursuing the higher things in life. After warning the people of its evil end they have been told us if to say: "These blessings which you are amassing and enjoying thoughtlessly, are not mere blessings but are also a means of your trial. For each one of these blessings and comforts you will surely be called to account in the Hereafter."</p>
`
