export default `
 <h2>Name</h2>
<p>The Surah derives its name from the word <em>ashab al fil</em> in the very first verse.</p>
<h2>Period of Revelation</h2>
<p>This is unanimously a Makki Surah; and if it is studied against its historical background it appears that it must have been sent down in the very earliest stage at Makkah.</p>
<h2>Historical Background</h2>
<p>As we have explained in E. N. 4 of Surah Al-Buruj above, in retaliation for the persecution of the followers of the Prophet Jesus Christ (peace be on him) in Najran by the Jewish ruler Dhu-Nuwas of Yemen, the Christian kingdom of Abyssinia invaded Yemen and put an end to the Himyarite rule there, and in 52S A. D. this whole land passed under Abyssinian control. This happened, in fact, through collaboration between the Byzantine empire of Constantinople and the Abyssinian kingdom, for the Abyssinians at that time had no naval fleet. The fleet was provided by Byzantium and Abyssinia sent 70,000 of its troops by it across the Red Sea to Yemen. At the outset one should understand that all this did not happen under the religious zeal but there were economic and political factors also working behind it, and probably these were the real motive, and retaliation for the Christian blood was just an excuse. Since the time the Byzantine empire had occupied Egypt and Syria, it had been
trying to gain control over the trade going on between East Africa, India, Indonesia, etc., and the Byzantine dominions: from the Arabs, who had been controlling it for centuries, so as to earn maximum profits by eliminating the intermediary Arab merchants. For this purpose, in 24 or 25 B. C., Caesar Augustus sent a large army under the Roman general, Aelius Gallus, which landed on the western coast of Arabia, in order to intercept and occupy the sea route between southern Arabia and Syria. (See map of this trade route on p. 111 of <em>The Meaning of the Qur'an</em>, vol. iv). But the campaign failed to achieve its objective on account of the extreme geographical conditions of Arabia. After this, the Byzantines brought their fleet into the Red Sea and put an end to the Arab trade which they carried out by sea, with the result that they were left only with the land route. To capture this very land route they conspired with the Abyssinian Christians and aiding them with their fleet
helped them to occupy Yemen.</p>
<p>The Arab historians statements about the Abyssinian army that invaded Yemen are different. Hafiz Ibn Kathir says that it was led by two commanders, Aryat and Abrahah, and according to Muhammad bin Ishaq, its commander was Aryat, and Abrahah was included in it. Then both are agreed that Aryat and Abrahah fell out, Aryat was killed in the encounter, and Abrahah took possession of the country; then somehow he persuaded the Abyssinian king to appoint him his viceroy over Yemen. On the contrary, the Greek and Syrian historians state that when after the conquest of Yemen, the Abyssinians started putting to death the Yamanite chiefs, who had put up resistance, one of the chiefs, named As-Sumayfi Ashwa (whom the Greek historians call Esymphaeus) yielded to the Abyssinians and promising to pay tribute obtained the Abyssinian king's warrant to be governor over Yemen. But the Abyssinian army revolted against him and made Abrahah governor in his place. This man was the slave of a Greek
merchant of the Abyssinian seaport of Adolis, who by clever diplomacy had come to wield great influence in the Abyssinian army occupying Yemen. The troops sent by the Negus to punish him either warned him or were defeated by him. Subsequently, after the death of the king, his successor was reconciled to accept him as his vice regent of Yemen.(The Greek historians write him as Abrames and the Syrian historians as Abraham. Abrahah perhaps is an Abyssinian variant of Abraham, for its Arabic version is Ibrahim).</p>
<p>This man through passage of time became an independent ruler of Yemen. He acknowledged the sovereignty of the Negus only in name and described himself as his deputy. The influence he wielded can be judged from the fact that after the restoration of the dam of Marib in 543 A. D. he celebrated the event by holding a grand feast, which was attended by the ambassadors of the Byzantine emperor, king of Iran, king of Hirah, and king of Ghassan. Its full details are given in the inscription that Abrahah installed on the dam. This inscription is extant and Glaser has published it.(For further details, see E. N. 37 of the commentary of Surah Saba).</p>
<p>After stabilizing his rule in Yemen Abrahah turned his attention to the objective which from the very beginning of this campaign had been before the Byzantine empire and its allies, the Abyssinian Christians, i. e. to spread Christianity in Arabia, on the one hand, and to capture the trade that was carried out through the Arabs between the eastern lands and the Byzantine dominions, on the other. The need, for this increased because the Byzantine struggle for power against the Sasanian empire of Iran had blocked all the routes of the Byzantine trade with the East.</p>
<p>To achieve this objective, Abrahah built in Sana, the capital of Yemen, a magnificent cathedral, called by the Arabian historians al-Qalis, al-Qullais, or al-Qulais, this word being an Arabic version of the Greek word Ekklesia, church. According, to Muhammad bin Ishaq, after having completed the building, he wrote to the Negus, saying: "I shall not rest until I have diverted the Arabs pilgrimage to it."Ibn Kathir writes that he openly declared his intention in Yemen and got it publicly announced. He, in fact, wanted to provoke the Arabs into doing something which should provide him with an excuse to attack Makkah and destroy the Ka'bah. Muhammad bin Ishaq says that an Arab, enraged at this public proclamation somehow went into the cathedral and defiled it. Ibn Kathir says this was done by a Quraishite and according to Muqatil bin Suleman, some young men of the Quraish had set fire to the cathedral. Either might have happened, for Abrahah's proclamation was certainly provocative
and in the ancient pre-Islamic age it cannot be impossible that an Arab, or a Quraishite youth, might have been enraged and might have defiled the cathedral, or set fire to it. But it may well also be that Abrahah himself got this done secretly by his own agent so as to have an excuse for invading Makkah and thus achieving both his objectives by destroying the Quraish and intimidating the Arabs. In any case, whatever happened, when the report reached Abrahah that the devotees of the Ka'bah had thus defiled his cathedral, he swore that he would not rest until he had destroyed the Ka'bah.</p>
<p>So, in 570 or 571 A. D., he took 60,000 troops and 13 elephants (according to another tradition, 9 elephants) and set off for Makkah. On the way, first a Yamanite chief, Dhu Nafr by name, mustering an army of the Arabs, resisted him but was defeated and taken prisoner. Then in the country of Khath'am he was opposed by Nufail bin Habib al-Khath'am, with his tribe, but he too was defeated and taken prisoner, and in order to save his life he accepted to serve him as guide in the Arab country. When he reached near Ta'if, Bani Thaqif felt that they would not be able to resist such a big force and feeling the danger lest he should destroy the temple of their deity Lat, too; their chief, Mas'ud. came out to Abrahah with his men, and he told him that their temple was not the temple he had come to destroy. The temple He sought was in Makkah, and they would send with him a man to guide him there. Abrahah accepted the offer, and Bani Thaqif sent Abu Righal as guide with him. When they
reached al-Mughammas (or al- Mughammis), a place about 3 miles short of Makkah, Abu Righal died, and the Arabs stoned his grave and the practice survives to this day. They cursed the Bani Thaqif too, for in order to save the temple of Lat they had cooperated with the invaders of the House of Allah.</p>
<p>According to Muhammad bin Ishaq, from al- Mughammas Abrahah sent forward his vanguard and they brought him the plunder of the people of Tihamah and Quraish, which included two hundred camels of Abdul Muttalib, the grandfather of the Holy Messenger of Allah (upon whom be His peace). Then, he sent an envoy of his to Makkah with the message that he had not come to fight the people of Makkah but only to destroy the House (i. e. the Ka'bah). If they offered no resistance, there would be no cause for bloodshed. Abrahah also instructed his envoy that if the people of Makkah wanted to negotiate, he should return with their leading chief to him. The leading chief of Makkah at that time was Abdul Muttalib. The envoy went to him and delivered Abrahah's message. Abdul Muttalib replied:"We have no power to fight Abrahah. This is Allah's House. If He wills He will save His House." The envoy asked him to go with him to Abrahah. He agreed and accompanied him to the king. Now Abdul Muttalib was
such a dignified and handsome man that when, Abrahah saw him he was much impressed; he got off his throne and sat beside him on the carpet. Then he asked him what he wanted. Abdul Muttalib replied that he wanted the king to return his camels which he had taken. Abrahah said: "I was much impressed when I saw you but your reply has brought you down in my eyes: you only demand your camels but you say nothing about this House which is your sanctuary and the sanctuary of your forefathers." He replied: "I am the owner of my camels and am requesting you to return them. As for the House, it has its own Owner: He will defend it." When Abrahah said that He would not be able to defend it against him, Abdul Muttalib said that that rested between Him and him. With this Abdul Muttalib left Abrahah and he restored to him his camels.</p>
<p>Ibn Abbas tradition is different. It does not mention the demand for the camels at all. According to the traditions related from him by Abd bin Humaid, Ibn al-Mundhir, lbn Marduyah, Hakim, Abu Nuaim and Baihaqi, he states that when Abrahah reached As-Sifah (a place situated between Arafat and Taif in the mountains near the sacred bounds of Makkah), Abdul Muttalib went to him and said: "There was no need for you to come so far. You should have ordered us and we would have brought before you whatever you needed." He said: "I hear that this House is the House of peace: I have come to destroy its peace."Thereupon, Abdul Muttalib said: "This is Allah's House. He has not allowed anyone so far to dominate it."Abrahah replied: "We will not return until we have destroyed it."Abdul Muttalib said:"You may take whatever you like from us and return."Abrahah refused to budge and ordered his troops to advance, leaving Abdul Muttalib behind.</p>
<p>Leaving the two traditions as they are, one thing which becomes evident is that the tribes living in and around Makkah did not have the power to fight such a big force and save the Ka'bah. Therefore, obviously, the Quraish did not try to put up any resistance. The Quraish on the occasion of the Battle of the Trench (Ahzab) had hardly been able to muster &amp; strength numbering ten to twelve thousand men in spite of the alliance with the pagan and Jewish tribes; they could not have resisted an army 60,000 strong.</p>
<p>Muhammad bin Ishaq says that after returning from the camp of Abrahah Abdul Muttalib ordered the Quraish to withdraw from the city and go to the mountains along with their families for fear of a general massacre. Then he went to the Ka'bah along with some chiefs of the Quraish and taking hold of the iron ring of the door, prayed to Allah Almighty to protect His House and its keepers. There were at that time 360 idols in and around the Ka'bah, but on that critical moment they forgot them and implored only Allah for help. Their supplications which have been reported in the books of history do not contain any name but of Allah, the One. Ibn Hisham in his <em>Life of the Prophet</em> has cited some verses of Abdul Muttalib, which are to the following effect:</p>
<p>"O God, a man protects his house, so protect Your House; Let not their cross and their craft tomorrow overcome Your craft. If You will to leave them and our qiblah to themselves, You may do as You please."</p>
<p>Suhail in Raud al-Unuf has cited this verse also in this connection: "Help today Your devotees against the devotees of the cross and its worshipers."</p>
<p>Ibn Jarir has cited Abdul Muttalib's these verses also, which he had recited in his supplication; "O my Lord, I do not cherish any hope from anyone against them except You. O my Lord, protect Your House from them. The enemy of this House is Your enemy. Stop them from destroying Your settlement."</p>
<p>After making these supplications Abdul Muttalib and his companions also went off to the mountains. Next morning Abrahah prepared to enter Makkah, but his special elephant, Mahmud, which was in the forefront, knelt down. It was beaten with iron bars, goaded, even scarified, but it would not get up. When they made it face south, north, or east, it would immediately start off, but as soon as they directed it towards Makkah, it knelt down. In the meantime swarms of birds appeared carrying stones in their beaks and claws and showered these on the troops. Whoever was hit would start disintegrating. According to Muhammad bin Ishaq and Ikrimah, this was smallpox, which was seen in Arabia for the first time in that year. Ibn Abbas says that whoever was struck by a pebble, would start scratching his body resulting in breaking of the skin and falling off of the flesh. In another tradition Ibn Abbas says that the flesh and blood flowed like water and bones in the body became visible. The
same thing happened with Abrahah too. His flesh fell in pieces and there arose bores on his body emitting pus and blood. In confusion they withdrew and fled towards Yemen. Nufail bin Habib, whom they had brought as guide from the country of Khatham, was searched out and asked to guide them back to Yemen, but he refused and said: "Now where can one flee when God pursues? The split nose (Abrahah) is the conquered; not the conqueror."</p>
<p>As they withdrew they were continually falling by the bay and dying. Ata bin Yasar says that all the troops did not perish at the spot; some perished there and others perished by the wayside as they withdrew. Abrahah died in the country of Khath'am.</p>
<p>This event took place at Muhassir by the Muhassab valley, between Muzdalifah and Mina. According to the <em>Sahih</em> of Muslim and Abu Da'ud, in the description of the Holy Prophet's farewell pilgrimage that Imam Jafar as-Sadiq has related from his father, Imam Muhammad Baqir, and he from Hadrat Jabir bin Abdullah, he says that when the Holy Prophet (upon whom be peace) proceeded from Muzdalifah to Mina, he increased his speed in the valley of Muhassir. Imam Nawawi has explained it saying that the incident of the people of the elephant had occurred there; therefore, the pilgrims have been enjoined to pass by quickly, for Muhassir is a tormented place. Imam Malik in <em>Mu'atta</em> has related that the Holy Prophet said that the whole of Muzdalifah is a fit place for staying but one should not stay in the valley of Muhassir.</p>
<p>In the verses of Nufail bin Habib, which Ibn Ishaq has cited, he describes this event as an eye witness: "Would that you had seen, O Rudaina, but you would not see, What we saw by the valley of Muhassab. I praised God when I saw the birds, and I feared lest the stones should fall upon us. Everyone was asking for Nufail As though I owned the Abyssinians a debt."</p>
<p>This was such a momentous event that it soon spread throughout Arabia and many poets made it the subject of their laudatory poems. In these poems one thing is quite evident that everyone regarded it as a manifestation of Allah Almighty's miraculous power, and no one, even by allusion, said that the idols which were worshiped in the Ka'bah, had anything to do with it. For example, Abdullah ibn Az-Zibara says: "The sixty thousand returned not home, Nor did their sick man (Abrahah) survive on return. Ad and Jurham were there before them, And there is Allah, above the servants, Who sustains it."</p>
<p>Abu Qais bin Aslat says: "Rise and worship your Lord and anoint The Corners of the House of Allah between the Mountains of Makkah and Mina. When the help of the Owner of the Throne reached you, His armies repulsed them so that they were lying in dust, pelted with stones."</p>
<p>Not only this, but according to Hadrat Umm Hani and Hadrat Zubair bin al-Awwam, the Holy Prophet (upon whom be peace) said:"The Quraish did not worship anyone but Allah, the Only and One, for ten years (and according to others, for seven years. Umm Hani's tradition has been related by Imam Bukhari in his History and by Tabarani, Hakim, Ibn Marduyah and Baihaqi in their collections of <em>Ahadith</em>. Hadrat Zubair's statement has been related by Tabarani, Ibn Marduyah and Ibn Asakir, and this is further confirmed by the <em>mursal</em> tradition of Hadrat Sa'id bin al Musayyab, which Khatib Baghdadi has recorded in his History.</p>
<p>The Arabs describe the year in which this event took place as <em>Am al-Fil</em> (the year of the elephants), and in the same year the Holy Messenger of Allah (upon whom be His peace) was born. The traditionists and historians almost unanimously state that the event of the people of the elephant had occurred in Muharram and the Holy Prophet was born in Rabi al-Awwal. A majority of them states that he took birth 50 days after the event of the elephant.</p>
<h2>Theme and Substance</h2>
<p>If Surah al-Fil is studied in the light of the historical details as given above, one can fully well understand why in this Surah only Allah's inflicting His punishment on the people of the elephant has been referred and described so briefly. It was an event of recent occurrence, and everyone in Makkah and Arabia was fully aware of it. The Arabs believed that the Ka'bah had been protected in this invasion not by any god or goddess but by Allah Almighty Himself. Then Allah alone had been invoked by the Quraish chiefs for help, and for quite a few years the people of Quraish having been impressed by this event, had worshiped none but Allah. Therefore, there was no need to mention the details in Surah al-Fil, but only a reference to it was enough so that the people of Quraish, in particular, and the people of Arabia, in general, should consider well in their hearts the message that the Holy Prophet Muhammad (upon whom be Allah's peace and blessings) was giving. For the only message
that he gave was that they should worship and serve none but Allah, the Only and One. Then, they should also consider that if they used force to suppress this invitation to the truth, they would only be inviting the wrath of God, Who had so completely routed and destroyed the people of the elephants.</p>;
`
