export default `
 <h2>Name</h2>
<p>The Surah has been so entitled after the word <em>Quraish</em> in the very first verse.</p>
<h2>Period of Revelation</h2>
<p>Although Dahhak and Kalbi regard it as a Madani Surah, yet a great majority of the commentators are agreed that it is Makki, and a manifest evidence of this are the words <em>Rabba hadh-al-Bait</em> (Lord of this House) of this Surah itself. Had it been revealed at Madinah, the words "this House" for the Ka'bah could not be relevant. Moreover, its subject matter so closely relates to that of Surah Al-Fil that probably it was revealed immediately after it, without any other Surah intervening between them. On the basis of this very relevance, some of the earliest scholars regard the two Surahs as one entity. This view is strengthened by the traditions which say that in the Quran copy belonging to Hadrat Ubayy bin Ka'b these two were written as one Surah, i.e. without the insertion of the <em>Bismillah</em> between them. Furthermore, Hadrat Umar had once recited the two Surahs as one in the Prayer. But this view is not acceptable because in the Quran copy which Hadrat Uthman (may
Allah bless him) had got written down officially by the cooperation of a large number of the Companions and sent to the centers of Islamic lands, the <em>Bismillah</em> was written between these two Surahs, and since then these two have been written as separate Surahs in all the copies of the Quran everywhere in the world. Moreover, the style of the two Surahs is so different that they manifestly appear as two separate Surahs.</p>
<h2>Historical Background</h2>
<p>To understand the Surah well it is essential that one should keep the historical background relevant to the contents of this Surah and of Surah Al-Fil in view.</p>
<p>The tribe of Quraish was scattered throughout Hijaz until the time of Qusayy bin Kilab, the ancestor of the Holy Prophet (upon whom be Allah's peace). First of all, Qusayy gathered it in Makkah and this tribe was able to gain authority over the Ka'bah. On that very basis Qusayy was called <em>mujammi</em> (uniter, assembler) by his people. This man by his sagacity and wisdom founded a city state in Makkah and made excellent arrangements for the welfare of the pilgrims coming from all over Arabia, with the result that the Quraish were able to gain great influence among the Arabian tribes and lands. After Qusayy the offices of the state of Makkah were divided between his sons, Abdi Manaf and Abd ad-Dar, but of the two Abdi Manaf gained greater fame even during his father's lifetime and was held in high esteem throughout Arabia. Abdi Manaf had four sons: Hashim, Abdi Shams, Al-Muttalib, and Naufal. Of these Hashim, father of Abdul Muttalib and grandfather of the Holy Prophet, first
conceived the idea to take part in the trade that passed between the eastern countries and Syria and Egypt through Arabia, and also to purchase the necessities of life for the Arabians so that the tribes living by the trade route bought these from them and the merchants living in the interior of the country were attracted to the,market of Makkah. This was the time when the Sasanian kingdom of Iran had captured the international trade that was carried out between the northern lands and the eastern countries and Byzantine empire through the Persian Gulf. This had boosted up the trade activity on the trade route leading from southern Arabia to Syria and Egypt along the Red Sea coast. As against the other Arabian caravans, the Quraish had the advantage that the tribes on the route held them in high esteem on account off their being keepers of the Ka'bah. They stood indebted to them for the great generosity with which the Quraish treated them in the Hajj season. That is why the Quraish
felt no fear that their caravans would be robbed or harmed any where on the way. The tribes on the way did not even charge them the heavy transit taxes that they demanded from the other caravans. Hashim taking advantage of this prepared the trade scheme and made his three brothers partners in it. Thus, Hashim obtained trade privileges from the Ghassanide king of Syria, Abdi Shams from the Negus, Al-Muttalib from the Yamanite nobles and Naufal from the governments of Iraq and Iran, and their trade began to flourish. That is how the four brothers became famous as traders and began to be called ashab al-ilaf (generators of love and affection) on account of their friendly relations with the tribes and states of the surrounding lands.</p>
<p>Because of their business relations with Syria, Egypt, Iraq, Iran, Yaman and Abyssinia, the Quraish came across such opportunities and their direct contact with the culture and civilization of different countries so enhanced the level of their knowledge and wisdom that no tribe in Arabia could match and equal them. As regards wealth and worldly goods they became the most affluent tribe, and Makkah became the most important commercial center of the Arabian peninsula. Another great advantage that accrued from these international relations was that they brought from Iraq tile script which later was used for writing down the Quran. No other Arabian tribe could boast of so many literate people as Quraish. For these very reasons the Holy Prophet (upon whom be peace) said: "Quraish are the leaders of men." (Musnad Ahmad: <em>Marwiyat Amr bin al As</em>). And according to a tradition from Hadrat Ali in Baihaqi, the Holy Prophet said: "First the leadership of the Arabians was in the
hands of the people of Himyar, then Allah withdrew it from them and gave it to Quraish".</p>
<p>The Quraish were thus prospering and flourishing when the event of Abrahah's invasion of Makkah took place. Had Abrahah at that time succeeded in taking this holy City and destroying the Ka'bah, the glory and renown of not only the Quraish but of the Ka'bah itself, would have faded away, the belief of the pre-Islamic Arabia that the House indeed was Allah's House would have been shattered, and the high esteem in which Quraish were held for being keepers of the House throughout the country would have been tarnished. Then, after the Abyssinian advance to Makkah, the Byzantium also would have taken the initiative to gain control over the trade route between Syria and Makkah: and the Quraish would have been reduced to a plight worse than that in which they were involved before Qusayy bin Kilab. But when Allah showed this manifestation of His power that the swarms of birds destroyed 60,000 Abyssinian troops brought by Abrahah by pelting then, with stones, and from Makkah to Yaman
they went on falling and dying by the wayside, the faith of the Arabs that the Ka'bah indeed was Allah's House increased manifold, and the glory and renown of Quraish too was enhanced considerably throughout the country. Now the Arabs were convinced that they were under Allah's special favor; therefore, they visited every part of Arabia fearlessly and passed through every land with their trade caravans unharmed. No one could dare touch them with an evil intention. Not to speak of touching them, even if they had a non-Quraishite under their protection, he too was allowed to pass unharmed.</p>
<h2>Theme and Substance</h2>
<p>As all this was well known in the time of the Holy Prophet's appointment to Prophethood, there was no need to mention them. That is why in the four brief sentences of this Surah, Quraish were simply asked to consider:"When you yourselves acknowledge this House (i. e. the Ka'bah) to be Allah's House, and not of the idols, and when you fully well know that it is Allah alone Who has granted you peace by virtue of this House, made your trade and commerce flourish and saving you from destitution favored you with prosperity you should then worship and serve Him alone."</p>;
`
