export default `
 <h2>Name</h2>
<p>The Surah has been so designated after the word <em>al-kauthar</em> occurring in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Ibn Marduyah has cited Hadrat Abdullah bin Abbas, Hadrat Abdullah bin az-Zubair and Hadrat Aishah as saying that this Surah is Makki. Kalbi and Muqatil also regard it as Makki, and the same is the view held by the majority of commentators. But Hadrat Hasan Basri, Ikrimah, Mujahid and Qatadah regard it as Madani. Imam Suyuti in <em>Al-Itqan</em> has confirmed this same view, and Imam Nawawi in his commentary of the <em>Sahih</em> of Muslim has also preferred the same. The reason for this assumption is the tradition which traditionists of the rank of Imam Ahmad, Muslim, Abu Daud, Nasai, Ibn Abi Shaibah, Ibn al-Mundhir, Ibn Marduyah, Baihaqi and others have related from Hadrat Anas bin Malik, saying: "The Holy Prophet was among us. In the meantime he dozed; then he raised his head, smiling, according to some traditions, the people asked what for he was smiling, according to others, he himself told them that a Surah had just been revealed to him. Then, with <em>Bismillah ir-Rahman
ir-Rahim</em>, he recited Surah Al-Kauthar; then he asked the people whether they knew what Kauthar was. When they said that Allah and his Messenger had the best knowledge, he said; It is a river which my Lord has granted me in Paradise." (The details follow under "<em>Kauthar</em> "). The basis of the reasoning from this tradition for this Surah's being Madani is that Hadrat Anas belonged to Madinah, and his saying that this Surah was revealed in his presence is a proof that it was Madani.</p>
<p>But, in the first place, from this same Hadrat Anas, Imam Ahmad, Bukhari, Muslim, Abu Da'ud, Tirmidhi and Ibn Jarir have related the traditions which say that this river of Paradise (<em>Al-Kauthar</em>) had been shown to the Holy Prophet (upon whom be peace) on the occasion of the <em>mi\`raj</em> (ascension) and everyone knows that <em>mi\`raj</em> had taken place at Makkah before the <em>hijrah</em>. Secondly, when during the <em>mi\`raj</em> the Holy Prophet had not only been informed of this gift of Allah Almighty but also shown it, there was no reason why Surah Al-Kauthar should have be revealed at Madinah to give him the good news of it. Thirdly, if in an assembly of the Companions the Holy Prophet himself had given the news of the revelation of Surah Al-Kauthar which Hadrat Anas has mentioned in his tradition, and it meant that that Surah had been revealed for the first time then, it was not possible that well-informed Companions like Hadrat Aishah, Hadrat Abdullah bin Abbas
and Hadrat Abdullah bin Zubair should have declared this Surah to be a Makki revelation and most of the commentators also should have regarded it as Makki. If the matter is considered carefully, there appears to be a flaw in the tradition from Hadrat Anas in that it does not say what was the subject under discussion in the assembly in which the Holy Prophet gave the news about Surah Al-Kauthar. It is possible that at that time the Holy Prophet was explaining something. In the meantime he was informed by revelation that that point was further explained by Surah Al-Kauthar, and he mentioned the same thing, saying that that Surah was revealed to him just then. Such incidents did take place on several occasions, on the basis of which the commentators have opined about certain verses that they were revealed twice. This second revelation, in fact, meant that the verse had been revealed earlier, but on some later occasion the Holy Prophet's attention was invited to it by revelation for
the second time. In such traditions, the mention of the revelation of a certain verse is not enough to decide whether it was revealed at Makkah or Madinah, and when precisely it was revealed.</p>
<p>Had this tradition of Hadrat Anas not been there to cause doubt, the whole content of the Surah Al-Kauthar by itself bears evidence that it was revealed at Makkah, and in the period when the Holy Prophet was passing through extremely discouraging conditions.</p>
<h2>Historical Background</h2>
<p>Before this in Surahs Ad-Duha and Alam Nashrah we have seen that when in the earliest phase of Prophethood the Holy Prophet (upon whom be peace) was passing through the most trying conditions when the whole nation had turned hostile, there was resistance and opposition on every side, and the Holy Prophet and a handful of his Companions did not see any remote chance of success. Allah in order to console and encourage him at that time had sent down several verses. In Surah Ad- Duha it was said: "And surely the later period (i.e. every later period) is better for you than the former period, and soon your Lord shall give you so much that you shall be well pleased". In Surah Alam Nashrah: "And We exalted your renown for you."That is, "Though the enemies are trying to defame you throughout the country, We, on the contrary, have arranged to exalt your name and fame."And: "The fact is that along with every hardship there is also ease."That is, "You should not be disheartened by the
severity of conditions at this time; this period of hardships will soon pass, and the period of success and victory will follow."</p>
<p>Such were the conditions in which Allah by sending down Surah Al-Kauthar consoled the Holy Prophet as well as foretold the destruction of his opponents. The disbelieving Quraish said: "Muhammad (upon whom be Allah's peace) is cut off from his community and reduced to a powerless and helpless individual. According to Ikrimah when the Holy Prophet was appointed a Prophet, and he began to call the people to Islam, the Quraish said: "Muhammad (upon whom be Allah's peace and blessings) is cut off from his people as a tree is cut off from its root, which might fall to the ground any moment." (Ibn Jarir). Muhammad bin Ishaq says: "Whenever the Prophet (upon whom be peace) was mentioned before As bin Wa'il as-Sehmi, the chief of Makkah, he used to say: Let him alone for he is only a childless man (<em>abtar</em>) with no male offspring. When he dies, there will be no one to remember him." Shamir bin Atiyyah says that Uqbah bin Abi Mu'ait, also used to say similar things about the Holy
Prophet, (Ibn Jarir). According to Ibn Abbas, once Ka'b bin Ashraf (the Jewish chief of Madinah) came to Makkah and the Quraish chiefs said to him: "Just see this boy, who is cut off from his people; he thinks he is superior to us, whereas we manage the Hajj, look after the Ka'bah and water the pilgrims." (Bazzar). Concerning this very incident Ikrimah reports that the Quraish had used the words <em>as-sunbur al-munbatir min qaumi-hi</em> (a weak, helpless and childless man who is cut off from his people) for the Holy Prophet. (Ibn Jarir) Ibn Sa'd and lbn Asakir have related that Hadrat Abdullah bin Abbas said; "The eldest son of the Holy Prophet (upon whom be peace) was Qasim; next to him was Zainab, next to her Hadrat Abdullah and next to him three daughters, viz. Umm Kulthum, Fatimah and Ruqayyah. Of them first Hadrat Qasim died and then Hadrat Abdullah. Thereupon As bin Wail said: "His line has come to an end: now he is <em>abtar</em> (i. e. cut of from root)."Some traditions add
that As said "Muhammad is <em>abtar</em> : he has no son to succeed him. When he dies, his memory will perish and you will be rid of him."The tradition from Ibn Abbas, which Abd bin Humaid has related, shows that Abu Jahl also had said similar words on the death of the Holy Prophet's son, Abdullah. Ibn Abi Hatim has related on the authority of Shmir bin Atiyyah that the same kind of meanness was shown by Uqbah bin Abi Mu'ait by rejoicing at this bereavement of the Holy Prophet. Ata says that when the second son of the Holy Prophet died, his own uncle, Abu Lahab (whose house was next to his) hastened to the pagans and gave them the "good news": <em>Batira Muhammadun al-lail</em> :"Muhammad has become childless this night, or he is cut off from root."</p>
<p>Such were the disturbing conditions under which Surah Al-Kauthar was sent down. The Quraish were angry with him because he worshiped and served only Allah and repudiated their idolatry publicly. For this very reason he was deprived of the rank, esteem and honor that he enjoyed among his people before Prophethood and was now as cut off from his community. The handful of his Companions also were helpless, poor people who were being persecuted and tyrannized. Furthermore, he was bereaved by the death of two sons, one after the other, whereat the near relatives and the people of his clan, brotherhood and neighborhood were rejoicing and uttering such words as were disheartening and disturbing for a noble person who had treated even his enemies most kindly. At this Allah just in one sentence of this brief Surah gave him the good news, better news than which has never been given to any man in the world, besides the decision that it will be his opponents who will be cut off from their
root and not he.</p>
`
