export default `
 <h2>Name</h2>
<p>This Surah has been named after Prophet Hud whose story has been related in vv. 50-60.</p>
<h2>Period of Revelation</h2>
<p>If we consider its theme deeply, we come to the conclusion that it was revealed during the same period as Surah Yunus and most probably followed it immediately.</p>
<h2>Subject</h2>
<p>The Surah deals with the same subject as Surah Yunus, that is, invitation to the Message, admonition and warning, with this difference that the warning is sterner. This is also supported by a Tradition:</p>
<p>It is related that after its revelation, once Hadrat Abu Bakr said to the Holy Prophet, "Of late I have been noticing that you are growing older and older. What is the cause of it?" The Holy Prophet replied, "Surah Hud and the like Surahs have made me old." This shows that it was a very hard time for the Holy Prophet and these stern warnings added greatly to his anxieties that were caused by the persecution from the Quraish, who were doing their worst to crush down the Message of Islam. For it was obvious to the Holy Prophet that the last limit of the respite given by Allah was approaching nearer and nearer and he was afraid lest the term of the respite should expire and his people be seized by the torment.</p>
<p>The invitation is this: Obey the Messenger of Allah; discard <em>shirk</em>, and worship Allah and Allah alone: establish the entire system of your life on the belief that you shall be called to account in the Hereafter.</p>
<p>The admonition is this: Remember that those people who put their faith in the outward appearance of this worldly life and rejected the Message of the Prophets met with dire consequences. Therefore you should consider it seriously whether you should follow the same way that history has proved to be the path to ruin.</p>
<p>The warning is this: You should not be deluded by the delay in the coming of the punishment: it is because of the respite that Allah has granted you by His grace so that you might mend your ways: if you do not make use of this opportunity, you shall be inflicted with an inevitable punishment that will destroy you all except the Believers.</p>
<p>Instead of addressing the people directly, the Quran has used the stories of the people of Noah, Hud, Salih, Lot, Shu'aib and Moses to achieve the above mentioned objects. What is most prominent in their stories is that when Allah passes His judgment on the people, He does not spare anyone whatsoever, even if he be the nearest relative of the Prophet of the time. Only that one is rescued who had believed in the Prophet, and none else, not even his own son or wife. More than that: the Faith demands from each and every Believer that he should totally forget his relationships when that judgment comes and remember only the relationship of the Faith. For it is against the spirit of Islam to show any regard whatsoever for the relationships of blood and race. And the Muslims demonstrated these teachings practically in the Battle of Badr, four years after the revelation of this Surah.</p>
`
