export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>nasr</em> occurring in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Hadrat Abdullah bin Abbas states that this is the last Surah of the Quran to be revealed, i. e. no complete Surah was sent down to the Holy Prophet after it. (Muslim Nasai, Tabarani, Ibn Abi Shaibah, Ibn Marduyah).</p>
<p>According to Hadrat Abdullah bin Umar, this Surah was sent down on the occasion of the Farewell Pilgrimage in the middle of the <em>Tashriq</em> Days at Mina, and after it the Holy Prophet rode his she camel and gave his well known Sermon. (Tirmidhi, Bazzar, Baihaqi, Ibn Abi Shaibah, Abd bin Humaid, Abn Yala, Ibn Marduyah). Baihaqi in <em>Kitab al- Hajj</em> has related from the tradition of Hadrat Sarra bint-Nabhan the Sermon which the Holy Prophet gave on this occasion. She says:</p>
<p>"At the Farewell Pilgrimage I heard the Holy Prophet say: O people, do you know what day it is? They said: Allah and His Messenger have the best knowledge. He said: This is the middle day of the <em>Tashriq</em> Days. Then he said: Do you know what place it is? They said: Allah and His Messenger have the best knowledge. He said: This is <em>Masharil-Haram</em>. Then he said: I do not know, I might not meet you here again. Beware, your bloods and your honors are forbidden, until you appear before your Lord, and He questions you about your deeds. Listen: let the one who is near convey it to him who is far away. Listen: have I conveyed the message to you? Then, when we returned to Madinah, the Holy Prophet passed away not many days after that."</p>
<p>If both these traditions are read together, it appears that there was an interval of three months and some days between the revelation of Surah An-Nasr and the Holy Prophet's death, for historically the same was the interval between the Farewell Pilgrimage and the passing away of the Holy Prophet.</p>
<p>Ibn Abbas says that when this Surah was revealed, the Holy Prophet said that he had been informed of his death and his time had approached. (Musnad Ahmad, Ibn Jarir, Ibn al-Mundhir, Ibn Marduyah). In the other traditions related from Hadrat Abdullah bin Abbas, it has been stated that at the revelation of this Surah the Holy Prophet understood that he had been informed of his departure from the world.(Musnad Ahmad, Ibn Jarir, Tabarani, Nasai, Ibn Abi Hatim, Ibn Marduyah).</p>
<p>Mother of the Believers, Hadrat Umm Habibah, says that when this Surah was revealed the Holy Prophet said that he would leave the world that year. Hearing this Hadrat Fatimah wept. Thereat he said: "From among my family you will be the first to join me." Hearing this she laughed.(Ibn Abi Hatim, Ibn Marduyah). A tradition containing almost the same theme has been related by Baihaqi from Ibn Abbas.</p>
<p>Ibn Abbas says: "Hadrat Umar used to invite me to sit in his assembly along with some of the important elderly Companions who had fought at Badr. This was not liked by some of them. They complained that they also had sons who were like the boy. Why then was he in particular invited to sit in the assembly? (Imam Bukhari and Ibn Jarir have pointed out that such a thing was said by Hadrat Abdur Rahman bin Auf).</p>
<p>Hadrat Umar said that the boy enjoyed the position and distinction because of his knowledge. Then one day he invited the Companions of Badr and called me also to sit with them. I understood that he had invited me to the assembly to prove his contention. During the conversation Hadrat Umar asked the Companions of Badr: "What do you say about <em>Idha jaa nasrullahi wal- fath</em>?" Some said: "In it we have been enjoined to praise Allah and ask for His forgiveness when His succor comes and we attain victory."Some others said that it implied the conquest of cities and forts. Some kept quiet. Then Hadrat Umar said: "Ibn Abbas, do you also say the same?"I said no. He asked: "What then is your view?"I submitted that it implied the last hour of Allah's Messenger (upon whom be peace); in it he was informed that when Allah's succor came and victory was attained, it would be a sign that his hour had come; therefore, he should praise Allah and ask for His forgiveness. Thereat Hadrat Umar
said "I know naught but what you have said."</p>
<p>In another tradition there is the addition that, Hadrat Umar said to the Companions: "How can you blame me when you yourselves have seen why I invite this boy to join the assembly?" (Bukhari, Musnad Ahmad, Tirmidhi, Ibn Jarir, Ibn Marduyah, Baghawi, Baihaqi, Ibn al-Mundhir).</p>
<h2>Theme and Subject Matter</h2>
<p>As is shown by the above traditions, Allah in this Surah had informed His Messenger (upon whom be peace) that when Islam attained complete victory in Arabia and the people started entering Allah's religion in great numbers, it would mean that the mission for which he had been sent to the world, had been fulfilled. Then, he was enjoined to busy himself in praising and glorifying Allah by Whose bounty he had been able to accomplish such a great task, and should implore Him to forgive whatever failings and frailties he might have shown in the performance of the service. Here, by a little consideration one can easily see the great difference that there is between a Prophet and a common worldly leader. If a worldly leader in his own lifetime is able to bring about a revolution, which has the aim and objective of his struggle, this would be an occasion for exultation for him. But here we witness quite another phenomenon. The Messenger of Allah in a brief space of 23 years
revolutionized an entire nation as regards its beliefs, thoughts, customs, morals, civilization, ways of living, economy, politics and fighting ability, and raising it from ignorance and barbarism enabled it to conquer the world and become leader of nations; yet when he had accomplished this unique task, he was not enjoined to celebrate it but to glorify and praise Allah and to pray for His forgiveness, and he busied himself humbly the implementation of that command.</p>
<p>Hadrat Aishah says: "The Holy Messenger (upon whom be peace) often used to recite <em>Subhanak-Allahumma wa bi-hamdika astaghfiruka wa atubu ilaika</em> (according to some other traditions, <em>Subhan Allahi wa bi hamdi-hi as- taghfirullaha wa atubu ilaihi</em>) before his death. I asked: O Messenger of Allah, what are these words that you have started reciting now? He replied: A sign has been appointed for me so that when I see it, I should recite these words, and it is: <em>Idha jaa nasrullahi wal-fathu</em>." (Musnad Ahmad, Muslim, Ibn Jarir, lbn al-Mundhir, Ibn Marduyah).</p>
<p>In some other traditions on the same subject Hadrat Aishah has reported that the Holy Prophet often recited the following words in his ruku and sajdah: Subhanak-Allahumma wa-bi hamdika, Allahumma- aghfirli. This was the interpretation of the Quran (i. e. of Surah An-Nasr) that he had made.(Bukhari, Muslim Abu Daud, Nasai, Ibn Majah, Ibn Jarir).</p>
<p>Hadrat Umm Salamah says that the Holy Prophet (upon whom be peace) during his last days very often recited the following words sitting and standing, going out of the house and coming back to it: <em>Subhan Allahi wa-bi hamdi-hi</em>. I one day asked: "Why do you recite these words so often? O Messenger of Allah". He replied: I have been enjoined to do so. Then he recited this Surah." (Ibn Jarir).</p>
<p>According to Hadrat Abdullah bin Masud, when this Surah was revealed, the Messenger of Allah (upon whom be peace) frequently began to recite the words <em>Subhanak-Allahumma wa bi-hamdika, Allahumm-aghfirli, subhanaka Rabbana wa bi-hamdika, Allahumm-aghfirli, innaka anta at- Tawwab al-Ghafur</em>.(Ibn Jarir, Musnad Ahmad, Ibn Abi Hatim).</p>
<p>Ibn Abbas has stated that after the revelation of this Surah the Holy Messenger (upon whom be peace) began to labor so intensively and devotedly hard for the Hereafter as he had never done before.</p>;
`
