export default `
 <h2>Name</h2>
<p><em>Al-Ikhlas</em> is not merely the name of this Surah but also the title of its contents, for it deals exclusively with <em>Tauhid</em>. The other Surahs of the Quran generally have been designated after a word occurring in them, but in this Surah the word <em>Ikhlas</em> has occurred nowhere. It has been given this name in view of its meaning and subject matter. Whoever understands it and believes in its teaching, will get rid of <em>shirk</em> (polytheism) completely.</p>
<h2>Period of Revelation</h2>
<p>Whether it is a Makki or a Madani Surah is disputed, and the difference of opinion has been caused by the traditions which have been related concerning the occasion of its revelation. We give them below ad seriatim:</p>
<ol>
  <li>
    <p>Hadrat Abdullah bin Masud has reported that the Quraish said to the Holy Prophet (upon whom be be peace): "Tell us of the ancestry of your Lord." Thereupon this Surah was sent down. (Tabarani).</p>
  </li>
  <li>
    <p>Abul Aliyah has related on the authority of Hadrat Ubayy bin Kab that the polytheists said to the Holy Prophet (upon whom be peace): “Tell us of your Lord's ancestry." Thereupon Allah sent down this Surah. (Musnad Ahmad, Ibn Abi Harim, Ibn Jarir, Tirmidhi, Bukhari in <em>At-Tarikh</em>, Ibn al-Mundhir, Hakim, Baihaqi). Tirmidhi has related a tradition on the same theme from Abul Aliyah, which does not contain any reference to Hadrat Ubayy bin Kab, and has declared it to be more authentic.</p>
  </li>
  <li>
    <p>Hadrat Jabir bin Abdullah has stated that a bedouin (according to other traditions, some people) said to the Holy Prophet (upon whom be peace): "Tell us of your Lord's ancestry." Thereupon Allah sent down this Surah.(Abu Yala, Ibn Jarir, Ibn al-Mundhir, Tabarani in <em>Al-Ausat</em>, Baihaqi, Abu Nuaim in <em>Al-Hilyah</em>).</p>
  </li>
  <li>
    <p>Ikrimah has related a tradition form Ibn Abbas, saying that a group of the Jews, including Kab bin Ashraf, Huyayy bin Akhtab and other, came before the Holy Prophet (upon whom be peace) and said: "O Muhammad (upon whom be Allah's peace and blessings), tell us of the attributes of your Lord, who has sent you as a Prophet." Thereupon Allah sent down this Surah. (Ibn Abi Hatim, Ibn Adi, Baihaqi in <em>Al-Asma</em> was-<em>Sifat</em>).</p>
    <p>In addition to these, some other traditions also have been cited by Ibn Taimiyyali in his commentary of Surah Al-Ikhlas, which are as follows;</p>
  </li>
  <li>
    <p>Hadrat Anas has stated that some Jews of Khaiber came before the Holy Prophet (upon whom be peace) and they said: "O Abul Qasim, Allah created the angels from light, Adam from rotten clay, Iblis from the flame of fire, the sky from smoke, and the earth from the foam of water. Now tell us about your Lord (of what He is made)." The Holy Prophet (upon whom be peace) did not give any reply to this question. Then Gabriel came and he said: "O Muhammad, say to them: <em>Huwa Allahu ahad</em>."</p>
  </li>
  <li>
    <p>Amir bin at-Tufail said to the Holy Prophet: "O Muhammad, what do you call us to?"The Holy Prophet replied: "To Allah." Amir said, "Then, tell us of what He is made, whether of gold, silver, or iron?" Thereupon this surah was sent down.</p>
  </li>
  <li>
    <p>Dahhak, Qatadah and Muqatil have stated that some Jewish rabbis came before the Holy Prophet, and they said: "O Muhammad, tell us what is your Lord like, so that we may believe in you. Allah in the Torah has sent down His description. Kindly tell us of what He is made, what is His sex, whether He is made of gold, copper, brass, iron, or silver, and whether He eats and drinks. Also tell us from whom He has inherited the world, and who will inherit it after Him." Thereupon Allah sent down this Surah.</p>
  </li>
  <li>
    <p>Ibn Abbas has reported that a deputation of the Christians of Najran along with seven priests visited the Holy Prophet upon whom be peace), and they said: "O Muhammad, tell us what is your Lord like and of what substance He is made."The Holy Prophet replied, "My Lord is not made from any substance. He is unique and exalted above everything." Thereupon Allah sent down this Surah.</p>
  </li>
</ol>
<p>These traditions show that different people on different occasions had questioned the Holy Prophet (upon whom be peace) about the essence and nature of the God to Whose service and worship he invited the people, and on every occasion he recited by Allah's command this very Surah in response. First of all, the pagans. of Quraish asked him this question in Makkah, and in reply this Surah was sent down. Then, at Madinah, sometimes the Christians, and sometimes the other people of Arabia, asked him questions of this nature, and every time Allah inspired him to recite this very Surah in answer to them. In each of these traditions, it has been said that this Surah was revealed on this or that occasion. From this one should not form the impression that all these traditions are mutually contradictory. The fact is that whenever there existed with the Holy Prophet a verse or a Surah previously revealed in respect of a particular question or matter, and later the same question was
presented before him, Allah inspired him to recite the same verse or Surah to the people as it contained the answer to their question. The reporters of <em>Hadith</em> describe the same thing, saying: When such and such a question or matter was presented before the Holy Prophet, such and such a verse or Surah was revealed. This has also been described as repetition of revelation, i. e. the revelation of a verse or Surah several times.</p>
<p>Thus, the fact is that this Surah is Makki, rather in view of its subject matter a Surah revealed in the earliest period at Makkah, when detailed verses of the Quran dealing with the essence and attributes of Allah Almighty had not yet been revealed, and the people hearing, the Holy Prophet's invitation to Allah, wanted to know what was his Lord like to whose worship and service he was calling them. Another proof of this Surah's being one of the earliest Surahs to be revealed is that when in Makkah Umayyah bin Khalaf, the master of Hadrat Bilal, made him lie down on burning sand and placed a heavy stone on his chest, Bilal used to cry "<em>Ahad, Ahad</em> !" This word was derived from this very Surah.</p>
<h2>Theme and Subject Matter</h2>
<p>A little consideration of the traditions regarding the occasion of the revelation of this Surah, shows what were the religious concepts of the world at the time the Holy Prophet began to preach the message of <em>Tauhid</em>. The idolatrous polytheists were worshiping gods made of wood, stone, gold, silver and other substances. These gods had a form, shape and body. The gods and goddesses were descended from each other. No goddess was without a husband and no god without a wife. They stood in need of food and drink and their devotees arranged these for them. A large number of the polytheists believed that God assumed human form and there were some people who descended from Him. Although the Christians claimed to believe in One God, yet their God also had at least a son, and besides the Father and Son, the Holy Ghost also had the honor of being an associate in Godhead: so much so that God had a mother and a mother-in-law too. The Jews also claimed to believe in One God, but their
God too was not without physical, material and other human qualities and characteristics. He went for a stroll, appeared in human form, wrestled with a servant of His, and was father of a son, Ezra. Besides these religious communities, the Zoroastrians were fire worshipers, and the Sabeans star worshipers. Under such conditions when the people were invited to believe in Allah, the One Who has no associate, it was inevitable that questions arose in the minds as to what kind of a God it was, Who was one and Only Lord and invitation to believe in Whom was being given at the expense of all other gods and deities. It is a miracle of the Quran that in a few words briefly it answered all the questions and presented such a clear concept of the Being of Allah as destroyed all polytheistic concepts, without leaving any room for the ascription of any of the human qualities to His Being.</p>
<h2>Merit and Importance</h2>
<p>That is why the Holy Messenger of Allah (upon whom be peace) held this Surah in great esteem, and he made the Muslims realize its importance in different ways so that they recited it frequently and disseminated it among the people. For it states the foremost and fundamental doctrine of Islam (viz. <em>Tauhid</em>) in four such brief sentences as are immediately impressed on human memory and can be read and recited easily. There are a great number of the traditions of <em>Hadith</em>, which show that the Holy Prophet on different occasions and in different ways told the people that this Surah is equivalent to one third the Quran. Several <em>ahadith</em> on this subject have been related in Bukhari, Muslim, Abu Daud; Nasai, Tirmidhi, Ibn Majah, Musnad Ahmad, Tabarani and other books, on the authority of Abu Said Khudri, Abu Hurairah, Abu Ayyub Ansari, Abu ad-Darda, Muadh bin Jabal, Jabir bin Abdullah, Ubayy bin Kab, Umm Kulthum bint Uqbah bin Abi Muait, Ibn Umar, Ibn Masud,
Qatadah bin an-Numan, Anas bin Malik, and Abu Masud (may Allah be pleased with all of them).</p>
<p>The commentators have given many explanations of the Holy Prophet's saying. But in our opinion it simply means that the religion presented by the Quran is based on three doctrines: <em>Tauhid</em>, Prophethood and the Hereafter. This Surah teaches <em>Tauhid</em>, pure and undefiled. Therefore, the Holy Prophet (upon whom he Peace) regarded it as, equal to one-third of the Quran.</p>
<p>A tradition on the authority of Hadrat Aishah has been related in Bukhari, Muslim and other collections of the <em>Ahadith</em>, saying that the Holy Prophet sent a man as leader of an expedition. During the journey he concluded his recitation of the Quran in every Prayer with <em>Qul Huwa-Allahu ahad</em>. On their return him companions mentioned this before the Holy Prophet. He said: "Ask him why he did so." When the man was asked, he replied: "In this Surah the attributes of the Merciful God have been stated; therefore, I love to recite it again and again." When the Holy Prophet heard this reply, he said to the people: "Inform him that Allah holds him in great love and esteem."</p>
<p>A similar incident has been related in Bukhari, on the authority of Hadrat Anas. He says: "A man from among the Ansar led the Prayers in the Quba Mosque. His practice was that in every <em>rak\`ah</em> he first recited this Surah and then would join another Surah to it. The people objected to it and said to him:"Don't you think that Surah Ikhlas is by itself enough? Why do you join another Surah to it? You should either recite only this surah, or should leave it and recite some other Surah. He said: "I cannot leave it, I would rather give up leadership in the Prayer, if you so desired." The people did not approve that another man be appointed leader instead of him. At last, the matter was brought before the Holy Prophet. He asked the man, "What prevents you from conceding what your companions desire? What makes you recite this particular Surah in every <em>rak\`ah</em>?" The man replied: "I have great love for it." The Holy Prophet remarked: "Your this love for this Surah has
earned you entry into Paradise."</p>;
`
