export default `
 <h2>Name</h2>
<p>This Surah takes its name from the word (<em>ar-Ra'ad</em>) (thunder) that occurs in v. 13. It is merely the symbolic name of the Surah and does not in any way mean that the Surah deals with the scientific problems connected with thunder.</p>
<h2>Period of Revelation</h2>
<p>The internal evidence (vv. 27-31 and vv. 34-48) shows that this Surah was revealed in the last stage of the Mission of the Holy Prophet at Makkah and during the same period in which Surahs Yunus, Hud and Al- A'araf were sent down. The manner of speech indicates that a long time had passed since the Holy Prophet had been conveying the Message. On the one hand, his opponents had been contriving different devices to defeat him and his Mission, and, on the other, his followers had been expressing a desire that by showing a miracle the disbelievers might be brought to the Right Way. In answer, Allah impressed on the Believers that it is not His way to convert people by this method and that they should not lose heart, if He is giving the enemies of the Truth a rope long enough to hang themselves. Otherwise, He is able to show such signs as may bring the dead out of their graves and make them speak (v. 31), but even then these obdurate people will invent an excuse to explain this away.
All this decisive evidence clearly proves that this Surah was revealed during the last stage of the Prophet's Mission at Makkah.</p>
<h2>Central Theme</h2>
<p>The first verse enunciates the main theme of this Surah, that is, "The Message of Muhammad (Allah's peace be upon him) is the very Truth, but it is the fault of the people that they are rejecting it." This is the pivot on which the whole Surah turns. This is why it has been shown over and over again in different ways that the basic components of the Message -- <em>Tauhid</em>, Resurrection and Prophethood-are a reality: therefore they should believe sincerely in these for their own moral and spiritual good. They have been warned that they shall incur their own ruin if they reject them, for <em>kufr</em> by itself is sheer folly and ignorance. Moreover, the aim of the Surah is not merely to satisfy the minds but also to appeal to the hearts to accept the Faith. Therefore it does not merely put forward logical arguments in support of the truth of the Message and against the people's wrong notions, but at appropriate intervals it makes frequent use of sympathetic and earnest appeals
to win over their hearts by warning them of the consequences of <em>kufr</em> and by holding out the happy rewards of Faith so that the foolish people should give up their obduracy.</p>
<p>Besides this, the objections of the opponents have been answered without any mention of them, and those doubts which are proving a hindrance in the way of the Message or were being created by the opponents have been removed. At the same time, the Believers; who had been passing through long and hard ordeal and were feeling tired, and waiting anxiously for Allah's succor, have been comforted and filled with hope and courage.</p>;
`
