export default `
 <h2>Name</h2>
<p>This Surah takes its name (Bani Israil) from v. 4. But this name is merely a distinctive appellation like the names of many other surahs and not a descriptive title, and does not mean that "Bani Isra'il" is the theme of this Surah.</p>
<h2>Period of Revelation</h2>
<p>The very first verse indicates that this Surah was revealed on the occasion of <em>Mi\`raj</em> (Ascension). According to the Traditions and books on the life of the Holy Prophet, this event happened one year before Hijrah. Thus, this Surah is one of those which were revealed in the last stage of Prophethood at Makkah.</p>
<h2>Background</h2>
<p>The Holy Prophet had been propagating <em>Tauhid</em> for the previous twelve years and his opponents had been doing all they could to make his Mission a failure, but in spite of all their opposition, Islam had spread to every corner of Arabia and there was hardly any clan which had not been influenced by his invitation. In Makkah itself the true Believers had formed themselves into a small community and were ready and willing to face every danger to make Islam a success. Besides them, a very large number of the people of Aus and Khazraj (two influential clans of Al-Madinah) had accepted Islam. Thus the time had come for the Holy Prophet to emigrate from Makkah to Al- Madinah and there gather together the scattered Muslims and establish a state based on the principles of Islam.</p>
<p>These were the conditions when <em>Mi\`raj</em> took place and on his return the Holy Prophet brought down the Message contained in this Surah.</p>
<h2>Theme and Topics</h2>
<p>This Surah is a wonderful combination of warning, admonition and instruction, which have been blended together in a balanced proportion.</p>
<p>The disbelievers of Makkah had been admonished to take a lesson from the miserable end of the Israelites and other communities and mend their ways within the period of respite given by Allah, which was about to expire. They should, therefore, accept the invitation that was being extended by Muhammad (Allah's peace be upon him) and the Quran. Otherwise they shall be annihilated and replaced by other people. Incidentally, the Israelites, with whom Islam was going to come in direct contact in the near future at Al-Madinah have also been warned that they should learn a lesson from the chastisements that have already been inflicted on them. They were warned, "Take advantage of the Prophethood of Muhammad (Allah's peace be upon him) because that is the last opportunity which is being given to you. If even now you behave as you have been behaving, you shall meet with a painful torment."</p>
<p>As regards the education of mankind, it has been impressed that human success or failure, gain or loss, depends upon the right understanding of <em>Tauhid</em>, life-after- death and Prophethood. Accordingly, convincing arguments have been put forward to prove that the Quran is the Book of Allah and its teachings are true and genuine the doubts of the disbelievers about these basic realities have been removed and on suitable occasions they have been admonished and rebuked in regard to their ways of ignorance.</p>
<p>In this connection, those fundamental principles of morality and civilization on which the Islamic System of life is meant to be established have been put forward. Thus this was a sort of the Manifesto of the intended Islamic state which had been proclaimed a year before its actual establishment. It has been explicitly stated that that was the sketch of the system on which Muhammad (Allah's peace be upon him) intended to build human life first in his own country and then in the outside world.</p>
<p>Besides these, the Holy Prophet has been instructed to stick firmly to his stand without minding the opposition and difficulties which he was encountering and should never think of making a compromise with unbelief. The Muslims who sometimes showed signs of impatience, when they met with persecution, calumny, and crooked arguments, have also been instructed to face adverse circumstances with patience and fortitude and keep full control over their feelings and passions. Moreover, salat was prescribed in order to reform and purify their souls, as if to say, "This is the thing which will produce in you those high qualities of character which are essential for everyone who intends to struggle in the righteous way Incidentally, we learn from Traditions that Mi'raj was the first occasion on which the five daily Prayers were prescribed to be offered at fixed times.</p>
`
