export default `
 <h2>Name</h2>
<p>It takes its name from v. 16.</p>
<h2>Period of Revelation</h2>
<p>It was revealed before the Migration to Habash. We learn from authentic Traditions that Hadrat Ja'afar recited vv. 1-40 of this Surah in the court of Negus when he called the migrants to his court.</p>
<h2>Historical Background</h2>
<p>We have already briefly referred to the conditions of that period in the introduction to Surah Al-Kahf. Here we shall give rather fuller details of the same conditions, which will be helpful in grasping the meaning of this Surah and the other Surahs of the period. When the chiefs of the Quraish felt that they had failed to suppress the Islamic movement by ridicule, sarcasm, and by holding out promises and threats and by making false accusations, they resorted to persecution, beating and economic pressure. They would catch hold of the new Muslims of their clans and persecute them, starve them and would even inflict physical torture on them in order to coerce them to give up Islam. The most pitiful victims of their persecution were the poor people and the slaves and the proteges of the Quraish. They were beaten black and blue, were imprisoned and kept thirsty and hungry and were dragged on the burning sands of Makkah. The people would get work from the professional laborers but
would not pay them their wages. As an instance we give below the story of Hadrat Khabbab bin Arat, which is given in <em>Bukhari</em> and <em>Muslim</em> :</p>
<p>"I used to work as a blacksmith in Makkah. Once I did some work for As bin Wa'il. When I went to ask for my wages, he said, 'I will not pay your wages unless you disown Muhammad'."</p>
<p>In the same connection Hadrat Khabbab says, "One day the Holy Prophet was sitting in the shadow of the Ka'abah. I went to him and said, '0 Messenger of Allah, now persecution has gone to its extreme; why do you not pray to Allah (for relief)?' At this the Holy Prophet was greatly moved. He said, 'The believers before you were persecuted much more than you. Their bones were scraped with combs of iron and their heads were cut with saws, but still they did not give up their Faith. I assure you that Allah will fulfill this Mission, and there will come a period of such peace that one would travel from Sanna to Hadramaut, and he will have no fear from anyone, save Allah. But you people have already become impatient'." (<em>Bukhari</em>)</p>
<p>When the conditions became unbearable, the Holy Prophet, in the month of Rajab of the fifth year of Prophethood, gave advice to his Companions to this effect: "You may well migrate to Habash, for there is a king, who does not allow any kind of injustice to anyone, and there is good in his land. You should remain there till the time that Allah provides a remedy for your affliction".</p>
<p>Accordingly, at first, eleven men and four women left for Habash. The Quraish pursued them up to the coast but fortunately they got a timely boat for Habash at the sea-port of Shu'aibah, and they escaped attest. Then after a few months, other people migrated to Habash and their number rose to eighty-three men and eleven women of the Quraish and seven non-Quraish. After this, only forty persons were left with the Holy Prophet at Makkah.</p>
<p>There was a great hue and cry in Makkah after this Migration, for every family of the Quraish was adversely affected by this. There was hardly a family of the Quraish which did not lose a son, a son-in-law, a daughter, a brother or a sister. For instance, there were among the Migrants the near relatives of Abu Jahl, Abu Sufyan and other chief of the Quraish who were notorious for their persecution of the Muslims. As a result of this, some of them became even more bitter in their enmity of Islam, while there were others who were so moved by this that they embraced Islam. For instance, this Migration left a deep mark on Hadrat Umar. One of his relatives, Laila, daughter of Hathmah, says, "I was packing my luggage for Migration, while my husband, Amr bin Rabiy'ah, had gone out. In the meantime Umar came there and began to watch me, while I was engaged in preparation for the journey. Then he said, 'Are you also going to migrate?' I answered, 'Yes by God, you people have persecuted
us much. But the wide earth of Allah is open for us. Now we are going to a place where Allah will grant us peace'. At this, I noticed such signs of emotion on the face of Umar as I had never seen before. He simply said, 'May God be with you' and went away."</p>
<p>After the migration, the Quraish held consultations, and decided to send Abdullah bin Abi Rabiy'ah, half brother of Abu Jahl, and Amr bin As to Habash with precious gifts so as to persuade Negus to send the migrants back to Makkah. Hadrat Umm Salmah (a wife of the Holy Prophet), who was among the migrants, has related this part of the story in detail. She says, "When these two clever statesmen of the Quraish reached Habash, they distributed the gifts among the courtiers of the King and persuaded them to recommend strongly to him to send the migrants back. Then they saw Negus himself and, presenting rich gifts to him, said, "Some headstrong brats of our city have come to your land and our chiefs have sent us to you with the request that you may kindly send them back. These brats have forsaken our faith and have not embraced your faith either, but have invented a new faith". As soon as they had finished their speech, all the courtiers recommended their case, saying, "We should
send such people back to their city for their people know them better. It is not proper for us to keep them here." At this the King was annoyed and said, "I am not going to give them back without proper inquiry. As these people have put their trust in my country rather than in any other country and have come here to take shelter, I will not betray them. At first I will send for them and investigate into the allegations these people have made against them. Then I will make my final decision". Accordingly, the King sent for the Companions of the Holy Prophet and asked them to come to his court.</p>
<p>When the migrants received the message of the King, they assembled and held consultations as to what they should say to the King. At last they came to this unanimous decision: "We will present before the King the teachings of the Holy Prophet without adding anything to or withholding anything from them and leave it to him whether he lets us remain here or turns us out of his country". When they came to the court, the King put this problem abruptly before them:"I understand that you have given up the faith of your own people and have neither embraced my faith nor any other existing faith. I would like to know what your new faith is." At this, Jafar bin Abi Talib, on behalf of the migrants, made an extempore speech to this effect: "O King! We were sunk deep in ignorance and had become very corrupt; then Muhammad (Allah's peace be upon him) came to us as a Messenger of God, and did his best to reform us. But the Quraish began to persecute his followers, so we have come to your
country in the hope that here we will be free from persecution". After his speech, the King said, "Please recite a piece of the Revelation which has been sent down by God to your Prophet". In response, Hadrat Jafar recited that portion of Surah Maryam which relates the story of Prophets John and Jesus (Allah's peace be upon them). The King listened to it and wept, so much so that his beard became wet with tears. When Hadrat Jafar finished the recital, he said:"Most surely this Revelation and the Message of Jesus have come from the same source. By God I will not give you up into the hands of these people".</p>
<p>Next day \`Amr bin \`As went to Negus and said, "Please send for them again and ask them concerning the creed they hold about Jesus, the son of Mary, for they say a horrible thing about him". The King again sent for the migrants, who had already learned about the scheme of Amr. They again sat together and held consultations in regard to the answer they should give to the King, if he asked about the belief they held about Prophet Jesus. Though this was a very critical situation and all of them were uneasy about it, they decided that they would say the same thing that Allah and His Messenger had taught them. Accordingly, when they went to the court, the King put them the question that had been suggested by Amr bin As. So Jafar bin Abi Talib stood up and answered without the least hesitation: "He was a Servant of Allah and His Messenger. He was a Spirit and a Word of Allah which had been sent to virgin Mary." At this the King picked up a straw from the ground and said, 'Bye God,
Jesus was not worth this straw more than what you have said about him." After this the King returned the gifts sent by the Quraish, saying, "I do not take any bribe". Then he said to the migrants, "You are allowed to stay here in perfect peace."</p>
<h2>Theme and Subject</h2>
<p>Keeping in view this historical background, it becomes quite obvious that this Surah was sent down to serve the migrants as a "provision" for their journey to Habash, as if to say, "Though you are leaving your country as persecuted emigrants to a Christian country, you should not in the least hide anything from the teachings you have received. There- fore you should plainly say to the Christians that Prophet Jesus was not the son of God."</p>
<p>After relating the story of Prophets John and Jesus in vv. 1-40, the story of Prophet Abraham has been related (vv. 41-50) also for the benefit of the Migrants for he also had been forced like them to leave his country by the persecution of his father, his family and his country men. On the one hand, this meant to console the Emigrants that they were following the footsteps of Prophet Abraham and would attain the same good end as that Prophet did. On the other hand, it meant to warn the disbeliever, of Makkah that they should note it well that they were in the position of the cruel people who had persecuted their forefather and leader, Abraham, while the Muslim Emigrants were in the position of Prophet Abraham himself.</p>
<p>Then the mention of the other Prophets has been made in vv. 51-65 with a view to impress that Muhammad (Allah's peace be upon him) had brought the same way of Life that had been brought by the former Prophets but their followers had become corrupt and adopted wrong ways.</p>
<p>In the concluding passage (vv. 66-98), a strong criticism has been made of the evil ways of the disbelievers of Makkah, while the Believers have been given the good news that they would come out successful and become the beloved of the people, in spite of the worst efforts of the enemies of the Truth.</p>;
`
