export default `
 <h2>Name</h2>
<p>This Surah takes its name, An Nur, from verse 35.</p>
<h2>Period of Revelation</h2>
<p>The consensus of opinion is that it was sent down after the Campaign against Bani al-Mustaliq and this is confirmed by vv. 11-20 that deal with the incident of the "Slander", which occurred during that Campaign. But there is a difference of opinion as to whether this Campaign took place in 5 A. H. before the Battle of the Trench or in 6 A. H. after it. It is important to decide this issue in order to determine whether this Surah was sent down earlier or Surah Al- Ahzab(XXXIII), which is the only other Surah containing the Commandments about the observance of purdah by women. Surah Al-Ahzab was admittedly sent down on the occasion of the Battle of the Trench. Now if this Battle occurred earlier, it would mean that the initial instructions in connection with the Commandments of purdah were sent down in Surah Al-Ahzab and they were complemented later by the Commandments revealed in this Surah. On the other hand, if the Campaign against Bani al-Mustaliq occurred earlier, the
chronological order of the Commandments would be reversed, and it would become difficult to understand the legal wisdom and implications of the Commandments of purdah.</p>
<p>According to Ibn Sa'd, the Campaign against Bani al Mustaliq took place in Shaban 5 A. H. and the Battle of the Trench in Zil- Qa'dah the same year. This opinion is based on some traditions from Hadarat Ayesha about the events connected with the "Slander" in which she refers to a dispute between Hadrat Sa'd bin 'Ubadah and Sa'd bin Mu'az. Hadrat Sa'd bin Mu'az, according to authentic traditions, died during the Campaign against Bani Quraizah, which took place immediately after the Battle of the Trench. It is, therefore, evident that he could not be present in 6 A. H. to take part in a dispute about the "Slander".</p>
<p>On the other hand, Muhammad bin Ishaq says that the Battle of the Trench took place in Shawwal 5 A. H. and the Campaign against Bani al-Mustaliq in Sha'ban 6 A. H. This opinion is supported by many authentic traditions from Hadrat Ayesha and others. According to these traditions, (1) the Commandments about purdah had been sent down in Surah Al-Ahzab before the incident of the "Slander", (2) the Holy Prophet had married Hadrat Zainab in Zil-Qa'dah 5 A. H. after the Battle of the Trench, (3) Hamnah, sister of Hadrat Zainab, had taken a leading part in spreading the "Slander", just because Hadrat Ayesha was a rival of her sister. All this evidence supports the view of Muhammad bin Ishaq.</p>
<p>Now let us consider the two opinions a little more closely. The only argument in favor of the first opinion is the mention of the presence of Hadrat Sa'd bin Mu'az in a dispute connected with the incident of the "Slander". But this argument is weakened by some other traditions from Hadrat Ayesha, in which she mentions Hadrat Usaid bin Hudair instead of Hadrat Sa'd bin Mu'az in this dispute. It may, therefore, be assumed that there has been some confusion regarding the two names in reporting the traditions. Moreover, if we accept the first opinion, just because of the mention of the name of Hadrat Sa'd bin Mu'az in some traditions, we encounter other difficulties that cannot be resolved in any way. For, in that case, we shall have to admit that the revelation of the Commandments of purdah and the Holy Prophet's marriage with Hadrat Zainab had taken place even earlier than the Battle of the Trench. But we learn from the Qur'an and many authentic traditions that both these events
happened after that Battle and the Campaign against Bani Quraizah. That is why Ibn Hazm, Ibn Qayyim and some other eminent scholars have held the opinion of Muhammad bin Ishaq as correct, and we also hold it to be so. Thus, we conclude that Surah Al Ahzab was sent down earlier than Surah An-Nur, which was revealed in the latter half of 6 A. H. several months after Surah Al Ahzab.</p>
<h2>Historical Background</h2>
<p>Now let us review the circumstances existing at the time of the revelation of this surah. It should be kept in mind that the incident of the "Slander", which was the occasion of its revelation, was closely connected with the conflict between Islam and the disbelievers.</p>
<p>After the victory at Badr, the Islamic movement began to gain strength day by day; so much so that by the time of the Battle of the Trench, it had become so strong that the united forces of the enemy numbering about ten thousand failed to crush it and had to raise the siege of Al Madinah after one month. It meant this, and both the parties understood it well, that the war of aggression which the Disbelievers had been waging for several years, had come to an end. The Holy Prophet himself declared: "After this year, the Quraish will not be able to attack you; now you will take the offensive."</p>
<p>When the disbelievers realized that they could not defeat Islam on the battlefield, they chose the moral front to carry on the conflict. It cannot be said with certainty whether this Change of tactics was the outcome of deliberate consultations, or it was the inevitable result of the humiliating retreat in the Battle of the Trench, for which all the available forces of the enemy had been concentrated:They knew it well that the rise of Islam was nor due to the numerical strength of the Muslims nor to their superior arms and ammunition nor to their greater material resources; nay, the Muslims were fighting against fearful odds on all these fronts. They owed their success to their moral superiority. Their enemies realized that the pure and noble qualities of the Holy Prophet and his followers were capturing the hearts of the people, and were also binding them together into a highly disciplined community. As a result of this, they were defeating the <em>mushriks</em> and the Jews
both on the peace and on the war front, because the latter lacked discipline and character.</p>
<p>Under the above mentioned circumstances, the wicked designs of the disbelievers led them to start a campaign of vilification against the Holy Prophet and the Muslims in order to destroy the bulwark of morale that was helping them to defeat their enemies. Therefore the strategy was to attain the assistance of the hypocrites to spread slanders against the Holy Prophet and his followers so that the <em>mushriks</em> and the Jews could exploit these to sow the seeds of discord among the Muslims and undermine their discipline.</p>
<p>The first opportunity for the use of the new strategy was afforded in Zil-Qa'dah 5 A. H. when the Holy Prophet married Hadrat Zainab (daughter of Jahsh), who was the divorced wife of his adopted son, Zaid bin Harithah. The Holy Prophet had arranged this marriage in order to put an end to the custom of ignorance, which gave the same status to the adopted son that was the right only of the son from one's own loins. The hypocrites, however, considered it a golden opportunity to vilify the Holy Prophet from inside the community, and the Jews and the <em>mushriks</em> exploited it from outside to ruin his high reputation by this malicious slander. For this purpose fantastic stories were concocted and spread to this effect: "One day Muhammad (Allah's peace be upon him) happened to see the wife of his adopted son and fell in love with her; he maneuvered her divorce and married her." Though this was an absurd fiction it was spread with such skill, cunning and artfulness that it succeeded
in its purpose; so much so that some Muslim traditionalists and commentators also have cited some parts of it in their writings, and the orientalists have exploited these fully to vilify the Holy Prophet. As a matter of fact, Hadrat Zainab was never a stranger to the Holy Prophet that he should see her by chance and fall in love with her at first sight. For she was his first cousin, being the daughter of his real paternal aunt, Umaimah, daughter of Abdul Muttalib. He had known her from her childhood to her youth. A year before this incident, he himself had persuaded her to marry Hadarat Zaid in order to demonstrate practically that the Quraish and the liberated slaves were equal as human being. As she never reconciled herself to her marriage with a liberated slave, they could not pull on together for long, which inevitably led to her divorce. The above mentioned facts were well known to all, yet the slanderers succeeded in their false propaganda with the result that even today
there are people who exploit these things to defame Islam.</p>
<p>The second slander was made on the honor of Hadrat Ayesha, a wife of the Holy Prophet, in connection with an incident which occurred while he was returning from the Campaign against Bani al-Mustaliq. As this attack was even severer than the first one and was the main background of this Surah, we shall deal with it in greater detail.</p>
<p>Let us say a few words about Abdullah bin Ubayy, who played the part of a villain in this attack. He belonged to the clan of Khazraj and was one of the most important chiefs of Al-Madinah. The people had even intended to make him their king a little before the Holy Prophet's migration there, but the scheme had to be dropped because of the changed circumstances. Though he had embraced Islam, he remained at heart a hypocrite and his hypocrisy was so manifest that he was called the "Chief of the Hypocrites". He never lost any opportunity to slander Islam in order to take his revenge.</p>
<p>Now the main theme. When in Sha'ban 6 A. H. the Holy Prophet learned that the people of Bani al-Mustaliq were making preparations for a war against the Muslims and were trying to muster other clans also for this purpose, he fore- stalled and took the enemy by surprise. After capturing the people of the clan and their belongings, the Holy Prophet made a halt near Muraisi, a spring in their territory. One day a dispute concerning taking water from the spring started between a servant of Hadrat Umar and an ally of the clan of Khazraj, and developed into a quarrel between the Muhajirs(immigrants) and the Ansar(Muslims of Madinah), but was soon settled. This, however, did not suit the strategy of Abdullah bin Ubayy, who also had joined the expedition with a large number of hypocrites. So he began to incite the Ansar, saying, "You yourselves brought these people of the quraish from Makkah and made them partners in your wealth and property. And now they have become your rivals and want
domination over you. If even now you withdraw your support from them, they shall be forced to leave your city." Then he swore and declared, "As soon as we reach back Al-Madinah, the respectable people will turn out the degraded people from the city."</p>
<p>When the Holy Prophet came to know of this, he ordered the people to set off immediately and march back to Al-Madinah. The forced march continued up to noon the next day without a halt on the way so that the people became exhausted and had no time for idle talk.</p>
<p>Though this wise judgment and quick action by the Holy Prophet averted the undesirable consequences of the mischief, Abdullah bin Ubayy got another opportunity for doing a far more serious and greater mischief, i. e. by engineering a "Slander" against Hadrat Ayesha, for that was a mischief which might well have involved the young Muslim Community in a civil war, if the Holy Prophet and his sincere and devoted followers had not shown wisdom, forbearance and marvelous discipline in dealing with it. In order to understand the events that led to the incident of the "Slander", we cite the story in Hadrat 'Ayesha's own words. She says :</p>
<p>"Whenever the Holy Prophet went out on a journey, he decided by lots as to which of his wives should accompany him. Accordingly, it was decided that I should accompany him during the expedition to Bani al Mustaliq. On the return journey, the Holy Prophet halted for the night at a place which was the last stage on the way back to Al- Madinah. It was still night, when they began to make preparations for the march. So I went outside the camp to ease myself. When I returned and came near my halting place, I noticed that my necklace had fallen down somewhere. I went back in search for it but in the meantime the caravan moved off and I was left behind all alone. The four carriers of the litter had placed it on my camel without noticing that it was empty. This happened because of my light weight due to lack of food in those days. I wrapped myself in my sheet and lay down in the hope that when it would be found that I had been left behind, a search party would come back to pick me up.
In the meantime I fell asleep. In the morning, when Safwan bin Mu'attal Sulami passed that way, he saw me and recognized me for he had seen me several times before the Commandment about purdah had been sent down. No sooner did he see me than he stopped his camel and cried out spontaneously : "How sad! The wife of the Holy Prophet has been left here!" At this I woke up all of a sudden and covered my face with my sheet. Without uttering another word, he made his camel kneel by me and stood aside, while I climbed on to the camel back. He led the camel by the nose-string and we overtook the caravan at about noon, when it had just halted and nobody had yet noticed that I had been left behind. I learnt afterwards that this incident had been used to slander me and Abdullah bin Ubayy was foremost among the slanderers.(According to other traditions, when Hadrat Ayesha reached the camp on the camel, led by Safwan, and it was known that she had been left behind, Abdullah bin Ubayy cried out,
'By God, she could not have remained chaste. Look, there comes the wife of your Prophet openly on the camel led by the person with whom she passed the night.')</p>
<p>"When I reached Al-Madinah, I fell ill and stayed in bed for more than a month. Though I was quite unaware of it, the news of the "Slander" was spreading like a scandal in the city, and had also reached the Holy Prophet. Anyhow, I noticed that he did not seem as concerned about my illness he used to be. He would come but without addressing me directly, would inquire from others how I was and leave the house. Therefore it troubled my mind that something had gone wrong somewhere. So I took leave of him and went to my mother's house for better nursing.</p>
<p>"While I was there, one night I went out of the city to ease myself in the company of Mistah's mother, who was a first cousin of my mother. As she was walking along she stumbled over something and cried out spontaneously, 'May Mistah perish!' To this I retorted, 'What a good mother you are that you curse your own son -- the son who took part in the Battle of Badr.' She replied, 'My dear daughter, are you not aware of his scandal mongering?' Then she told me everything about the campaign of the "Slander".(Besides the hypocrites, some true Muslims also had been involved in this campaign, and among them who took leading part in it, were Mistah, Hassan bin Thabit, the famous poet of Islam, and Hamnah, daughter of Jahsh and sister of Hadrat Zainab). Hearing this horrible story, my blood curdled, and I immediately returned home, and passed the rest of the night in crying over it.</p>
<p>"During my absence the Holy Prophet took counsel with Ali and Usamah bin Zaid about this matter. Usamah said good words about me to this effect:'O Messenger of Allah, we have found nothing but good in your wife. All that is being spread about her is a lie and calumny.' As regards Ali, he said, 'O Messenger of Allah, there is no dearth of women; you may, if you like, marry an other wife. If, how- ever, you would like to investigate into the matter, you may send for her maid servant and inquire into it through her.' Accordingly, the maid servant was sent for and questioned. She replied, 'I declare on an oath by Allah, Who has sent you with the Truth, that I have never seen any evil thing in her, except that she falls asleep when I tell her to look after the kneaded dough in my absence and a goat comes and eats it.'</p>
<p>"On that same day the Holy Prophet addressed the people from the pulpit, saying:'O Muslims, who from among you will defend my honor against the attacker of the person who has transgressed all bounds in doing harm to me by slandering my wife. By God, I have made a thorough inquiry and found nothing wrong with her nor with the man, whose name has been linked with the "Slander". At this Usaid bin Hudair (or Sa'd bin Mauz) according to other traditions) stood up and said, 'O Messenger of Allah, if that person belongs to our clan, we will kill him by ourselves, but if he belongs to the Khazraj clan, we will kill him if you order us to do so.' Hearing this Sa'd bin 'Ubadah, chief of the Khazraj clan, stood up and said, 'You lie you can never kill him. You are saying this just because the person belongs to our clan of Khazraj. Had he belonged to your clan, you would never have said so.' Hadrat Usaid retorted, 'You are a hypocrite: that is why you are defending a hypocrite.' At this,
there was a general turmoil in the mosque, which would have developed into a riot, even though the Holy Prophet was present there the whole time. But he cooled down their anger and came down from the pulpit."</p>
<p>The remaining details of the incident will be cited along with our commentary on the Text, which honorably absolved Hadrat Aishah from the blame. But here we would only want to point out the enormity of the mischief that was engineered by Abdullah bin Ubayy: (1) It implied an attack on the honor of the Holy Prophet and Hadrat Abu Bakr Siddiq.(2) He meant to undermine the high moral superiority which was the greatest asset of the Islamic Movement (3) He intended to ignite civil war between the Muhajirs and the Ansar, and between Aus and Khazraj, the two clans of the Ansar.</p>
<h2>Theme and Topics</h2>
<p>This Surah and vv. 28-73 of Surah Al-Ahzab(of which this is the sequel) were sent down to strengthen the moral front, which at that time was the main target of the attack, vv. 28-73 of Al-Ahzab were sent down concerning the Holy Prophet's marriage with Hadrat Zainab, and on the occasion of the second attack (the "Slander" about Hadrat Aishah), Surah An-Nur was sent down to repair the cracks that had appeared in the unity of the Muslim Community. If we keep this in view during the study of the two Surahs, we shall understand the wisdom that underlies the Commandments about purdah. Allah sent the following instructions to strengthen and safeguard the moral front, and to counteract the storm of propaganda that was raised on the occasion of the marriage of Hazrat Zainab:</p>
<ol>
  <li>
    <p>The wives of the Holy Prophet were enjoined to remain within their private quarters, to avoid display of adornments and to be cautious in their talk with other persons (vv. 32, 33).</p>
  </li>
  <li>
    <p>The other Muslims were forbidden to enter the private rooms of the Holy Prophet and instructed to ask whatever they wanted from behind the curtain.(v. 53).</p>
  </li>
  <li>
    <p>A line of demarcation was drawn between the <em>mahram</em> and the non-<em>mahram</em> relatives. Only the former were allowed to enter the private rooms of those wives of the Holy Prophet with whom they were so closely related as to prohibit marriage with them.(v. 55).</p>
  </li>
  <li>
    <p>The Muslims were told that the wives of the Prophet were prohibited for them just like their own real mothers; therefore every Muslim should regard them with the purest of intentions.(vv. 53, 54).</p>
  </li>
  <li>
    <p>The Muslims were warned that they would invite the curse and scourge of Allah if they offended the Holy Prophet. Likewise it was a heinous sin to attack the honor of or slander any Muslim man or woman.(vv. 57, 58).</p>
  </li>
  <li>
    <p>All the Muslim women were enjoined to cover their faces with their sheets if and when they had to go out of their houses.(v. 59).</p>
  </li>
</ol>
<p>On the occasion of the second attack, this Surah was sent down to keep pure and strengthen the moral fiber of the Muslim society, which had been shaken by the enormity of the slander. We give below a summary of the Commandments and instructions in their chronological order so that one may understand how the Qur'an makes use of the psychological occasion to reform the Community by the adoption of legal, moral and social measures.</p>
<ol>
  <li>
    <p>Fornication which had already been declared to be a social crime (IV: 15,16) was now made a criminal offense and was to be punished with a hundred lashes.</p>
  </li>
  <li>
    <p>It was enjoined to boycott the adulterous men and women and the Muslims were forbidden to have any marriage relations with them.</p>
  </li>
  <li>
    <p>The one, who accused the other of adultery but failed to produce four witnesses, was to be punished with eighty lashes.</p>
  </li>
  <li>
    <p>The Law of <em>Li'an</em> was prescribed to decide the charge of adultery against his own fife by a husband.</p>
  </li>
  <li>
    <p>The Muslims were enjoined to learn a lesson from the incident of the "Slander" about Hadrat Aishah, as if to say, "You should be very cautious in regard to charges of adultery against the people of good reputation, and should not spread these; nay, you should refute and suppress them immediately." In this connection, a general principle was enunciated that the proper spouse for a pure man is a pure woman, for he cannot pull on with a wicked woman for long, and the same is the case with a pure woman, as if to say, "When you knew that the Holy Prophet was a pure man, nay, the purest of all human beings, how could you believe that he had experienced happiness with a wicked woman and exalted her as the most beloved of his wives? For it was obvious that an adulterous woman could not have been able to deceive, with her affected behavior, a pure man like the Holy Prophet. You ought also to have considered the fact that the accuser was a mean person while the accused was a pure
    woman. This should have been enough to convince you that the accusation was not worth your consideration; nay, it was not even conceivable.</p>
  </li>
  <li>
    <p>Those who spread news and evil rumors and propagate wickedness in the Muslim Community, deserve punishment and not encouragement.</p>
  </li>
  <li>
    <p>A general principle was laid down that relations in the Muslim Community should be based on good faith and not on suspicion: everyone should be treated as innocent unless he is proved to be guilty and <em>vice versa</em>.</p>
  </li>
  <li>
    <p>The people were forbidden to enter the houses of others unceremoniously and were instructed to take permission for this.</p>
  </li>
  <li>
    <p>Both men and women were instructed to lower their gaze and forbidden to cast glances or make eyes at each other.</p>
  </li>
  <li>
    <p>Women were enjoined to cover their heads and breasts even inside their houses.</p>
  </li>
  <li>
    <p>Women were forbidden to appear with make-up before other men except their servants or such relatives with whom their marriage is prohibited.</p>
  </li>
  <li>
    <p>They were enjoined to hide their make-ups when they went out of their houses, and even forbidden to put on jingling ornaments, while they moved out of their houses.</p>
  </li>
  <li>
    <p>Marriage was encouraged and enjoined even for slaves and slave girls, for unmarried people help spread indecency.</p>
  </li>
  <li>
    <p>The institution of slavery was discouraged and the owners and other people were enjoined to give financial help to the slaves to earn their freedom under the law of <em>Mukatabat</em>.</p>
  </li>
  <li>
    <p>Prostitution by slave girls was forbidden in the first instance, for prostitution in Arabia was confined to this class alone. This in fact implied the legal prohibition of prostitution.</p>
  </li>
  <li>
    <p>Sanctity of privacy in home life was enjoined even for servants and under age children including one's own. They were enjoined not to enter the private rooms of any man or woman without permission; especially in the morning, at noon and at night.</p>
  </li>
  <li>
    <p>Old women were given the concession that they could set aside their head covers within their houses but should refrain from display of adornments. Even they were told that it was better for them to keep themselves covered with head wrappers.</p>
  </li>
  <li>
    <p>The blind, lame, crippled and sick persons were allowed to take any article of food from the houses of other people without permission, for it was not to be treated like theft and cheating, which are cognizable offenses.</p>
  </li>
  <li>
    <p>On the other hand, the Muslims were encouraged to develop mutual relationships by taking their meals together, and the nearest relatives and intimate friends were allowed to take their meals in each other's house without any formal invitation. This was to produce mutual affection and sincere relationships between them to counteract any future mischief. Side by side with these instructions, clear signs of the Believers and the hypocrites were stated to enable every Muslim to discriminate between the two. At the same time the Community was bound together by adopting disciplinary measures in order to make it stronger and firmer than it was at the time so as to discourage the enemies from creating mischief in it.</p>
  </li>
</ol>
<p>Above all, the most conspicuous thing about this discourse is that it is free from the bitterness which inevitably follows such shameful and absurd attacks. Instead of showing any wrath at this provocation, the discourse prescribes some laws and regulations and enjoins reformative commandments and issues wise instructions that were required at the time for the education and training of the Community. Incidentally, this teaches us how to deal with such provocative mischiefs coolly, wisely and generously. At the same time, it is a clear proof that this is not the word of Prophet Muhammad (Allah's peace and blessings be upon him) but of a Being Who is observing all human conditions and affairs from the highest level, and guiding mankind without any personal prejudices, feelings and leanings. Had this been the word of the Holy Prophet; there would have been at least some tinge of natural bitterness in spite of his great generosity and forbearance, for it is but human that a noble
man naturally become enraged when his own honor is attacked in this mean manner.</p>
`
