export default `
 <h2>Name</h2>
<p>The Surah takes its name "Al-Furqan" from the first verse. Though it is symbolic like the names of many other Surahs, it has a close relation to its subject matter.</p>
<h2>Period of Revelation</h2>
<p>It appears from its style and subject matter that, like Surah Al- Mu'minun, it was also revealed during the third stage of Prophethood at Makkah. Ibn Jarir and Imam Razi have cited a tradition of Dahhak bin Muzahim that this Surah was revealed eight years before Surah An Nisa. This also confirms our opinion as to its period of revelation. (<em>Ibn Jarir</em>, Vol. XIX, pp. 28-30, and <em>Tafsir Kabir</em>, Vol. VI,p. 358).</p>
<h2>Subject Matter and Topics</h2>
<p>The Surah deals with the doubts and objections that were being raised against the Qur'an, the Prophethood of Muhammad (Allah's peace and blessings be upon him) and his teachings by the disbelievers of Makkah. Appropriate answers to each and every objection have been given and the people have been warned of the consequences of rejecting the Truth. At the end of the Surah, a clear picture of the moral superiority of the Believers has been depicted as in the beginning of Surah Al-Mu'minun, as if to say, 'Here is the criterion for distinguishing the genuine from the counterfeit. This is the noble character of those people who have believed in and followed the teachings of the Holy Prophet and this is the kind of people that he is trying to train. You may yourselves compare and contrast this type of people with those Arabs, who have not as yet accepted the Message, and who are upholding "ignorance" and exerting their utmost to defeat the Truth. Now you may judge for yourselves as to
which you would like to choose." Though this question was not posed in so many words, it was placed before every one in Arabia in a tangible shape. It may be noted that during the next few years, the practical answer given to this question by the whole nation, with the exception of a small minority, was that they chose Islam.</p>;
`
