export default `
 <h2>Name</h2>
<p>The Surah takes its name from verse 25 in which the word Al-Qasas occurs. Lexically, <em>qasas</em> means to relate events in their proper sequence. Thus, from the viewpoint of the meaning too, this word can be a suitable title for this Surah, for in it the detailed story of the Prophet Moses has been related.</p>
<h2>Period of Revelation</h2>
<p>As already mentioned in the introduction to Surah An Naml, according to Ibn Abbas and Jabir bin Zaid, Surahs Ash-Shu\`araa', An-Naml and Al- Qasas were sent down one after the other. The language, the style and the theme also show that the period of the revelation of these three Surahs is nearly the same. Another reason for their lose resemblance is that the different parts of the Prophet Moses story as mentioned in these surahs together make up a complete story. In Surah Ash Shu\`araa', excusing himself for not accepting the office of Prophethood the Prophet Moses submits, "The people of Pharaoh have the charge of a crime against me; therefore, I fear that they will put me to death." Then, when lie goes before Pharaoh, the latter says, "Did we not bring you up as a child in our house? You lived quite a few years of your life among us, and then you did what you did." Nothing more of this has been mentioned there, but in this Surah the other details have been supplied. Similarly,
in Surah An-Naml the story starts abruptly from the time when the Prophet Moses was journeying with his family and suddenly saw a fire at a distance. In that Surah nothing has been said about the nature of his journey, or the place he was coming from, or his destination, but this Surah supplies all the necessary details. Thus, the three Surahs read together complete the story of the Prophet Moses (Allah's peace be upon him).</p>
<h2>Theme and Topics</h2>
<p>The main theme is to remove the doubts and objections that were being raised against the Prophethood of the Holy Prophet Muhammad (upon whom be Allah's peace and blessings) and to invalidate the excuses which were being offered for not believing in him.</p>
<p>For this purpose, first the story of the Prophet Moses has been related, which, by analogy with the period of revelation, impresses the following points in the listeners mind automatically:</p>
<p>First, Allah provides the means and motives of whatever He wills to do, in imperceptible ways. Thus, Allah so arranged things that the child through whom Pharaoh had to be removed from power, was bred and brought up in his own house, and he could not know whom he was fostering. Who can then fight God and frustrate Him by his machinations.</p>
<p>Secondly, Prophethood is not granted to a person amid festivities by issuing a proclamation from the earth and heavens. You wonder how Muhammad (upon whom be Allah's peace) has been blessed with Prophethood unexpectedly, all of a sudden, but Moses whom you yourselves acknowledge as a Prophet (v. 48) had also become a Prophet unexpectedly, while on a journey, and nobody had known what event had occurred in the desolation at the foot of Mt. Sinai. Even Moses himself did not know a moment before what he was going to be blessed with. He, in fact, had gone to bring a piece of the fire but had returned with the gift of Prophethood.</p>
<p>Thirdly, the person from whom Allah wants to take some service comes out without any army and armor and without an apparent helper or force at his back, yet he puts to rout much stronger and better equipped opponents. The contrast that existed between the strengths of Moses (peace be upon him) and Pharaoh was much more prominent and glaring than that which existed between Muhammad (peace be upon him) and the quraish; yet the world knows who had come out victorious in the end and who had been routed.</p>
<p>Fourthly, you refer to Moses again and again and say, "Why has Muhammad not been given the same which was given to Moses? i. e. miracles of the staff, the shining hand, etc. as if to suggest that you would readily believe only if you were shown the kind of the miracles that were shown by Moses to Pharaoh. But do you know what sort of response was made by those who were shown those miracles? They had not believed even after seeing the miracles, and had only said, "This is magic", for they were involved in stubbornness and hostility to the Truth. The same malady afflicts you today. Will you believe only when you are slowly the same kind of miracles?Then, do you know what fate the disbelievers had met even after seeing the miracles? They were annihilated by Allah. Do you now wish to meet the same doom by asking for the miracles in your obstinacy?</p>
<p>These were the things which were automatically impressed in the mind of every listener who heard this story in the pagan environment of Makkah, for a similar conflict was going on at that time between the Holy Prophet and disbelievers of Makkah as had already taken place between the Prophet Moses and Pharaoh before. This was the background against which the story of the Prophet Moses was narrated so that a perfect analogy was established automatically in every detail between the conditions prevailing then in Makkah and those existing in the time of the Prophet Moses. Then, from verse 43 onward the discourse turns to the real theme.</p>
<p>In the first place, the narration of a two thousand year old historical event by the Holy Prophet with such accuracy and detail, is presented as a proof of his Prophethood although he was un-lettered and the people of his city and clan knew full well that he had no access to any source of such information as they could point out.</p>
<p>Then the disbelievers of Makkah have been warned and put to shame for an event that occurred in those very days. Some Christians had come to Makkah and embraced Islam when they heard the Qur'an from the Holy Prophet. Instead of learning any lesson from this the Makkans were so upset at this that their leader, Abu Jahl, disgraced those people publicly.</p>
<p>In conclusion, the excuse that the disbelievers put forward for not believing in the Holy Prophet has been dealt with. What they feared was this:"If we give up the polytheistic creed of the Arabs and accept the doctrine of <em>Tauhid</em> instead, this will put an end to our supremacy in the religious, political and economic fields, which, in turn, will destroy our position of the most influential tribe of Arabia and we shall be left with no refuge anywhere in the land." As this was the real motive of the chiefs of the Quraish for their antagonism towards the Truth, and their doubts and objections were only the pretenses, which they invented to deceive the common people, Allah has dealt with these fully till the end of the Surah, considered each aspect of these in a wise manner and offered the remedy for their basic ailment due to which those people judged the Truth and falsehood only from the viewpoint of their worldly interests.</p>;
`
