export default `
 <h2>Name</h2>
<p>The Surah takes its name from verse 41 in which the word <em>Ankabut</em> (Spider) has occurred.</p>
<h2>Period of Revelation</h2>
<p>Verses 56 to 60 clearly show that this Surah was sent down a little before the migration to Habash, and this is supported by the internal evidence of the subject matter as well. Some commentators have opined that since it mentions the hypocrites, and hypocrisy appeared in Madinah, the first ten verses of this Surah were revealed at Madinah and the rest of it at Makkah; whereas the people whose hypocrisy has been mentioned here are those who had adopted a hypocritical way of life because they were afraid of the oppression and extreme physical torture to which the Muslims were being subjected by the disbelievers. Evidently, this kind of hypocrisy could be there only at Makkah and not at Madinah. Similarly, some other commentators, seeing that in this Surah the Muslims have been exhorted to migrate, have regarded it as the last Surah to be revealed at Makkah, whereas the Muslims had migrated to Habash even before their migration to Madinah. These opinions are not based on any
tradition but on the internal evidence of the subject matter, and this internal evidence, when considered against the subject matter of the Surah as a whole, points to the conditions prevailing in the time of the migration to Habash and not to the last stage at Makkah.</p>
<h2>Theme and Subject matter</h2>
<p>A perusal of the Surah shows that the period of its revelation was the period of extreme persecution of the Muslims at Makkah. The disbelievers were opposing and fighting Islam tooth and nail and the new converts were being subjected to the severest oppression. Such were the conditions when Allah sent down this Surah to strengthen and encourage the sincere Muslims as well as to put to shame those who were showing weakness of the faith. Besides, the disbelievers of Makkah have been threatened and warned not to invite for themselves the fate that the antagonists of the Truth have been experiencing in every age.</p>
<p>In this connection, the questions that some young men answered. For instance, their parents were urging them to abandon Muhammad (may Allah's peace be upon him), and return to their ancestral religion, for they argued: "The Qur'an in which you have put your faith, regards the rights of the parents as the uppermost; therefore, listen to what we say; otherwise you will be working against the dictates of your own Faith." This has been answered in verse 8.</p>
<p>Similarly, the people of some clans said to the new converts to Islam, "Leave the question of punishments, etc., to us. Listen to us and abandon this man. If God seizes you in the Hereafter, we will come forward and say, 'Lord, these people are innocent: we had forced them to give up the Faith; therefore, seize us'." This has been dealt with, in vv. 12-13.</p>
<p>The stories mentioned in this Surah also impress the same point mostly, as if to say, "Look at the Prophets of the past: they were made to suffer great hardships and were treated cruelly for long periods. Then, at last they were helped by Allah. Therefore, take heart: Allah's succor will certainly come. But a period of trial and tribulation has to be undergone." Besides teaching this lesson to the Muslims, the disbelievers also have been warned, as if to say, "If you are not being immediately seized by Allah, you should not form the wrong impression that you will never be seized. The signs of the doomed nations of the past are before you. Just see how they met their doom and how Allah succored the Prophets."</p>
<p>Then the Muslims have been instructed to the effect: "If you feel that the persecution has become unbearable for you, you should give up your homes, instead of giving up your Faith: Allah's earth is vast: seek a new place where you can worship Allah with the full peace of mind." Besides all this, the disbelievers also have been urged to understand Islam. The realities of <em>Tauhid</em> and the Hereafter have been impressed with rational arguments, <em>shirk</em> have been refuted, and drawing their attention towards the signs in the universe, they have been told that all these Signs confirm the teachings that the Prophet is presenting before them.</p>
`
