export default `
 <h2>Name</h2>
<p>The Surah takes its name Ar-Rum from the second verse in which the words <em>ghulibat-ir-Rum</em> have occurred.</p>
<h2>Period of Revelation</h2>
<p>The period of the revelation of this Surah is determined absolutely by the historical event that has been mentioned at the outset. It says: "The Romans have been vanquished in the neighboring land."In those days the Byzantine occupied territories adjacent to Arabia were Jordan, Syria and Palestine, and in these territories the Romans were completely overpowered by the Iranians in 615 A. D. Therefore, it can be said with absolute certainty that this Surah was sent down in the same year, and this was the year in which the migration to Habash took place.</p>
<h2>Historical Background</h2>
<p>The prediction made in the initial verses of this Surah is one of the most outstanding evidences of the Quran's being the Word of Allah and the Holy Prophet Muhammad's being a true Messenger of Allah. Let us have a look at the historical background relevant to the verses.</p>
<p>Eight years before the Holy Prophet's advent as a Prophet the Byzantine Emperor Maurice was overthrown by Phocus, who captured the throne and became king. Phocus first got the Emperor's five sons executed in front of him, and then got the Emperor also killed and hung their heads in a thoroughfare in Constantinople. A few days after this he had the empress and her three daughters also put to death. The event provided Khusrau Parvez, the Sassanid king of Iran; a good moral excuse to attack Byzantium. For Emperor Maurice had been his benefactor; with his help he had got the throne of Iran. Therefore, he declared that he would avenge his godfather's and his children's murder upon Phocus, the usurper. So, he started war against Byzantium in 603 A. D. and within a few years, putting the Phocus armies to rout in succession, he reached Edessa (modern, Urfa) in Asia Minor, on the one hand, and Aleppo and Antioch in Syria, on the other. When the Byzantine ministers saw that Phocus could
not save the country, they sought the African governor's help, who sent his son, Heraclius, to Constantinople with a strong fleet. Phocus was immediately deposed and Heraclius made emperor. He treated Phocus as he had treated Maurice. This happened in 610 A. D., the year the Holy Prophet was appointed to Prophethood.</p>
<p>The moral excuse for which Khusrau Parvez had started the war was no more valid after the deposition and death of Phocus. Had the object of his war really been to avenge the murder of his ally on Phocus for his cruelty, he would have come to terms with the new Emperor after the death of Phocus. But he continued the war, and gave it the color of a crusade between Zoroastrianism and Christianity. The sympathies of the Christian sects (i. e. Nestorians and Jacobians, etc.) which had been excommunicated by the Roman ecclesiastical authority and tyrannized for years also went with the Magian (Zoroastrian) invaders, and the Jews also joined hands with them; so much so that the number of the Jews who enlisted in Khusrau's army rose up to 26,000.</p>
<p>Heraclius could not stop this storm. The very first news that he received from the East after ascending the throne was that of the Iranian occupation of Antioch. After this Damascus fell in 613 A. D. Then in 614 A.D. the Iranians occupying Jerusalem played havoc with the Christian world. Ninety thousand Christians were massacred and the Holy Sepulcher was desecrated. The Original Cross on which, according to the Christian belief, Jesus had died was seized and carried to Mada'in. The chief priest Zacharia was taken prisoner and all the important churches of the city were destroyed. How puffed up was Khusrau Parvez at this victory can be judged from the letter that he wrote to Heraclius from Jerusalem. He wrote: "From Khusrau, the greatest of all gods, the master of the whole world: To Heraclius, his most wretched and most stupid servant: You say that you have trust in your Lord. why didn't then your Lord save Jerusalem from me?"</p>
<p>Within a year after this victory the Iranian armies over-ran Jordan, Palestine and the whole of the Sinai Peninsula, and reached the frontiers of Egypt. In those very days another conflict of a far greater historical consequence was going on in Makkah. The believers in One God, under the leadership of the Prophet Muhammad (may Allah's peace be upon him), were fighting for their existence against the followers of <em>shirk</em> under the command of the chiefs of the Quraish, and the conflict had reached such a stage that in 615 A. D., a substantial number of the Muslims had to leave their homes and take refuge with the Christian kingdom of Habash, which was an ally of the Byzantine Empire. In those days the Sassanid victories against Byzantium were the talk of the town, and the pagans of Makkah were delighted and were taunting the Muslims to the effect: "Look the fire worshipers of Iran are winning victories and the Christian believers in Revelation and Prophethood are being
routed everywhere. Likewise, we, the idol worshipers of Arabia, will exterminate you and your religion."</p>
<p>These were the conditions when this Surah of the Quran was sent down, and in it a prediction was made, saying:"The Romans have been vanquished in the neighboring land and within a few years after their defeat, they shall be victorious. And it will be the day when the believers will rejoice in the victory granted by Allah." It contained not one but two predictions: First, the Romans shall be victorious; and second, the Muslims also shall win a victory at the same time. Apparently, there was not a remote chance of the fulfillment of the either prediction in the next few years. On the one hand, there were a handful of the Muslims, who were being beaten and tortured in Makkah, and even till eight years after this prediction there appeared no chance of their victory and domination. On the other, the Romans were losing more and more ground every next day. By 619 A. D. the whole of Egypt had passed into Sassanid hands and the Magian armies had reached as far as Tripoli. In Asia Minor
they beat and pushed back the Romans to Bosporus, and in 617 A. D. they captured Chalcedon (modern, Kadikoy) just opposite Constantinople. The Emperor sent an envoy to Khusrau, praying that he was ready to have peace on any terms, but he replied, "I shall not give protection to the emperor until he is brought in chains before me and gives up obedience to his crucified god and adopts submission to the fire god." At last, the Emperor became so depressed by defeat that he decided to leave Constantinople and shift to Carthage (modern, Tunis). In short, as the British historian Gibbon says, even seven to eight years after this prediction of the Quran, the conditions were such that no one could even imagine that the Byzantine Empire would ever gain an upper hand over Iran. Not to speak of gaining domination, no one could hope that the Empire, under the circumstances, would even survive.</p>
<p><em>bid\`i sinin</em>, and the word <em>bid\`</em> in Arabic applies to a number upto ten. Therefore, make the bet for ten years and increase the number of camels to a hundred." So, Hadrat Abu Bakr spoke to Ubayy again and bet a hundred camels for ten years.</p>
<p>In 622 A. D. as the Holy Prophet migrated to Madinah, the Emperor Heraclius set off quietly for Trabzon from Constantinople via the Black Sea and started preparations to attack Iran from rear. For this he asked the Church for money, and Pope Sergius lent him the Church collections on interest, in a bid to save Christianity from Zoroastrianism. Heraclius started his counter attack in 623 A. D. from Armenia. Next year, in 624 A. D., he entered Azerbaijan and destroyed Clorumia, the birthplace of Zoroaster, and ravaged the principal fire temple of Iran. Great are the powers of Allah, this was the very year when the Muslims achieved a decisive victory at Badr for the first time against the <em>mushriks</em>. Thus both the predictions made in Surah Rum were fulfilled simultaneously within the stipulated period of ten years.</p>
<p>The Byzantine forces continued to press the Iranians hard and in the decisive battle at Nineveh (627 A.D.) they dealt them the hardest blow. They captured the royal residence of Dastagerd, and then pressing forward reached right opposite to Ctesiphon, capital of Iran in those days. In 628 A. D. in an internal revolt, Khusrau Parvez was imprisoned and 18 of his sons were executed in front of him and a few days later he himself died in the prison. This was the year when the peace treaty of Hudaibiya was concluded, which the Quran has termed as "the supreme victory", and in this very year Khusrau's son, Qubad II, gave up all the occupied Roman territories, restored the True Cross and made peace with Byzantium. In 628 A. D., the Emperor himself went to Jerusalem to install the "Holy Cross" in its place, and in the same year the Holy Prophet entered Makkah for the first time after the Hijrah to perform the <em>\`Umra-tul-Qada'</em>.</p>
<p>After this no one could have any doubt about the truth of the prophecy of the Quran, with the result that most of the Arab polytheists accepted Islam. The heirs of Ubayy bin Khalaf lost their bet and had to give a hundred camels to Hadrat Abu Bakr Siddiq. He took them before the Holy Prophet, who ordered that they be given away in charity, because the bet had been made at a time when gambling had not yet been forbidden by the <em>Shari\`ah</em> ; now it was forbidden. Therefore, the bet was allowed to be accepted from the belligerent disbelievers, but instruction given that it should be given away in charity and should not be brought in personal use.</p>
<h2>Theme and Subject matter</h2>
<p>The discourse begins with the theme that the Romans have been overcome and the people the world over think that the empire is about to collapse, but the fact is that within a few years the tables will be turned and the vanquished will again become victorious.</p>
<p>This introductory theme contains the great truth that man is accustomed to seeing only what is apparent and superficial. That which is behind the apparent and superficial he does not know. When in the petty matters of life, this habit to see only the apparent and superficial can lead man to misunderstandings and miscalculations, and when he is liable to make wrong estimates only due to lack of knowledge about "what will happen tomorrow", how stupendous will be his error if he risks his whole life-activity by placing reliance only upon what is visible and apparent with respect to his worldly life as a whole.</p>
<p>In this connection, the Signs of the universe which have been presented as evidence to prove the doctrine of the Hereafter arc precisely the same which support the doctrine of <em>Tauhid</em>. Therefore from verse 28 onward, the discourse turns to the affirmation of <em>Tauhid</em> and the refutation of <em>shirk</em>, and it is stressed that the natural way of life for man is none else but to serve One God exclusively. <em>Shirk</em> is opposed to the nature of the universe as to the nature of man. Therefore, whenever man has adopted this deviation, chaos has resulted. Again here, an allusion has been made to the great chaos that had gripped the world on account of the war between the two major powers of the time, and it has been indicated that this chaos too, is the result of <em>shirk</em>, and all the nations who were ever involved in mischief and chaos in the history of mankind were also <em>mushriks</em>.</p>
<p>In conclusion, a parable has been presented to make the people understand that just as dead earth comes to life, all of a sudden, by a shower of rain sent by God and swells with vegetation and plant life, so is the case with the dead humanity. When God sends a shower of His mercy in the form of Revelation and Prophethood, it also gives a new life to mankind and causes it to grow and develop and flourish. Therefore: "If you take full advantage of this opportunity, the barren land of Arabia will bloom by Allah's mercy and the whole advantage will be your. But if you do not take advantage of it, you will harm only your selves. Then no regret will avail and no opportunity will be provided to make amends."</p>
`
