export default `
 <h2>Name</h2>
<p>The Surah has been named Luqman after Luqman the Sage, whose admonitions to his son have been related in vv. 12-19 of this Surah.</p>
<h2>Period of Revelation</h2>
<p>A perusal of the subject matter shows that it was sent down in the period when persecution to suppress and thwart the invitation to Islam had begun and every sort of machination had started being employed for the purpose. This is borne out by vv. 14-15, in which the young converts to Islam have been told that although the rights of the parents are the uppermost after God, they should not listen to them if they prevented them from accepting Islam, or compelled them to revert to the creed of shirk and polytheism. The same thing has been said in Surah Al-Ankabut, which indicates that both these Surahs were sent down in the same period. A study of the style and subject matter of the two Surahs on the whole, however, shows that Surah Luqman was sent down earlier, for one does not see any sign of the antagonism in its background though, contrary to this, while studying Surah Al-Ankabut one can clearly feel that the Muslims were being severely persecuted during the period of its
revelation.</p>
<h2>Theme and Subject matter</h2>
<p>In this Surah the people have been made to understand the meaninglessness and absurdity of <em>shirk</em> and the truth and reasonableness of <em>Tauhid</em>, and they have been invited to give up blind imitation of their forefathers, consider with a cool mind the teachings which the Prophet Muhammad (upon whom be Allah's peace and blessings) is presenting from the Lord of the worlds, and see with open eyes the manifest Signs found in the universe around them and in their own selves, which bear evidence to its truth.</p>
<p>In this connection, it has also been pointed out that this is not a new teaching which might have been, presented in the world, or in the land of Arabia, for the first time, and with which the people might be unfamiliar. The learned and wise people of the past ages said and taught the same thing which Muhammad (upon whom be Allah's peace) is teaching today. It is as if to say, "O people! In your own country there has lived a wise man, named Luqman, whose wisdom has been well known among you, whose proverbs and wise sayings are cited in your daily conversation and who is often quoted by your poets and orators. Now you should see for yourselves what creed and what morals he used to teach."</p>
`
