export default `
 <h2>Name</h2>
<p>The Surah derives its name <em>Al-Ahzab</em> from verse 20.</p>
<h2>Period of Revelation</h2>
<p>The Surah discusses three important events which are: the Battle of the Trench (or <em>Al-Ahzab</em> : the Clans), which took place in Shawwal, A. H. 5; the raid on Bani Quraizah, which was made in Dhil-Qa'dah, A. H. 5; and the Holy Prophet's marriage with Hadrat Zainab, which also was contracted in Dhil-Qa'dah, A. H. 5. These historical events accurately determine the period of the revelation of this Surah.</p>
<h2>Historical Background</h2>
<p>The Islamic army's setback in the Battle of Uhud (A. H. 3) that resulted from the error of the archers appointed by the Holy Prophet so boosted up the morale of the Arab pagans and the Jews and the hypocrites that they started entertaining the hope that they would soon be able to exterminate Islam and the Muslims completely. Their high state of morale can be judged from the events that occurred in the first year after Uhud. Hardly two months had passed then the tribe of Bani Asad of Najd began to make preparations for a raid on Madinah, and the Holy Prophet had to dispatch an expedition under Abu Salamah to counteract them. In Safar A. H. 4 some people of the tribes of Adal and Qarah asked the Holy Prophet to send some men to instruct them in Islam. Accordingly six of the Companions were allowed to accompany them for the purpose. But when they reached Raji (a place between Rabigh and Jeddah), they summoned Hudhail against them, who killed four of the Companions, and took the
other two (Hadrat Khubaib bin Adi and Hadrat Zaid bin ad-Dathinnah) to Makkah and sold them to the enemy. Then in the same month of Safar, on the request of a chief of Bani Amir, the Holy Prophet sent another deputation of 40 (according to others, 70) preachers, consisting of the Ansar young men, to Najd. But they were also betrayed. The people of Usayyah and Ri'l and Dhakwan, tribes of Bani Sulaim, surrounded them suddenly at Bir Maunah and slew all of them. Meanwhile the Jewish tribe of Bani an-Nadir of Madinah, getting encouragement, continued to commit breaches of the treaties; so much so that in Rabi'ul Awwal, A.H. 4, they plotted against the life of the Holy Prophet himself. Then in Jamadi al-Ula, A. H. 4, Bani Thalbah and Bani Muharib, the two tribes of Bani Ghatafan, started making preparations to attack Madinah and the Holy Prophet had to go to punish them. Thus, after their setback at Uhud, the Muslims went on encountering repercussions continuously for seven to eight
months.</p>
<p>However, it was the Holy Prophet's determination and wisdom and his great Companions' spirit of sacrifice that changed these adverse conditions completely within a short span of time. The economic boycott by the Arabs had made life hard for the people of Madinah. All the polytheistic tribes around Madinah were becoming rebellious. Inside Madinah itself the Jews and the hypocrites were beat upon mischief. But the successive steps taken by a handful of the sincere Muslims, under the leadership of the Holy Prophet, not only restored the image of strength of Islam in Arabia but also increased it manifold.</p>
<h2>Raids Preceding the Battle of the Trench</h2>
<p>The first such step was taken immediately after the Battle of Uhud. The very next day when quite a large number of Muslims lay wounded and the martyrdom of the near and dear ones was being mourned in many houses, and the Holy Prophet himself was injured and sad at the martyrdom of his uncle, Hadrat Hamzah, he called out to the devoted servants of Islam to accompany him in pursuit of the pagans so as to deter them from returning and attacking Madinah again. The Holy Prophet's assessment was absolutely correct. He knew that, although the Quraish had retreated without taking any advantage of their almost complete victory, they would certainly regret their folly when they would halt and consider the whole matter coolly on the way, and would return to attack Madinah again. Therefore, he decided to go in pursuit of them, and 630 of of the Muslims at once volunteered to accompany him. When they reached Hamra al-Asad on the way to Makkah and camped there for three days, the Holy Prophet
came to know through a sympathetic non- Muslim that Abu Sufyan had stayed at Ar-Rauha, 36 miles short of Madinah, with an army 2,978 strong: they were regretting their error and were, in fact, planning to return and attack Madinah once agaln. But when they heard that the Holy Prophet was coming in pursuit of them with an army, they lost heart and gave up their plan. Thus, not only were the Quraish deterred by this action but the other enemies living around Madinah also realized that the Muslims were being led by a person, who was highly well informed, wise and resolute, and that the Muslims were ever ready to lay down their lives at his command.(For further details, see Introduction to Surah Al-i-\`Imran and E.N. 122 thereof).</p>
<p>Then as soon as the Bani Asad started making Preparations for a raid on Madinah, the Holy Prophet's secret agents gave him timely information about their intention. Thus, before they could come in force to attack Madinah, he sent an army 150 strong, under Hadrat Abu Salamah (the first husband of Hadrat Umm Salamah) to punish them. They took Bani Asad by surprise, who fled in panic leaving all their possessions behind, which fell into the Muslim hands.</p>
<p>After this came the turn of the Bani an-Nadir. The day they plotted against the life of the Holy Prophet, and the secret was disclosed, the Holy Prophet ordered them to leave Madinah within ten days and warned that anyone who remained behind after that would be put to death. Abdullah bin Ubayy, the chief of the hypocrites of Madinah, encouraged them to defy the order and refuse to leave Madinah. He even promised to help them with 2,000 men, and assured them that the Bani Ghatafan from Najd also would come to their aid. Accordingly, the Bani an- Nadir sent word that they would not leave no matter what the Holy Prophet might do.</p>
<p>As soon as the time limit of ten days come to an end, the Holy Prophet laid siege to their quarters, but none of their supporters had the courage to come to their rescue. At last, they surrendered on condition that every three of them would be allowed to load a camel with whatever they could carry and go away leaving the rest of their possessions behind. Thus, the whole suburbs of the city which were inhabited by the Bani an-Nadir, and their gardens and their fortresses and other properties fell to the Muslims, and the people of this treacherous tribe became scattered in Khyber, Wad il Qura and Syria.</p>
<p>Then the Holy Prophet turned his attention to the Bani Ghatafan, who were preparing for a war against Madinah. He took 400 of the Muslims and overtook them at Dhat ar-Riqa. They were so taken by surprise that they fled their houses without a struggle and took refuge in the mountains.</p>
<p>After this in Shaban A. H. 4, the Holy Prophet went forth to Badr to fight Abu Sufyan. At the end of the Battle of Uhud, he had challenged the Holy Prophet and the Muslims, saying, "We shall again meet you in combat at Badr next year." In reply the Holy Prophet announced through a Companion: "All right: we accept your challenge." Accordingly, at the appointed time he reached Badr with 1,500 of the Muslims. From the other side, Abu Sufyan left Makkah with an army of 2,000 men, but could not have the courage to march beyond Marr-az-Zahran (modern, Wadi Fatimah). The Holy Prophet waited for him at Badr for eight days; the Muslims during these days did profitable business with a trading party. This incident help- ed more than restore the image of strength of the Muslims that had been tarnished at Uhud. It also made the whole of Arabia realize that the Quraish alone could no longer resist Muhammad (upon whom be Allah's peace and blessings). (Please also refer to E.N. 124 of
Al-i-\`Imran).</p>
<p>This image and position of the Muslims was further strengthened by another event. Dumat al-Jandal (modern, Al-Jauf) was an important place at the border between Arabia and Syria. When the caravans of the Arabs, trading between Iraq in the south and Syria and Egypt in the north, passed that way, they were harassed and looted by the natives. In Rabi al- Awwal, A. H. 5, the Holy Prophet himself went to punish them with an army of 1,000 men. They could not muster up courage to come out and fight him and, therefore, fled the place. This caused the whole of northern Arabia to dread the power of Islam, and the tribes began to realize that the great power emerging from Al-Madinah was formidable and could no longer be resisted by one or a few of the tribes.</p>
<h2>The Battle of the Trench</h2>
<p>Such were the conditions when the Battle of the Trench took place. It was in fact a combined raid by many of the Arab tribes, who wanted to crush the power of Madinah. It had been instigated by the leaders of the Bani an-Nadir, who had settled in Khyber after their banishment from Madinah. They went round to the Quraish and Ghatafan and Hudhail and many other tribes and induced them to gather all their forces together and attack Madinah jointly. Thus, in Shawwal, A. H. 5, an unprecedentedly large army of the Arab tribes marched against the small city of Madinah. From the north came Jews of Bani an-Nadir and Bani Qainuqa who after their banishment from Madinah, had settled in Khaiber and Wad il Qura. From the east advanced the tribes of Ghatafan, Bani Sulaim, Fazarah, Murrah, Ashja, Sad, Asad, etc. and from the south the Quraish, along with a large force of their allies. Together they numbered from ten to twelve thousand men.</p>
<p>Had it been a sudden attack, it would have been disastrous. But the Holy Prophet was not unaware of this in Madinah. His intelligence men and the sympathizers of the Islamic movement and the people influenced by it were present in every tribe, who kept him informed of the enemy's movements. Even before the enemy could reach his city, he got a trench dug out on the north-west of Madinah in six days, and having the Mount Salat their back, took up a defensive position with 3,000 men in the protection of the Trench. To the south of Madinah there were many gardens (even now there are) so that it could not be attacked from that side. To the east there are lava rocks which are impassable for a large army. The same is the case with the south western side. The attack, therefore, could be made only from the eastern and western sides of the Uhud, which the Holy Prophet had secured by digging a trench. The disbelievers were not at all aware that they would have to counter the trench outside
Madinah. This kind of a defensive stratagem was unknown to the Arabs. Thus, they had to lay a long siege in winter for which they had not come prepared.</p>
<p>After this, only one alternative remained with the disbelievers: to incite the Jewish tribe of Bani Quraizah, who inhabited the south eastern part of the city, to rebellion. As the Muslims had entered a treaty with them that in case of an attack on Madinah they would defend the city along with them, the Muslims had made no defensive arrangement there and had even sent their families to take shelter in the forts situated on that side. The invaders perceived this weakness of the Islamic defenses. They sent Huyayy bin Akhtab, the Jewish leader of the Bani an-Nadir, to the Bani Quraizah so as to induce them to break the treaty and join the war. In the beginning, they refused to oblige and said that they had a treaty with Muhammad (upon whom be Allah's peace) who had faithfully abided by it and given them no cause for complaint. But when Ibn Akhtab said to them, "Look, I have summoned the united force of entire Arabia against him: this is a perfect opportunity to get rid of him. If
you lose it, you will never have another opportunity," the anti Islamic Jewish mind prevailed over every moral consideration and the Bani Quraizah were persuaded to break the treaty.</p>
<p>The Holy Prophet received news of this. He at once told Sad bin Ubadah, Sad bin Muadh, Abdullah bin Rawahah and Khawwat bin Jubair, chiefs of the Ansar, to go and find out the truth. He advised them that if they found Bani Quraizah still loyal to the treaty, they should return and say so openly before the Muslim army; however, if they found that they were bent upon treachery they should only inform him so that the common Muslims would not be disheartened. On reaching there the Companions found the Bani Quraizah fully bent on mischief They told the Companions openly, "There is no agreement and no treaty between us and Muhammad." At this they returned to the Islamic army and submitted their report to the Holy Prophet, saying, "'Adal and Qarah." That is, "The Quraizah are bent upon doing what the Adal and Qarah had done with the preachers of Islam at Raji."</p>
<p>This news spread among the Muslims and caused great consternation among them, for they had been encircled and their city had been endangered on the side where there existed no defensive arrangement and where they had also sent their families to take shelter in the forts. This further increased the activities of the hypocrites and they started making psychological attacks to break the morale of the Muslims. One said, "How strange! We were being foretold that the lands of Caesar and Chosroes would fall to us, but here we are that not one of us can go out even to relieve himself." Another one asked for permission to leave his post at the Trench so that he could go and protect his own house which was in danger. Another one started making secret propaganda to the effect: "Settle your affair with the invaders yourselves and hand over Muhammad to them." This was a highly critical hour of trial, which exposed every person who harbored any hypocrisy in his heart. Only the true and
sincere Muslims remained firm and steadfast in their resolve and devotion.</p>
<p>In the meantime Nuaim bin Masud, a member of the Ashja branch of the Ghatafan tribe, became a Muslim and came before the Holy Prophet and submitted: "No one as yet knows that I have embraced Islam: You can take from me whatever service you please." The Holy Prophet replied: "Go and sow the seeds of discord among the enemy."' So, first of all, Nu'aim went to the Quraizah with whom he was on friendly terms, and said to them, "The Quraish and the Ghatafan can become wearied of the siege and go back, and they will lose nothing, but you have to live here with the Muslims. Just consider what will be your position if the matter turns that way. Therefore, I would advise you not to join the enemy until the outsiders should send some of their prominent men as hostages to you." This had the desired effect upon the Bani Quraizah and they decided to demand hostages from the united front of the tribes. Then he went to the chiefs of the Quraish and the Ghatafan and said to them, "The Bani
Quraizah seem to be slack and irresolute. May be they demand some men as hostage from you, and then hand them over to Muhammad (upon whom be Allah's peace) to settle their affair with him. Therefore, be very firm and cautious in your dealing with them." This made the leaders of the united front suspicious of Bani Quraizah. and they sent them a message, saying, "We are tired of the long siege; let there be a decisive battle; let us, therefore, make a general assault simultaneously from both the sides." The Bani Quraizah sent back the word, saying, "We cannot afford to join the war unless you hand over some of your prominent men to us as hostages." The leaders of the united front became convinced that what Nuaim had said was true. They refused to send hostages. And the Bani Quraizah, on the other side, also felt that Nuaim had given them the correct counsel. Thus, the strategy worked: it divided the enemy against itself.</p>
<p>The siege was prolonged for more than 25 days. It was winter. The supply of food and water and forage was becoming more and more scarce everyday and division in the camp was also a great strain on the state of morale of the besiegers. Then, suddenly one night a severe windstorm accompanied by thunder and lightning hit the camp. It added to the cold and darkness. The wind overthrew the tents and put the enemy in disarray. They could not stand this severe blow of nature. They left the battleground even during the night and returned to their homes. When the Muslims awoke in the morning, there was not a single enemy soldier to be seen on the battlefield. The Holy Prophet, finding the battlefield completely empty, said: "The Quraish will never be able to attack you after this: now you will take the offensive." This was a correct assessment of the situation. Not only the Quraish but the united front of all the enemy tribes had made their final assault against Islam and had failed. Now
they could no longer dare invade Madinah; now the Muslims were on the offensive.</p>
<h2>Raid on Bani Quraizah</h2>
<p>When the Holy Prophet returned from the Trench, Gabriel came to him in the early afternoon with the Divine Command the the Muslims should not lay aside the arms yet but should deal with the Bani Quraizah as well. On receipt of this Command, the Holy Prophet got announced: "Everyone who is steadfast in obedience should not offer his Asr Prayer till he reaches the locality of the Bani Quraizah." Immediately after this, he dispatched Hadrat Ali with a contingent of soldiers as vanguard towards the Quraizah. When they reached there, the Jews climbed on to their roof tops and started hurling abuses on the Holy Prophet and the Muslims, but their invectives could not save them from the consequences of their treachery. They had committed breach of the treaty right at the most critical moment of the war, joined hands with the invaders and endangered the entire population of Madinah. When they saw the contingent of Hadrat Ali, they thought that they had come only to overawe them. But when
the whole Islamic army arrived under the command of the Holy Prophet himself and laid siege to their quarters, they were very frightened. They could not stand the severity of the siege for more than two or three weeks. At last, they surrendered themselves to the Holy Prophet on the condition that they would accept whatever decision Hadrat Sad bin Muadh, the chief of the Aus, would give. They had accepted Hadrat Sad as their judge because in the pre-Islamic days the Aus and the Quraizah had been confederates and they hoped that in view of the past ties he would help them quit Madinah as had happened in the case of the Bani Qainuqa and the Bani an-Nadir before. The people of the Aus themselves wished that Hadrat Sad treat their previous allies leniently. But Hadrat Sad had just experienced and seen how the two Jewish tribes who had been allowed to leave Madinah previously had instigated the other tribes living around Madinah and summoned the united front of ten to twelve thousand men
against the Muslims. He was also aware how treacherously this last Jewish tribe had behaved right on the occasion when the city was under attack from outside and threatened the safety of the whole of its population. Therefore, he decreed that all the male members of the Quraizah should be put to death, their women and children taken prisoners, and their properties distributed among the Muslims. The sentence was carried out duly. When the Muslims entered their strongholds they found that the treacherous people had collected 1,500 swords, 300 coats of mail, 2,000 spears and 1,500 shields in order to join the war. If Allah's succor had not reached the Muslims, all this military equipment would have been used to attack Madinah from the rear right at the time when the polytheists were making preparations for a general assault on the Muslims after crossing the Trench. After this disclosure there remained no doubt that the decision of Hadrat Sad concerning those people was absolutely
correct.</p>
<h2>Social Reforms</h2>
<p>Though the period of two years between the Battles of Uhud and the Trench was a period of disturbance and turmoil and the Holy Prophet and his Companions could hardly relax in peace and security even for a day, the work of reform as a whole and the reconstruction of the Muslim society continued uninterrupted. This was the time when the Islamic laws pertaining to marriage and divorce were complemented; the law of inheritance was introduced, drinking and gambling were prohibited, and the new laws and regulations concerning many other aspects of the economic and social life were enforced.</p>
<p>In this connection, an important thing that needed to be reformed was the question of the adoption of a son. Whoever was adopted by the Arabs as a son was regarded as one of their own offspring: he got share in inheritance; he was treated like a real son and real brother by the adopted mother and the adopted sister; he could not marry the daughter of his adopted father and his widow after his death. And the same was the case if the adopted son died or divorced a wife. The adopted father regarded the woman as his real daughter-in-law. This custom clashed in every detail with the laws of marriage and divorce and inheritance enjoined by Allah in Surahs Al-Baqarah and An-Nisa. It made a person who could get no share in inheritance entitled to it at the expense of those who were really entitled to it. It prohibited marriage between the men and the women who could contract marriage perfectly lawfully. And, above all, it helped spread the immoralities which the Islamic Law wanted to
eradicate. For a real mother and a real sister and a real daughter cannot be like the adopted mother and the adopted sister and the adopted daughter, however one may try to sanctify the adopted relations as a custom. When the artificial relations endued with customary sanctity are allowed to mix freely like the real relations, it cannot but produce evil results. That is why the Islamic law of marriage and divorce, the law of inheritance and the law of the prohibition of adultery required that the concept and custom of regarding the adopted son as the real son should be eradicated completely.</p>
<p>This concept, however, could not be rooted out by merely passing a legal order, saying, The adopted son is not the real son. The centuries old prejudices and superstitions cannot be changed by mere word of mouth. Even if the people had accepted the command that these relations were not the real relations, they would still have looked upon marriage between the adopted mother and the adopted son, the adopted brother and the sister, the adopted father and the daughter, and the adopted father- in-law and the daughter-in- law odious and detestable. Moreover, there would still exist some freedom of mixing together freely. Therefore, it was inevitable that the custom should be eradicated practically, and through the Holy Prophet himself. For no Muslim could ever conceive that a thing done by the Holy Prophet himself, and done by him under Allah's Command, could be detestable. Therefore, a little before the Battle of the Trench, the Holy Prophet was inspired by Allah that he should
marry the divorced wife of his adopted son, Zaid bin Harithah (may Allah be pleased with him), and he acted on this Command during the siege of the Bani Quraizah. (The delay probably was caused for the reason that the prescribed waiting period had not yet ended, and in the meantime the Holy Prophet had to become busy in the preparation for war).</p>
<h2>Storm of Propaganda at the Marriage of Hadrat Zainab</h2>
<p>As soon as the marriage was contracted, there arose a storm of propaganda against the Holy Prophet. The polytheists, the hypocrites and the Jews, all were burning with jealousy at his triumphs which followed one after the other. The way they had been humbled within two years after Uhud, in the Battle of the Trench, and in the affair of the Quraizah, had made them sore at heart. They had also lost hope that they could ever subdue him on the battlefield. Therefore, they seized the question of this marriage as a god send for themselves and thought they would put an end to his moral superiority, which was the real secret of his power and success. Therefore, stories were concocted that Muhammad, God forbid, had fallen in love with his daughter-in-law, and when the son had come to know of this, he divorced his wife, and the father married his daughter-in-law. The propaganda, however, was absurd on the face of it. Hadrat Zainab was the Holy Prophet's first cousin. He had known her from
childhood to youth. So, there could be no question of his falling in love with her at first sight. Then he himself had arranged her marriage with Hadrat Zaid under his personal influence, although her whole family had opposed it. They did not like that a daughter of the noble Quraish should be given in marriage to a freed slave. Hadrat Zainab herself was not happy at this arrangement. But everyone had to submit to the Holy Prophet's command. The marriage was solemnized and a precedent was set in Arabia that Islam had raised a freed slave to the status of the Quraishite nobility. If the Holy Prophet had in reality any desire for Hadrat Zainab, there was no need of marrying her to Hadrat Zaid; he himself could have married her. But in spite of all this, the shameless opponents invented stories of love, spread them with great exaggeration and publicized them so vehemently that even some Muslims also began to accept them as true.</p>
<h2>Preliminary Commandments of Purdah</h2>
<p>The fact that the tales invented by the enemies also became topics of conversation among the Muslims was a clear sign that the element of sensuality in society had crossed all limits. If this malady had not been there, it was not possible that minds would have paid any attention whatever to such absurd and disgusting stories about a righteous and pure person like the Holy Prophet. This was precisely the occasion when the reformative Commandments pertaining to the law of <em>Hijab</em> or Purdah were first enforced in the Islamic society. These reforms were introduced in this Surah and complemented a year later in Surah An-Nur, when a slander was made on the honor of Hadrat Aishah.(For further details, see Introduction to Surah An-Nur).</p>
<h2>Domestic Affairs of the Holy Prophet</h2>
<p>There were two other problems which needed attention at that time. Though apparently they pertained to the Holy Prophet's domestic life, it was necessary to resolve them for the domestic and mental peace of the person, who was exerting every effort to promote the cause of Allah's Religion and was day and night absorbed in this great mission. Therefore, Allah took these two problems also officially in His own hand.</p>
<p>The first problem was that economically the Holy Prophet at that time was in straitened circumstances. During the first four years he had no source of income whatever. In 4 A. H. after the banishment of the Bani an-Nadir, a portion of their evacuated lands was reserved for his use by the Command of Allah, but it was not enough for his family requirements. On the other hand, the duties of the office of Prophethood were so onerous that they were absorbing all his energies of the mind and body and heart and every moment of his time, and he could not make any effort at all for earning his livelihood. In conditions such as these when his wives happened to disturb his mental peace because of economic hardships he would feel doubly strained and taxed.</p>
<p>The other problem was that before marrying Hadrat Zainab, he had four wives already in the houses: Hadrat Saudah, Hadrat Aishah, Hadrat Hafsah, and Hadrat Umm Salamah. Hadrat Zainab was his fifth wife. At this the opponents raised the objection, and the Muslims also started entertaining doubts, that as for others it had been forbidden to keep more than four wives at a time, but how the Holy Prophet himself had taken a fifth wife also.</p>
<h2>Subject Matter and Topics</h2>
<p>These were the questions that were engaging the attention of the Holy Prophet and the Muslims at the time Surah Al-Ahzab was revealed, and replies to the same form the subject matter of this Surah.</p>
<p>A perusal of the theme and the background shows that the Surah is not a single discourse which was sent down in one piece but it consists of several injunctions and commandments and discourses, which were sent down, one after the other, in connection with the important events of the time, and then were put together in one Surah. Its following parts stand out clearly distinguished from one another:</p>
<ol>
  <li>
    <p>Verses 1-8 seem to have been sent down before the Battle of the Trench. Their perusal, keeping the historical background in view, shows that at the time of their revelation Hadrat Zaid had already divorced Hadrat Zainab. The Holy Prophet was feeling the necessity that the concepts and customs and superstitions of ignorance concerning the adoption of the son should be eradicated, and he was also feeling that the delicate and deep sentiments the people cherished about the adopted relations merely on emotional grounds would not be rooted out until he himself took the initiative to eradicate the custom practically. But at the same time he was hesitant and considering seriously that if he married the divorced wife of Hadrat Zaid then, the hypocrites and the Jews and the <em>mushriks</em> who were already bent on mischief would get a fresh excuse to start a propaganda campaign against Islam. This was the occasion of the revelation of vv. 1-8.</p>
  </li>
  <li>
    <p>In verses 9-27 an appraisal has been made of the Battle of the Trench and the raid against the Bani Quraizah. This is a clear proof that these verses were sent down after these events.</p>
  </li>
  <li>
    <p>The discourse contained in vv. 28-35 consists of two parts. In the first part, Allah has given a notice to the wives of the Holy Prophet, who were being impatient of the straitened circumstances, to the effect:"Choose between the world and its adornments, and Allah, His Prophet and the Hereafter. If you seek the former, you should say so openly: you will not be kept back in hardship even for a day, but will be sent off gracefully. And if you seek the latter, you should cooperate with Allah and His messenger and bear patiently." In the second part, initial steps were taken towards the social reforms whose need was being felt by the minds moulded in the Islamic pattern themselves. In this regard, reform was started from the house of the Holy Prophet himself and his wives were commanded to avoid behaving and conducting themselves in the ways of the pre Islamic days of ignorance, ,to remain in their houses with dignity, and to exercise great caution in their conversation with
    the other men. This was the beginning of the Commandments of Purdah.</p>
  </li>
  <li>
    <p>Verses 36-48 deal with the Holy Prophet's marriage with Hadrat Zainab. In this section the opponents' objection about this marriage have been answered; the doubts that were being created in the minds of the Muslims have been removed; the Muslims have been acquainted with the Holy Prophet's position and status; and the Holy Prophet himself has been counseled to exercise patience on the false propaganda of the disbelievers and the hypocrites.</p>
  </li>
  <li>
    <p>In verse 49 a clause of the law of divorce has been laid down. This is a unique verse which was sent down on some occasion probably in connection with the same events.</p>
  </li>
  <li>
    <p>In verses 50-52 a special regulation of marriage has been laid down for the Holy Prophet, which points out that he is an exception to the several restrictions that have been imposed on the other Muslims in regard to marital life.</p>
  </li>
  <li>
    <p>In verses 53-55 the second step was taken towards social reform. It consists of the following injunctions: Restriction on the other men to visit the houses of the Holy Prophet's wives; Islamic etiquette concerning visits and invitations; the law that only the near relatives could visit the holy wives in their houses; as for the other men, they could speak to or ask them a thing from behind a curtain; the injunction that the Holy Prophet's wives were forbidden for the Muslims like their mothers; and none could marry any of them after him.</p>
  </li>
  <li>
    <p>In verses 56-57 warning was given to stop criticizing the Holy Prophet's marriage and his domestic life, and the believers instructed not to indulge in fault finding like the enemies of Islam, but to invoke the blessings of Allah for their Prophet; moreover, they were instructed that they should avoid falsely accusing one another even among themselves, not to speak of the person of the Prophet.</p>
  </li>
  <li>
    <p>In verse 59 the third step for social reform was taken. All the Muslim women were commanded that they should come out well covered with the outer garments and covering their faces whenever they came out of their houses for a genuine need.</p>
  </li>
</ol>
<p>After this till the end of the Surah the hypocrites and other foolish and mean people have been rebuked for the propaganda that they were carrying on at that time against Islam and the Muslims.</p>;
`
