export default `
 <h2>Name</h2>
<p>The Surah takes its name from verse 15 in which the word <em>Saba</em> has occurred, which implies that it is the Surah in which mention has been made of Saba (i. e. the Sabaeans).</p>
<h2>Period of Revelation</h2>
<p>The exact period of its revelation is not known from any reliable tradition. However, the style shows that it is either the middle or the early Makkan period. If it is the middle period, it was probably its initial stage when the persecution had not yet become tyrannical and the Islamic movement was being suppressed only by resort to derision and ridicule, rumor mongering, false allegations and casting of evil suggestions in the people's minds.</p>
<h2>Theme and Subject Matter</h2>
<p>The Surah deals with those objections of the disbelievers, which they were raising against the Holy Prophet's message of <em>Tauhid</em> and the Hereafter, and about his Prophethood itself, mostly in the form of absurd allegations and taunts and mockery. These objections have been answered, sometimes by citing them and sometimes without citing them, and the discourse itself shows which objection is being answered at a particular place. The answers mostly take the form of instruction and admonition and argument, but at some places the disbelievers have been warned also of the evil consequences, of their stubbornness. In this connection, the stories of the Sabaeans and the Prophets David and Solomon have been related to impress this lesson: "You have both these historical precedents before you. On the one hand, there were the Prophets David and Solomon, who had been blessed by Allah with great powers and such grandeur and glory as had been granted to hardly any people before them.
In spite of this, they were not proud and arrogant, but remained grateful servants of their Lord. They were never rebellious. On the other hand, there were the people of Saba, who, when blessed by Allah, became proud, and were consequently so thoroughly destroyed and dispersed as to be remembered only in myths and legends. With these precedents in view, you may see and judge for yourselves as to which bind of the life is better: that which is built on belief in <em>Tauhid</em> and the Hereafter and the attitude of gratefulness to Allah, or that which is based on disbelief and <em>shirk</em> and denial of the Hereafter and the worship of the world."</p>
`
