export default `
 <h2>Name</h2>
<p>The word <em>Fatir</em> of the first very verse is the title given to this Surah, which simply means that it is a Surah in which the word <em>Fatir</em> has occurred. The other name is <em>Al Malaika</em>, which also occurs in the first verse.</p>
<h2>Period of Revelation</h2>
<p>The internal evidence of the style shows that the period of the revelation of this Surah is probably the middle Makkan period, and especially that part of it, when antagonism had grown quite strong and every sort of mischief was being adopted to frustrate the mission of the Holy Prophet.</p>
<h2>Subject Matter and Theme</h2>
<p>The discourse is meant to warn and reprove the people of Makkah and their chiefs for their antagonistic attitude that they had then adopted towards the Holy Prophet's message of <em>Tauhid</em>, like a well wisher, and also to admonish them like a teacher, as if to say: "O foolish people, the way to which this Prophet is calling you is to your own advantage. Your anger, your tricks and machinations against it and your conspiracies and designs to frustrate it are not directed against him but against your own selves. If you do not listen to him, you will be harming your own selves, not him. Just consider and ponder over what he says : there is nothing wrong in it. He repudiates shirk. If you look around carefully, you will yourself realize that there is no basis for shirk in the world. He presents the doctrine of <em>Tauhid</em>. If you use your common sense, you will come to the conclusion that there is no being, beside Allah, Creator of the Universe, which might possess divine
attributes and powers and authority. He tells you that you have not been created to be irresponsible in this world, but you have to render an account of your deeds before your God, and that there is life after the life of this world when everyone will meet the consequences of what he has done here. If you thing a little you will see that your doubts and your astonishment about it are absolutely baseless. Don't you see the phenomenon of the reproduction of creation day and night. How can then your own recreation be impossible for that God Who created you from an insignificant sperm drop? Doesn't your own intellect testify that the good and the evil cannot be alike? Then think and judge for yourselves as to what is reasonable, should the good and the evil meet with the same fate and end up in the dust, or should the good be requited with good and the evil with evil? Now, if you do not admit and acknowledge these rational and reasonable things and do not abandon your false gods, and
wish to continue living only as irresponsible people in the world, the Prophet will not lose anything. It is you yourselves only who will suffer the consequences. The Prophet's only responsibility was to make the truth plain to you, which be has done."</p>
<p>In this connection, the Holy Prophet has been consoled again and again, as if to say :"When you are doing full justice to the preaching of your mission, you do not incur any responsibility for those who persist in their error and do not accept and follow the right way." Furthermore, he has also been consoled to the effect "You should neither grieve on account of those who do not want to believe, nor consume yourself with the thought of how to bring them to the rights path. Instead of this, you should pay your full attention to those who are inclined to listen to you."</p>
<p>The believers also, in this connection, have been given the good news so that they may feel strengthened and encouraged and remain steadfast on the path of the truth with full faith in the promises made by Allah.</p>
`
