export default `
 <h2>Name</h2>
<p>The Surah takes its name from the two letters of the alphabet with which it begins.</p>
<h2>Period of Revelation</h2>
<p>A study of the style shows that it was either sent down during the last stage of the middle Makkan period, or it is one of those Surahs, which were sent down during the last stage of the Holy Prophet's stay at Makkah.</p>
<h2>Subject Matter and Theme</h2>
<p>The object of the discourse is to warn the Quraish of the consequences of not believing in the Prophethood of Muhammad (may Allah's peace and blessings be upon him) and of resisting and opposing it with tyranny, ridicule and mockery. The aspect of the warning is dominant and conspicuous although along with repeatedly giving the warnings, arguments also have been given for the correct understanding by the people.</p>
<p>Arguments have been given for three things: (1) For <em>Tauhid</em>, from the signs of the universe and from common sense; (2) for the Hereafter, from the signs of the universe, from common sense and from man's own existence itself; and (3) for the Prophethood of the Prophet Muhammad, from the fact that he was facing all kinds of hardships in the preaching of his message without any selfish motive, and from this that whatever he was inviting the people to was rational and reasonable, accepting which was in the people's own interest.</p>
<p>On the strength of these arguments, themes of reprobation, reproof and warning have been presented repeatedly in a highly forceful manner, so that hearts are shaken up and those which have any capacity for accepting the truth left in them should not remain unmoved.</p>
<p>Imam Ahmad, Abu Daud, Nasai, Ibn Majah and Tabarani have related on the authority of Hadrat Ma'qil bin Yasar that the Holy Prophet said:"Surah Ya Sin is the heart of the Qur'an."This is similar to describing the Surah Al Fatiha has the <em>Umm al Qur'an</em> (the essence or core of the Qur'an), because Al Fatihah contains the sum and substance of the teaching of the whole Quran. The Surah Ya Sin has been called the throbbing heart of the Qur'an because it presents the message of the Qur'an in a most forceful manner, which breaks the inertness and stirs the spirit of man to action.</p>
<p>Again Imam Ahmad, Aba Da'ud and Ibn Majah have related from the same Ma'qil bin Yasar that the Holy Prophet said: "Recite Surah Ya Sin to the dying ones among you." The object is not only to revive and refresh the whole Islamic creed in the mind of the dying person but also bring before him, in particular, a complete picture of the Hereafter so that he may know what stages he would have to pass through after crossing the stage of this worldly life. In view of this, it would be desirable that along with the recitation of the Surah Ya Sin its translation also is made for the benefit of the person who does not know Arabic so that the purpose of the admonition is duly fulfilled.</p>
`
