export default `
 <h2>Name</h2>
<p>The name is derived from the word <em>was saaffat</em> with which the Surah begins.</p>
<h2>Period of Revelation</h2>
<p>The subject matter and the style show that this Surah probably was sent down in the middle of the Makkan period, or perhaps in the last stage of the middle Makkan period. The style clearly indicates that antagonism is raging strong in the background and the Holy Prophet and his Companions are passing through very difficult and discouraging circumstances.</p>
<h2>Subject Matter and Theme</h2>
<p>The disbelievers of Makkah have been severely warned for their attitude of mockery and derision with which they were responding to the Holy Prophet's message of <em>Tauhid</em> and the Hereafter and for their utter refusal to accept and acknowledge his claim to Prophethood. In the end, they have been plainly warned that the Prophet whom they are mocking and ridiculing will overwhelm them in spite of their power and self and they will find the army of Allah encamping in the very courtyards of their houses (vv. 171-179. This notice was given at a time when there appeared no chance whatever of the Holy Prophet's success and triumph. The Muslims (who have been called Allah's army in these verses) were being made the target of severe persecution. Three- fourth of their population had already emigrated and hardly 40 to 50 of the Companions were left with the Holy Prophet in Makkah who were experiencing all sorts of the excesses with utter helplessness. Under such circumstances, in view
of the apparent conditions, no one could believe that the Holy Prophet and the handful of his ill equipped Companions would ultimately attain dominance. The people rather thought that the new movement would end and be buried in the ravines of Makkah. But hardly 15 to 16 years had passed when on the conquest of Makkah precisely the same thing happened of which the disbelievers had been forewarned.</p>
<p>Along with administering warnings, Allah in this Surah has done full justice also to the theme of inducement and instruction in a balanced way. Brief but impressive arguments have been given about the validity of the doctrines of <em>Tauhid</em> and the Hereafter. Criticism has been made of the creed of the <em>mushrikin</em> to show the absurdity of their beliefs; they have been informed of the evil consequences of their deviations, which have been contrasted with the splendid results of the faith and righteous acts. Then, in continuation of the same, Precedents from past history have been cited to show how Allah had been treating His Prophets and their followers : how He has been favoring His faithful servants and punishing their deniers and rejectors.</p>
<p>The most instructive of the historical narratives presented in this Surah is the important event of the pious life of the Prophet Abraham, who became ready to sacrifice his only son as soon as he received an inspiration from Allah. In this there was a lesson not only for the disbelieving Quraish, who waxed proud of their blood relationship with him, but also for the Muslims who had believed in Allah and His Messenger. By narrating this event they were told what is the essence and the real spirit of Islam, and how a true believer should be ready to sacrifice his all for the pleasure and approval of Allah after he has adopted it as his Faith and Creed.</p>
<p>The last verses of the Surah were not only a warning for the disbelievers but also a good news for the believers who were passing through highly unfavorable and discouraging conditions on account of their supporting and following the Holy Prophet. In these verses they were given the good news that they should not be disheartened at the hardships and difficulties they had to encounter in the beginning, for in the end they alone would attain dominance, and the standard bearers of falsehood, who appeared to be dominant at the time would be overwhelmed and vanquished at their hands. A few years later the turn the events took, proved that it was not an empty consolation but an inevitable reality of which they had been foretold in order to strengthen their hearts.</p>
`
