export default `
 <h2>Period of Revelation</h2>
<p>This Surah comprises several discourses which were revealed on different occasions during the period ranging probably between the end of A.H. 3 and the end of A.H. 4 or the beginning of A.H. 5. Although it is difficult to determine the exact dates of their revelations, yet it is possible to assign to them a fairly correct period with the help of the Commandments and the events mentioned therein and the Traditions concerning them. A few instances are given below by way of illustration:</p>
<ol>
  <li>
    <p>We know that the instructions about the division of inheritance of the martyrs and for the safeguard of the rights of the orphans were sent down after the Battle of Uhd in which 70 Muslims were killed. Then naturally the question of the division of the inheritance of the martyrs and the safeguard of the rights of their orphans arose in many families at Al-Madinah. From this we conclude that vv. 1 -28 were revealed on that occasion.</p>
  </li>
  <li>
    <p>We learn from the Traditions that the Commandment about salat during war time was given on the occasion of Zat-ur-Riqa'a, an expedition which took place in A. H. 4. From this we conclude that the discourse containing v. 102 was revealed on that occasion.</p>
  </li>
  <li>
    <p>The last warning (v. 47) to the Jews was given before the Banu Nadir were exiled from Al-Madinah in Rabi'-ulAwwal, A. H. 4. From this it may safely be concluded that the discourse containing v. 47 must have been revealed some time before that date.</p>
  </li>
  <li>
    <p>The permission about <em>tayammum</em> (the performance of ablutions with pure dust, in case no water be available) was given during the Bani-al-Mustaliq expedition, which took place in A. H. 5.. Therefore the probable period of the revelation of the discourse containing v. 43 was A. H. 5.</p>
  </li>
</ol>
<h2>Topics and Their Background</h2>
<p>Let us now consider the social and historical considerations of the period in order to understand the Surah. All the discourses in this Surah deal with three main problems which confronted the Holy Prophet at the time. First of all, he was engaged in bringing about an all round development of the Islamic Community that had been formed at the time of his migration to Al-Madinah. For this purpose he was introducing new moral, cultural, social, economic and political ways in place of the old ones of the pre-Islamic period. The second thing that occupied his attention and efforts was the bitter struggle that was going on with the <em>mushrik</em> Arabs, the Jewish clans and the hypocrites who were opposing tooth and nail his mission of reform. Above all he had to propagate Islam in the face of the bitter opposition of these powers of evil with a view to capturing more and more minds and hearts.</p>
<p>Accordingly, detailed instructions have been given for the consolidation and strengthening of the Islamic Community in continuation of those given in Al-Baqarah. Principles for the smooth running of family life have been laid down and ways of settling family disputes have been taught. Rules have been prescribed for marriage and rights of wife and husband have been apportioned fairly and equitably. The status of women in the society has been determined and the declaration of the rights of orphans has been made laws and regulations have been laid down for the division of inheritance, and instructions have been given to reform economic affairs. The foundation of the penal code has been laid down drinking has been prohibited, and instructions have been given for cleanliness and purity. The Muslims have been taught the kind of relations good men should have with their Allah and fellow men. Instructions have been given for the maintenance of discipline in the Muslim Community.</p>
<p>The moral and religious condition of the people of the Book has been reviewed to teach lessons to the Muslims and to forewarn them to refrain from following in their footsteps. The conduct of the hypocrites has been criticized and the distinctive features of hypocrisy and true faith have been clearly marked off to enable the Muslims to distinguish between the two.</p>
<p>In order to cope with the aftermath of the Battle of Uhd, Inspiring discourses were sent down to urge the Muslims to face the enemy bravely, for the defeat in the Battle had so emboldened the <em>mushrik</em> Arab clans and the neighboring Jews and the hypocrites at home that they were threatening the Muslims on all sides. At this critical juncture, Allah filled the Muslims with courage and gave them such instructions as were needed during that period of war clouds. In order to counteract the fearful rumors that were being spread by the hypocrites and the Muslims of weak faith, they were asked to make a thorough inquiry into them and to inform the responsible people about them. Then they were experiencing some difficulties in offering their salat during the expeditions to some places where no water was available for performing their ablutions, etc. In such cases they were allowed to cleanse themselves with pure earth and to shorten the salat or to offer the "Salat of Fear", when
they were faced with danger. Instructions were also given for the solution of the puzzling problem of those Muslims who were scattered among the unbelieving Arab clans and were often involved in war. They were asked to migrate to Al-Madinah, the abode of Islam.</p>
<p>This Surah also deals with the case of Bani Nadir who were showing a hostile and menacing attitude, in spite of the peace treaties they had made with the Muslims. They were openly siding with the enemies of Islam and hatching plots against the Holy Prophet and the Muslim Community even at Al-Madinah itself. They were taken to task for their inimical behavior and given a final warning to change their attitude, and were at last exiled from Al-Madinah on account of their misconduct.</p>
<p>The problem of the hypocrites, who had become very troublesome at that time, was involving the Believers in difficulties-- Therefore they were divided into different categories to enable the Muslims to deal with them appropriately.</p>
<p>Clear instructions were also given regarding the attitude they should adopt towards the non-belligerent clans. The most important thing needed at that time was to prepare the Muslims for the bitter struggle with the opponents of Islam. For this purpose greatest importance was attached to their character building, for it was obvious that the small Muslim Community could only come out successful, nay, survive, if the Muslims possessed high moral character. They were, therefore, enjoined to adopt the highest moral qualities and were severely criticized whenever any moral weakness was detected in them.</p>
<p>Though this Surah mainly deals with the moral and social reforms, yet due attention has been paid to propagation of Islam. On the one hand, the superiority of the Islamic morality and culture has been established over that of the Jews, Christians and mushriks; on the other hand, their wrong religious conceptions, their wrong morality and their evil acts have been criticized to prepare the ground for inviting them to the way of the Truth.</p>
<h2>Subject: Consolidation of the Islamic Community</h2>
<p>The main object of this Surah is to teach the Muslims the ways that unite a people and make them firm and strong. Introductions for the stability of family, which is the nucleus of community have been given. Then they have been urged to prepare themselves for defense. Side by side with these, they have been taught the importance of the propagation of Islam. Above all, the importance of the highest moral character in the scheme of consolidation of the Community has been impressed.</p>
<h3>Topics and their Interconnection</h3>
<p>Just, fair and equitable laws and regulations for the smooth running of family life have been laid down for the husband and wife. Detailed instructions have been given for the division of inheritance and due regard has been paid to the rights of orphans. <strong>1 - 35</strong></p>
<p>In order to inculcate the right spirit for the observance of rules and regulations, the Muslims have been enjoined to show generosity to all around them and to be free from meanness, selfishness, stinginess of mind, because this is essential for the consolidation of the Communities and helpful for the propagation of Islam. <strong>36 - 42</strong></p>
<p>The ways of the purification of mind and body for the offering of Salat have been taught because it plays the most important part in every scheme of moral and social reform. <strong>43</strong></p>
<p>After moral preparation, instructions for defense have been given. First of all, the Muslims have been warned to be on their guard against the cunning machinations and vile practices of the local Jews who were hostile to the New Movement. This caution was necessary for removing some possible misunderstanding that might have arisen on account of the pre-Islamic alliance between the people of Al-Madinah and the Jews. <strong>44 - 57</strong></p>
<p>Then they have been enjoined to place their trusts and offices of trust in the custody of honest and qualified persons, and to do what is just and right, and to obey Allah and His Messenger and those among themselves entrusted with the conduct of their affairs and to turn to Allah and His Messenger for the settlement of their disputes. As such an attitude and behavior alone can ensure consolidation, they have been strongly warned that any deviation from this path will lead to their disintegration. <strong>58 - 72</strong></p>
<p>After this pre-requisite, they have been exhorted to make preparation for defense and to fight bravely for the cause of Islam, without showing any kind of cowardice or weakness. They have also been warned to be on their guard against hypocrites. A line of demarcation has been drawn to distinguish the intentional shirkers from the helpless devotees. <strong>73 - 100</strong></p>
<p>Here again instructions have been given for the offering of Salat during military campaigns and actual fighting. This is to impress the importance of Salat even at the time of fear and danger. <strong>101 - 103</strong></p>
<p>Before proceeding on to the next topic, the Muslims have been exhorted to persevere in their fight without showing any kind of weakness. <strong>104</strong></p>
<p>In order to make the Islamic Community firm and strong for defense, the Muslims have been enjoined to observe the highest standard of justice. The Muslims are required to deal out strict justice even in case of the enemy, with whom they might be involved in war. They should also settle disputes between husband and wife with justice. In order to ensure this, they should keep their beliefs and deeds absolutely free from every kind of impurity and should become the standard bearers of justice. <strong>105 - 135</strong></p>
<p>Resuming the theme of defense, the Muslims have been warned to be on their guard against their enemies. They have been admonished to take necessary precautions against the machinations of the hypocrites and the unbelievers and the people of the Book. As belief in Allah, and Revelation and Life-after-death is the only safeguard against every kind of enemy, they should sincerely believe in and follow His Messenger, Muhammad (Allah's peace be upon him). <strong>136 - 175</strong></p>
<p>Though this verse also deals with the family laws contained in verses <strong>1 - 35</strong>, it has been added as a supplement at the end of this Surah because it was revealed long after An-Nisa was being recited as a complete Surah. <strong>176</strong></p>
`
