export default `
 <h2>Name</h2>
<p>The Surah takes its name <em>Al Mu'min</em> from verse 28, implying thereby, that it is a Surah in which <em>Al Mu'min</em> (the Believer of Pharaoh's people) has been mentioned.</p>
<h2>Period of Revelation</h2>
<p>According to Ibn 'Abbas and Jabir bin Zaid, this Surah was sent down consecutively after Surah Az-Zumar, and its present position in the order of the Surahs in the Quran is the same as its chronological order.</p>
<h2>Background of Revelation</h2>
<p>There are clear indications in the subject matter of this Surah to the conditions in which it was revealed. The disbelievers of Makkah at that time were engaged in two kinds of the activities against the Holy Prophet. First, they were creating every kind of suspicion and misgiving in the minds of the people about the teaching of the Quran and the message of Islam and about the Holy Prophet himself by starting many disputes and discussions, raising irrelevant objections and bringing ever new accusations so that the Holy Prophet and the believers were sick of trying to answer them. Second, they were preparing the ground for putting an end to the Holy Prophet himself. They were devising one plot after the other, and on one occasion had even taken the practical steps to execute a plot. Bukhari has related a tradition on the authority of Hadrat Abdullah bin Amr bin 'As saying that one day when the Holy Prophet was offering his Prayer in the precinct's of the Kabbah, suddenly 'Uqbah
bin Abi Mu'ait, rushed forward and putting a piece of cloth round his neck started twisting it so as to strangle him to death. Hadrat Abu Bakr, who happened to go there in time, pushed him away. Hadrat Abdullah says that when Abu Bakr was struggling with the cruel man, he was saying words to the effect: "Would you kill a man only because he says: Allah is my Lord?" With a little variation this event has also been mentioned in Ibn Hisham, Nasa'i and Ibn Abi Hatim .</p>
<h2>Theme and Topics</h2>
<p>Both aspects of this have been clear]y stated at the very outset, and then the whole following discourse is a most effective and instructive review of them.</p>
<p>As an answer to the conspiracies of murder, the story of the Believer of the people of Pharaoh has been narrated (vv. 23 - 55) and through this story three different lessons have been taught to the three groups:</p>
<ol>
  <li>
    <p>The disbelievers have been admonished: "Whatever you intend to do against Muhammad (upon whom be Allah's peace), the same did the Pharaoh with his might intend against the Prophet Moses. Now, would you like to meet with the same fate with which he met by plotting such conspiracies ?"</p>
  </li>
  <li>
    <p>The Prophet Muhammad (upon whom be Allah's peace) and his followers have been taught the lesson: "These wicked people may apparently be very strong and powerful and you very weak and helpless against them, yet you should rest assured that the might of that God Whose Word you are trying to raise high is superior to every other power. Therefore, you should only seek Allah's refuge in response to every and any dreadful threat that they utter against you, and then busy yourself after this in fearlessly performing your mission. The God-worshiper has only one answer to every threat of the tyrant: \`I have taken refuge in my Lord and your Lord against every arrogant person who does not believe in the Day of Reckoning.' (v. 27) Thus, if you go on performing your mission fearless of every danger and with full trust in God, His succor will ultimately reach you, and the Pharaohs of today shall be doomed just as the Pharaohs of yesterday. Till that time you will have to face and bear
    patiently every wave of persecution and tyranny that may be directed against you."</p>
  </li>
  <li>
    <p>Besides these two, there was a third group of the people also in the society, who had been convinced in their hearts that the Truth was only on the side of the Holy Prophet Muhammad (upon whom be Allah's peace), and that the disbelieving Quraish were being unjust and cruel. But in spite of the conviction they were watching quietly and unconcerned the conflict between the Truth and falsehood. Allah here has aroused their conscience as if to say: "When the enemies of the Truth have openly plotted, in front of your very eyes, it would be a sad reflection on you if you still remained indifferent. Under such conditions, unless a person's conscience has wholly become dead, he should rise and perform the duty, which a righteous man from among the courtiers of Pharaoh himself had performed at a time when the Pharaoh had made up his mind to kill the Prophet Moses. The circumstances that prevent you from raising your voice had also obstructed the way of the Believer, but he had full
    faith in Allah and disregarded all expediency; then note that the Pharaoh was not able to do him any harm."</p>
  </li>
</ol>
<p>Now as for the conspiracies, which were continuing in Makkah day and night to defeat the Truth, on the one hand, arguments have been given to prove the doctrines of <em>Tauhid</em> and the Hereafter as true, which were the real basis of the dispute between the Holy Prophet and the disbelievers, and it has been stated plainly and openly that the disbelievers are wrangling over those truths without any knowledge. On the other, the motives which were the real cause of the Quraishite chiefs' conflict against the Holy Prophet, have been exposed. Apparently they were trying to have the common people believe that they had some genuine objections against the teaching of the Prophet and his claim to prophethood; that is why they were not prepared to listen to him. But, in fact, this was their struggle for power. In verse 56, they have been openly warned, so as to say" "The real cause of your denial is your arrogance and vanity. You think that if you acknowledge the prophethood of Muhammad
(upon whom be Allah's peace), your power and authority will come to an end. That is why you are straining every nerve to frustrate and defeat him."</p>
<p>In the same connection, the disbelievers have been warned again and again to the effect:"If you do not desist from wrangling against the Revelations of Allah, you will be doomed to the same fate as the nations of the past. Much worse torment awaits you in the Hereafter. Then you will repent, but it will be too late.</p>
`
