export default `
 <h2>Name</h2>
<p>The name of this Surah is composed of two words, <em>Ha-Mim</em> and <em>As-Sajdah</em>, which implies that it is a Surah which begins with <em>Ha-Mim</em> and in which a verse requiring the performance of <em>sajdah</em> (prostration) has occurred.</p>
<h2>Period of Revelation</h2>
<p>According to authentic Traditions, it was sent down after the affirmation of the Faith by Hadrat Hamzah and before the affirmation of the Faith by Hadrat Umar. Muhammad bin Ishaq, the earliest biographer of the Holy Prophet, has related on the authority of Muhammad bin Ka'b al-Qurzi, the famous follower of the Companions, that one day some of the Quraish chiefs were sitting in their assembly in the Masjid al-Haram, while in another corner of the Mosque there was the Holy Prophet sitting by himself. This was the time when Hadrat Hamzah had already embraced Islam and the people of the Quraish were feeling upset at the growing numbers of the Muslims. On this occasion, Utbah bin Rabi'ah (the father-in-law of Abu Sufyan) said to the Quraish chiefs: "Gentlemen, if you like I would go and speak to Muhammad (upon whom be Allah's peace and blessings) and put before him some proposals; maybe that he accepts one of them, to which we may also agree, and so he stops opposing us." They all
agreed to this, and Utbah went and sat by the Holy Prophet. When the Holy Prophet turned to him, he said: "Nephew, you know the high status that you enjoy in the community by virtue of your ancestry and family relations, but you have put your people to great trouble: you have created divisions among them and you consider them to be fools: you talk ill of their religion and gods, and say things as though all our forefathers were pagans. Now listen to me and I shall make some suggestions. Consider them well: maybe that you accept one of them." The Holy Prophet said: "Abul Walid, say what you want to say and I shall listen to you." He said, "Nephew, if by what you are doing, you want wealth, we will give you enough of it so that you will be the richest man among us; if you want to became an important man, we will make you our chief and will never decide a matter without you; if you want to be a king, we will accept you as our king; and if you are visited by a jinn, whom you cannot get
rid of by your own power, we will arrange the best physicians and have you treated at our own expense." 'Utbah went on speaking in this strain and the Holy Prophet went on listening to him quietly. Then he said, "Have you said, O Abul Walid, what you had to say?" He replied that he had. The Holy Prophet said: "Well, now listen to me."Then pronouncing <em>Bismilah ir Rehman-ir-Raihm</em> he began to recite this very Surah, and Utbah kept on listening to it, putting his hands behind his back and leaning on them as he listened. Coming to the verse of prostration (v. 38) the Holy Prophet prostrated himself; then raising his head, said, "This was my reply, O Abul Walid, now you may act as you please." then Utbah arose and walked back towards the chiefs, the people saw him from afar, and said: "By God! Utbab's face is changed. He does not look the same man that he was when he went from here." Then, when he came back and sat down, the people asked, "What have you heard?" He replied, "By
God! I have heard something the like of which I had never heard before. By God, it's neither poetry, nor sorcery, nor magic. O chiefs of the Quraish, listen to what I say and leave this man to himself. I think what he recites is going to have its effect. If the other Arabs overcome him, you will be saved from raising your band against your brother, and the others will deal with him. But if he overcame Arabia, his sovereignty would be your sovereignty and his honor your honor." Hearing this the chiefs spoke out:"You too, O father of Walid, have been bewitched by his tongue." Utbah replied, "I have given you my opinion; now you may act as you please." (Ibn Hisham, vol. I, pp. 313-314).</p>
<p>This story has been narrated by several other traditionists also on the authority of Hadrat Jabir bin Abdullah in different ways, with a little variation in wording. In some traditions it has also been related that when during the recitation the Holy Prophet had come to verse 13, viz."If they turn away, say to them: I warn you of a thunderbolt the like of which had visited the Ad and the Thamud,"Utbah had spontaneously placed his hand on the Holy Prophet's mouth, and said: "For God's sake, have mercy on your people." Afterwards he justified his action before the Quraish chiefs, saying: "You know that whatever Muhammad says is always fulfilled; therefore, I feared lest a torment should descend on us." (For details, see <em>Tafsir</em> Ibn Kathir, vol. IV, pp. 90- 91; <em>Al Bidayah wan-Nihayah</em>, vol. III, p. 62).</p>
<h2>Theme and Subject Matter</h2>
<p>In the discourse that Allah sent down in response to what Utbah said, no attention whatever was paid to the absurd proposals that he had made to the Holy Prophet. For what he had said was, in fact, an attack on the Holy Prophet's intention and his intellect. His assumption was that as there was no possibility of his being a Prophet and the Quran being Allah's Revelation, inevitably the motive of his invitation must either be the desire to obtain wealth and political power, or, God forbid, he had lost his reason. In the first case, he wanted to make a bargain with the Holy Prophet; in the second, he was insulting him when he said that the Quraish chiefs would have been cured of his madness at their own expense. Obviously, when the opponents come down to such absurd things, no gentleman would like to answer them, but would ignore them and say what he himself had to say.</p>
<p>Therefore, ignoring what Utbah said, this Surah makes antagonism its subject of discussion, which the unbelieving Quraish were showing stubbornly and wickedly in order to defeat the message of the Qur'an. They would say to tho Holy Prophet, "You may try however hard you try: we would not listen to you. We have put coverings on our hearts and we have closed our ears. There is a wall between you and us, which would never let us meet together."</p>
<p>They had given a clear notice to the Holy Prophet to the effect: "You may continue your mission of inviting the people to yourself, but we would go on opposing you as hard as we can to frustrate your mission."</p>
<p>For this object they had devised the following plan: Whenever the Holy Prophet or a follower of his would try to recite the Qur'an before the people, they would at once raise such a hue and cry that no one could bear anything.</p>
<p>They were desperately trying to misconstrue the verses of the Qur'an and spread every kind of misunderstanding among the people. They misconstrued everything and found fault even with the straightforward things. They would isolate words and sentences from their right context, from here and there, and would add their own words in order to put new meanings on them so as to mislead the people about the Quran and the Messenger who presented it.</p>
<p>They would raise strange objections a specimen of which has been presented in this Surah. They said, "If an Arab presents a discourse in Arabic, what could be the miracle in it? Arabic is his mother tongue. Anyone could compose anything that he pleased in his mother tongue and then make the claim that he had received it from God. It would be a miracle if the person would suddenly arise and make an eloquent speech in a foreign tongue which he did not know. Then only could one say that the discourse was not of his own composition but a revelation from God."</p>
<p>Here is a resume of what has been said in answer to this deaf and blind opposition:</p>
<ol>
  <li>
    <p>The Qur'an is most certainly the Word of God, which He has sent down in Arabic. The ignorant people do not find any light of knowledge in the truths that have been presented in it plainly and clearly, but the people of understanding are seeing this light as well as benefiting by it. It is surely Allah's mercy that He has sent down this Word for the guidance of man. If a person regarded it as an affliction, it would be his own misfortune. Good news is for those who benefit by it and warning for those who turn away from it.</p>
  </li>
  <li>
    <p>If you have put coverings on your hearts and have made yourselves deaf, it is none of the Prophet's job to make the one hear who does not want to hear, and the one who does not want to understand understand forcibly. He is a man like you; he can make only those to hear and understand, who are inclined to hear and understand.</p>
  </li>
  <li>
    <p>Whether you close down your eyes and ears and put coverings on your hearts, the fact, however, is that your God is only One God, and you are not the servant of any one else. Your stubbornness cannot change this reality in any way. If you accept this truth and correct your behavior accordingly you will do good only to yourselves, and if you reject it, you will only be preparing your own doom.</p>
  </li>
  <li>
    <p>Do you have any understanding as to whom you disbelieve and with whom you associate others in divinity? It is with regard to that God Who has created this limitless universe, Who is the Creator of the earth and heavens, from Whose blessings you are benefiting on the earth, and on Whose provisions you are being fed and sustained. You set up His mean creatures as His associates and then you are made to understand the truth you turn away in stubbornness.</p>
  </li>
  <li>
    <p>If you still do not believe, then be aware that a sudden torment is about to visit you, the like of which had visited the Ad and the Thamud, and this torment also will not be the final punishment of your crimes, but there is in addition the accountability and the fire of Hell in the Hereafter.</p>
  </li>
  <li>
    <p>Wretched is the man who gets as company such satans from among men and jinn, who show him nothing but green and pleasant, who make his follies seem fair to him, who neither let him think aright himself nor let him hear right from others. But on the Day of Reckoning when their doom overtakes them, each one of them will say that if he happened to get hold of those who had misled and deceived him in the world, he would trample them under his foot.</p>
  </li>
  <li>
    <p>This Quran is an unchangeable Book. You can not defeat it by your machinations and falsehoods. Whether falsehood comes from the front or makes a secret and indirect attack from behind, it cannot succeed in refuting it.</p>
  </li>
  <li>
    <p>Today when this Quran is being Presented in your own language so that you may understand it, you say that it should have been sent down in some foreign tongue. But had We sent it in a foreign tongue for your guidance, you would yourselves have called it a joke, as if to say, "What a strange thing! The Arabs are being given guidance in a non- Arabic language, which nobody understands." This means that you, in fact, have no desire to obtain guidance. You are only inventing ever new excuses for not affirming the faith.</p>
  </li>
  <li>
    <p>Have you ever considered that if it became established that the Qur'an was really from Allah, then what fate you would meet by denying it and opposing it so vehemently as you do?</p>
  </li>
  <li>
    <p>Today you do not believe but soon you will see with your own eyes that the message of this Qur'an had pervaded the whole world and you have yourselves been overwhelmed by it. Then you will come to know that what you were being told was the very truth.</p>
  </li>
</ol>
<p>Besides giving these answers to the opponents, attention has been paid to the problems which the believers and the Holy Prophet himself were facing in that environment of active resistance. Not to speak of preaching the message to others, the believers were even finding it difficult to follow the way of the Faith. Any one about whom it became known that he had become a Muslim, life would become an agony. As against the dreadful combination of the enemy and its all pervading power, they were feeling utterly helpless and powerless. In this state, in the first place, they were consoled and encouraged, as if to say: "You are not, in fact, helpless and powerless, for any person who believes in God as his Lord and adheres to this belief and way of life resolutely, God's angels descend on him and help and support him at every stage, from the life of this world till the Hereafter." Then they were encouraged with the consolation: "The best man is be who does good, invites others to God
and proclaims firmly that he is a Muslim."</p>
<p>The question that was vexing the Holy Prophet at that time was as to how be should carve out a way of preaching his message when he had to face such heavy odds on every side. The solution he was given to this question was: "Although apparently the obstacles seem to be insurmountable, the weapon of good morals and character can smash and melt them away. Use this weapon patiently, and whenever Satan provokes you and incites you to use some other device, seek refuge in Allah."</p>
`
