export default `
 <h2>Name</h2>
<p>It is derived frog the sentence, <em>wa amru-hum shura baina hum</em>, of verse 38, implying thereby that it is a Surah in which the word <em>shura</em> has occurred.</p>
<h2>Period of Revelation</h2>
<p>Although it could not be known from any authentic traditions, yet one feels after a study of its subject matter that this Surah might have been sent down consecutively after Ha-Miim As Sajdah, for it seems to be, in a way, a supplement to it. This will become clear to every person who first studies Surah Ha-Mim As Sajdah carefully and then goes through this Surah. He will see that in that Surah the Quraish chiefs had been taken to tack for their deaf and blind opposition so that anyone in Makkah and in its out-skirts, who had any sense of morality and nobility left in him, should know how unreasonably the chiefs of the people were opposing Muhammad (upon whom be Allah's peace), and as against them, how serious he was in everything he said, how rational was his standpoint and how noble his character and conduct. Immediately after that warning this Surah was sent down, which did full justice to teaching and instruction, and made the truth of the Holy Prophet's message plain in
such an impressive way that anyone who had any element of the love of the truth in him and who had not been blinded by the errors of ignorance, could not help being influenced by it.</p>
<h2>Theme and Subject Matter</h2>
<p>The discourse begins in a way as if to say:"Why are you expressing surprise and amazement at what Our Prophet is presenting before you?What he says is not new or strange, nor anything novel, which might have been presented for the first time in history: that Revelation should come down to a man from God and he should be given instructions for the guidance of mankind. Allah has been sending similar Revelations with similar instructions to the former Prophets before this. It is not surprising that the Owner of the Universe should be acknowledged as Deity and Ruler, but what is strange is that one should accept another as divine and deity in spite of being His subject and slave. You are being angry with him who is presenting Tauhid before you, where as the shirk that you are practicing with regard to the Master of the Universe is such a grave crime as may cause the heavens to break asunder. The angels are amazed at this boldness of yours and fear that the wrath of Allah might
descend on you any moment."</p>
<p>After this the people have been told that a person's being appointed to Prophethood and his presenting himself as a Prophet does not mean that he has been made master of the people's destinies and he has come to the world with that very claim. Allah has kept the destinies in His own hand. The Prophet has come only to arouse the heedless and guide the strayed ones to the Right Path. To call to account those who do not listen to him and to punish or not to punish them is Allah's own responsibility. and not part of the Prophet's work. Therefore, they should take it out of their head that the Prophet has come with a claim similar to those that are made by their so called religious guides and saints to the effect that he who would not listen to them, or would behave insolently towards them, would be burnt to death: In this very connection, the people have also been told that the Prophet has not come to condemn them but he is their well wisher; he is warning them that the way they are
following will only lead to their own destruction.</p>
<p>Then, an answer has been given to the question: Why didn't Allah make all human beings righteous by birth, and why did He allow the difference of viewpoint owing to which the people start following each and every way of thought and action?The answer given is this: Owing to this very fact has it become possible for man to attain to the special mercy of Allah, which is not meant for other dumb creatures, but is only meant for those endowed with power and authority, who should take Allah as Patron and Guardian not instinctively but consciously by willing choice. Allah supports the man who adopts this way and guides and helps him to do good and right and admits him into His special mercy. On the contrary, the man who misuses his option and makes his patron those who are not, in fact, the guardians, and cannot be, are deprived of divine mercy. In this connection, it has also been made clear that only Allah is the Patron of man and of all other creatures. Others are neither the patron
nor have the power to do full justice to patronage. Man's success depends only on this that he should make no mistake in choosing a patron for himself by the use of his free choice, and should take only Him his Guide Who, in reality, is the real Patron.</p>
<p>After this, it has been explained what the <em>Din</em> being presented by the Holy Prophet Muhammad (upon whom be Allah's peace) really is:</p>
<p>Its primary basis that as Allah Almighty is the Creator, Master and real Patron of the Universe and Man, He alone is Man's Ruler, He alone has the right to give Man Faith (<em>Din</em>) and Law (system of belief and practice) and judge the disputes of man and tell what is Truth and what is falsehood. No other being has any right whatever to be man's lawgiver. In other words, like the natural sovereignty, the sovereignty with regard to lawmaking also is vested only in Allah. No man or creature, apart from Allah, can be the bearer of this sovereignty. And if a person does not recognize and accept this Divine rule of Allah, it is merely futile for him to recognize the natural sovereignty of Allah.</p>
<p>On this very basis has Allah ordained a <em>Din</em> (True Religion) for Man from the very beginning. It was one and the same Religion that was vouchsafed in every age to all the Prophets. No Prophet ever founded any separate religion of his own. The same one Religion has been enjoined by Allah for all Mankind since the beginning of creation, and all the Prophets have been following it and inviting others to follow it.</p>
<p>This Religion and Creed was not sent so that man may rest content only with believing in it, but it was sent with the purpose and intention that it alone should be introduced, established and enforced in the world, and no man made religion be made to prevail in Allah's earth apart from His Religion. The Prophets had not been appointed only to preach this Religion but to establish it particularly in the world.</p>
<p>This same was the original Religion of mankind, but after the death of the Prophets, selfish people created new creeds by creating schisms for vested interests due to self conceit, vanity and ostentation. All the different religions and creeds found in the world today have resulted from corruption of the original Divine Truth.</p>
<p>Now, the Holy Prophet Muhammad (upon whom be Allah's peace,) has been sent so that he may present before the people the same and original Religion in place of the various practices and artificial creeds and man made religions, and may try to establish the same. On this, if instead of being grateful, you feel angry and come out to fight him, it is your folly; the Prophet will not abandon his mission only because of your foolishness. He has been enjoined to adhere to his faith at all costs and to carry out the mission to which he has been appointed. Therefore, the people should not cherish any false hope that in order to please thee he would cater to the same whims and superstitions of ignorance which has corrupted Allah's Religion before.</p>
<p>You do not understand how great an impudence it is against Allah to adopt a man made religion and law instead of the Religion and Law enjoined by Allah. You think it is an ordinary thing and there is nothing wrong with it. But in the sight of Allah it is the worst kind of <em>shirk</em> and a grave crime whose punishment will be imposed on all those who enforced their own religion on Allah's earth and those who adopted and followed their religion.</p>
<p>Thus, after presenting a clear and visible concept of Religion it is said:"The best possible method that could be employed for your instruction and for bringing you to the Right Path has already been employed. On the one hand, Allah has sent down His Book, which is teaching you the truth in a most impressive way in your own language; and on the other, the lives of the Holy Prophet Muhammad (upon whom be Allah's peace) and his Companions are present before you by which you can see for yourselves what kind of men are prepared by the guidance given in this Book. Even then if you do not accept this guidance, nothing else in the world can bring you to the Right Path. The only alternative, therefore, is that you should be allowed to persist in the same error in which you have remained involved for centuries, and made to meet with the same doom which has been destined by Allah for such wrongdoers."</p>
<p>While stating these truths, brief arguments have been given, here and there, for <em>Tauhid</em> and the Hereafter, the world worshipers have been warned of the evil consequences and their punishment in the life hereafter, and the disbelievers have been criticized for the moral weaknesses, which were the real cause of their deviation from the truth. The Surah has been concluded with two important themes.</p>
<p>First, that the Holy Prophet was wholly unaware of this concept of the "Book" or the True Faith during the first forty years of his life and then his sudden appearance before the people with those two things, is a manifest proof of his being a Prophet.</p>
<p>Secondly, his presenting his own teaching as the teaching of God does not mean that he claims to have spoken to God, face to face, but God has conveyed to him this Guidance, as in the case of all other Prophets, in three ways: He speaks to His Prophets either through Revelation, or from behind a veil, or He sends an angel with the message. This thing was clarified so that the opponents did not have an opportunity of accusing the Holy Prophet of claiming to have spoken to God, face to face, and the lovers of the truth should know by what methods Allah gave instruction to the man whom He had appointed to the mission of Prophethood.</p>
`
