export default `
 <h2>Name</h2>
<p>It is derived from the sentence <em>wa tartt kullu ummat- in jathiyat-un</em> of verse 28, implying thereby that it is the Surah in which the word <em>jathiyah</em> has occurred.</p>
<h2>Period of Revelation</h2>
<p>The period of the revelation of this Surah also has not been mentioned in any authentic tradition, but its subject matter clearly shows that it was revealed consecutively after Surah Ad Dukhan. The close resemblance between the contents of the two Surahs makes them look like the twin Surahs.</p>
<h2>Subject Matter and Topics</h2>
<p>It answers the doubts and objections of the disbelievers of Makkah about <em>Tauhid</em> and the Hereafter and warns them for their attitude that they had adopted against the message of the Qur'an.</p>
<p>The discourse begins with the arguments for <em>Tauhid</em>. In this connection, reference has been made to the count- less Signs that are found in the world, from man's own body to the earth and heavens, and it is pointed out that everywhere around him man finds things which testify to <em>Tauhid</em> which he refuses to acknowledge. If man sees carefully the variety of animals, the day and night, the rainfall and the vegetation thereby, the winds and his own creation, and ponders over them intelligently, without prejudice, he will find these Signs sufficiently convincing of the truth that this universe is not Godless, nor under the control of many gods, but it has been created by One God, and He alone is its Controller and Ruler. However, the case of the person who is determined not to acknowledge and wants to remain involved in doubts and suspicions is different. He cannot be blessed with the faith and conviction from anywhere in the world.</p>
<p>A little below, in the beginning of the second section, it has been reiterated that the things man is exploiting in the world, and the countless forces and agencies that are serving his interests in the universe, did not come into being just accidentally, nor have they been provided by the gods and goddesses, but it is One God alone, Who has supplied and subjected these to him from Himself. If only a person uses his mind properly and rightly, his own intellect will proclaim that God alone is man's real Benefactor and He alone deserves that man should pay obeisance to Him.</p>
<p>After this, the disbelievers of Makkah have been taken to task and reproved for their stubbornness, arrogance, mockery and insistence on disbelief with which they were resisting the invitation of the Qur'an they have been warned that this Qur'an has brought the same blessing which had been granted to the children of Israel before, by virtue of which they became distinguished above all the people of the world. Then, when they failed to recognize the true worth of this blessing and disputed their religion and lost it, this blessing now has been sent to them. This is such a code of guidance which shows the clear highway of Religion to man. The people who would turn it down by their own folly, would only prepare for their own doom, and only such people would become worthy of God's succour and mercy who would adopt obedience to it and lead a life of piety and righteousness.</p>
<p>In this connection, the followers of the Holy Prophet have been instructed that they should forbear and pardon the absurd and foolish behavior towards them of the people fearless of God, for if they showed patience God Himself would deal with their opponents and would reward them for their fortitude.</p>
<p>Then, there is a criticism of the erroneous ideas that the disbelievers hold about the Hereafter. They said that life was only this worldly life there was no life hereafter. Man dies in the course of time just as a watch stops functioning suddenly. The body is not survived by any soul, which might be seized and then breathed again into the human body some time in the future. In this regard, they challenged the Holy Prophet, saying: "If you lay a claim to this, then raise our dead forefathers back to life." In answer to this, Allah has given the following arguments:</p>
<ol>
  <li>
    <p>"You do not say this on the basis of any knowledge but are uttering this grave thing on the basis of conjecture. Do you really have the knowledge that there is no other life after death, and the souls are not seized but are annihilated?"</p>
  </li>
  <li>
    <p>"Your this claim rests mainly on this that you have not seen any dead person rising back to life and returning to the world. Is this basis strong enough for a person to make a claim that the dead people will never rise to life?When you do not experience and observe a thing, does it mean that you have the knowledge that it does not exist at all?</p>
  </li>
  <li>
    <p>It is utterly against reason and justice that the good and the bad, the obedient and the disobedient, the oppressor and the oppressed, should be made equal ultimately. Neither a good act should bear a good result nor an evil act an evil result; neither the grievances of the oppressed be redressed nor the oppressor be punished, but everyone should meet with the same fate ultimately. Whoever has formed this view about the universe of God, has formed a patently wrong view. The unjust and wicked people adopt this view because they do not want to face the evil results of their deeds, but this world of God is not a lawless kingdom; it is rather a system based on the Truth, in which there can be no question of the injustice of regarding the good and the bad as equal.</p>
  </li>
  <li>
    <p>That the creed of the denial of the Hereafter is highly destructive of morals. This is adopted only by such people as are the slaves of their lusts, and for the reason that they should have full freedom to serve their lusts. Then, when they have adopted this creed, it goes on making them more and more perverse till at last their moral sense becomes dead and all avenues of guidance are closed against them.</p>
  </li>
</ol>
<p>After giving these arguments Allah says most emphatically: "Just as you did not become living of your own accord, but became living by Our power, so you do not die of your own accord, but die when We send death on you. And a time is certainly coming when you will all be gathered together. If you do not believe in this because of your ignorance and folly today, you may not; when the time arrives, you will see for yourself that you are present before your God and your whole book of conduct is ready accurately, which bears evidence against each of your misdeeds. Then you will come to know how dearly has your denial of the Hereafter and your mockery of it cost you."</p>;
`
