export default `
 <h2>Name</h2>
<p>The Surah derives its name from the sentence <em>wa amanu bi-ma nuzzila ala Muhammad-in</em> of verse 2, thereby implying that it is the Surah in which the holy name of Muhammad (upon wham be Allah's peace and blessings) has occurred. Besides, it has another well known name "<em>al-Qital</em> " also, which is derived from the sentence <em>wa dhukira fi-hal-qital</em> of verse 20.</p>
<h2>Period of Revelation</h2>
<p>The contents of this Surah testify that it was sent down after the hijrah at Madinah at the time when the fighting had been enjoined, though active fighting had not yet been undertaken. Detailed arguments in support of this view have been given in E. N. 8 below.</p>
<h2>Historical Background</h2>
<p>The conditions at the time when this Surah was sent down were such that the Muslims were being made the target of persecution and tyranny in Makkah in particular and in Arabia in general, and life had become miserable for them. Although the Muslims had emigrated to the haven of Madinah from every side, the disbelieving Quraish were not prepared to leave them alone and let them live in peace even there. Thus, the small settlement of Madinah was hemmed in by the enemy, who was bent upon exterminating it completely. The only alternative left with the Muslims were that either they should surrender to the forces of ignorance, giving up their mission of preaching the true Faith, or even following it in their private lives, or should rise to wage a war at the cost of their lives to settle finally and for ever whether Islam would stay in Arabia or the creed of ignorance. On this occasion Allah showed the Muslims the same way of resolution and will, which is the only way for the true
believers. He first permitted them to fight in Surah Al Hajj 39 and then enjoined fighting in Al Baqarah 190. But at that time everyone knew fully well what it meant to wage a war in those conditions. There were only a handful of Muslims in Madinah, who could not muster even a thousand soldiers; yet they were being urged to take up the sword and clash against the pagan forces of the whole of Arabia. Then the kind of the weapons needed to equip its soldiers for war could hardly be afforded by the town in which hundreds of emigrants were still homeless and unsettled even by resort to starving its members at a time when it had been boycotted economically by the Arabs on all sides.</p>
<h2>Theme and Subject Matter</h2>
<p>Such were the conditions when this Surah was revealed. Its theme is to prepare the believers for war and to give them preliminary instructions in this regard. That is why it has also been entitled <em>al-Qital</em>. It deals with the following topics:</p>
<p>At the outset it is said that of the two groups confronting each other at this time, one has refused to accept the Truth and has become an obstruction for others on the way of Allah, while the other group has accepted the Truth which had been sent down by Allah to His servant, Muhammad (upon whom be Allah's peace and blessings). Now, Allah's final decision is that He has rendered fruitless and vain all the works of the former group and set right the condition and affairs of the latter group.</p>
<p>After this, the Muslims have been given the initial war instructions they have been reassured of Allah's help and guidance: they have been given hope for the best rewards on offering sacrifices in the cause of Allah and they have been assured that their struggle in the cause of the Truth will not go to waste, but they will be abundantly rewarded both in this world and in the Hereafter.</p>
<p>Furthermore, about the disbelievers it has been said that they are deprived of Allah's support and guidance: none of their designs will succeed in their conflict with the believers, and they will meet a most evil fate both in this world and in the Hereafter. They thought they had achieved a great success by driving the Prophet of Allah out of Makkah, but in fact by this they had hastened their own doom.</p>
<p>After this, the discourse turns to the hypocrites, who were posing to be sincere Muslims before the command to fight was sent down, but were confounded when this command actually came down, and began to conspire with the disbelievers in order to save themselves from the hazards of war. They have been plainly warned to the effect that no act and deed is acceptable to Allah of those who adopt hypocrisy with regard to Him and His Prophet. There, the basic issue against which all those who profess the Faith are being tried is whether one is on the side of the Truth or Falsehood, whether one's sympathies are with Islam and the Muslims or with disbelief and the disbelievers, whether one keeps one's own self and interests dearer or the Truth which one professes to believe in and follow. One who fails in this test is not at all a believer; his Prayer and his Fasting and his discharging of the <em>zakat</em> deserve no reward from Allah.</p>
<p>Then the Muslims have been exhorted not to lose heart for being small in numbers and ill equipped as against the great strength of the disbelievers: they should not show weakness by offering peace to them, which might still further embolden them against Islam and the Muslims, but they should come out with trust in Allah and clash with the mighty forces of disbelief. Allah is with the Muslims: they alone shall triumph; and the might of disbelief will be humbled and vanquished.</p>
<p>In conclusion, the Muslims have been invited to spend their wealth in the cause of Allah. Although at that time they were economically very weak, the problem that they confronted was the very survival of Islam and the Muslims. The importance and delicacy of the problem demanded that the Muslims should not only risk their lives for safeguarding themselves and their Faith from the dominance of disbelief and for exalting Allah's Religion but should also expend their economic resources as far as possible in the preparations for war. Therefore, they were clearly warned to the effect. Anyone who adopted a niggardly attitude at the time, would not, in fact, harm Allah at all, but would result in his own destruction, for Allah does not stand in need of help from men. If one group of men shirked offering sacrifices in the cause of His Religion, Allah would remove it and bring another group in its place.</p>;
`
