export default `
 <h2>Name</h2>
<p>It is derived from the words <em>Inna fatah-na laka fat-han mubina</em> of the very first verse. This is not only a name of the Surah but also its title in view of the subject matter, for it deals with the great victory that Allah granted to the Holy Prophet and the Muslims in the form of the Truce of Hudaibiyah.</p>
<h2>Period of Revelation</h2>
<p>Traditions concur that it was sent down in Dhil-Qadah, A. H. 6, at a time when the Holy Prophet was on his return journey to Madinah after concluding the Truce of Hudaibiyah with the disbelievers of Makkah.</p>
<h2>Historical Background</h2>
<p>The events in connection with which this Surah was sent down began life this: One day the Holy Prophet saw in a dream that he had gone to Makkah with his Companions and had performed the umrah there. Obviously, the Prophet's dream could not be a mere dream and fiction for it is a kind of Divine inspiration as Allah Himself has confirmed in verse 27 below and said that He Himself had shown that dream to His Messenger. Therefore, it was not merely a dream but a Divine inspiration which the Holy Prophet had to obey and follow.</p>
<p>Apparently, there was no possible way of acting on this inspiration. The disbelieving Quraish had debarred the Muslims from proceeding to the Ka'bah for the past six years and no Muslim had been allowed during that period to approach the Kabah for the purpose of performing hajj and umrah. Therefore, it could not be expected that they would allow the Holy Prophet to enter Makkah along with a party of his Companions. If they had proceeded to Makkah in the pilgrim garments with the intention of performing umrah, along with their arms, this would have provoked the enemy to war, and if they had proceeded unarmed, this would have meant endangering his own as well as his Companions' lives. Under conditions such as these nobody could see and suggest how the Divine inspiration could be acted upon.</p>
<p>But the Prophet's position was different. It demanded that he should carry out whatever Command his Lord gave fearlessly and without any apprehension and doubt. Therefore, the Holy Prophet informed his Companions of his dream and began to make preparations for the journey. Among the tribes living in the suburbs also he had the public announcement made that he was proceeding for umrah and the people could join him. Those who could only see the apparent conditions thought that he and his Companions were going into the very jaws of death none of them therefore was inclined to accompany him in the expedition. But those who had true faith in Allah and His Messenger were least bothered about the consequences. For them this information was enough that it was a Divine inspiration and Allah's Prophet had made up his mind to carry it into effect. After this nothing could hinder them from accompanying the Messenger of Allah. Thus, 1,400 of the Companions became ready to follow him on this
highly dangerous journey.</p>
<p>This blessed caravan set off from Madinah in the beginning of Dhil Qa'dah, A. H. 6. At Dhul Hulaifah they entered the pilgrims robe with the intention of umrah, took 70 camels with collars round their necks indicating that they were sacrificial animals; kept only a sword each in sheaths, which the pilgrims to the Kabah were allowed to carry according to the recognized custom of Arabia, but no other weapon. Thus, the caravan set out for the Ka'bah, the House of Allah, at Makkah, chanting the prescribed slogan of <em>Labbaik, Allahuma Labbaik</em>.</p>
<p>The nature of the relations between Makkah and Madinah in those days was known too well to every Arab. Just the previous year, in Shawwal A. H. 5, the Quraish mustering the united strength of the Arab tribes had invaded Madinah and the well known Battle of the Trench had taken place. Therefore, when the Holy Prophet along with such a large caravan set off for the home of his blood-thirsty enemy, the whole of Arabia looked up with amazement, and the people also noticed that the caravan was not going with the intention to fight but was proceeding to the House of Allah in a forbidden month in the pilgrims garb carrying sacrificial animals and was absolutely unarmed.</p>
<p>The Quraish were confounded at this bold step taken by the Holy Prophet. Dhil-Qa'dah was one of those forbidden months which had been held as sacred for pilgrimage in Arabia for centuries. Nobody had a right to interfere with a caravan which might be coming for hajj or umrah in the pilgrims garb in this month; so much so that even an enemy tribe could not hinder it from passing through its territory according to the recognized law of the land. The Quraish therefore were caught in a dilemma, for if they attacked this caravan from Madinah and stopped it from entering Makkah, this would arouse a clamor of protest in the whole country, and all the Arab tribes would have the misgiving that the Quraish had monopolized the Ka'bah as exclusively their own, and every tribe would be involved in the mistrust that now it depended on the will of the Quraish to allow or not to allow anyone to perform hajj or umrah in the future and that they would stop any tribe with which they were angry
from visiting the Ka'bah just as they had stopped the Madinese pilgrims. This they thought would be a grave mistake, which would cause the entire Arabia to revolt against them. But, on the other hand, if they allowed Muhammad (upon whom be Allah's peace and blessings) and his large caravan to enter their city safely, they would lose their image of power in Arabia and the people would say that they were afraid of Muhammad. At last, after a great deal of confusion, perplexity and hesitation they were overcome by their false sense of honor and for the sake of their prestige they took the decision that they would at no cost allow the caravan to enter the city of Makkah.</p>
<p>The Holy Prophet had dispatched a man of the Bani Ka'b as a secret agent so that he may keep him fully informed of the intentions and movements of the Quraish. When the Holy Prophet reached Usfan, he brought the news that the Quraish had reached Dhi Tuwa with full preparations and they had sent Khalid bin Walid with two hundred cavalry men in advance towards Kura'al-Ghamim to intercept him. The Quraish wanted somehow to provoke the Holy Prophet's Companions into fighting so that they may tell the Arabs that those people had actually come to fight and had put on the pilgrims garments for umrah only to deceive others.</p>
<p>Immediately on receipt of this information the Holy Prophet changed his route and following a very rugged, rocky track reached Hudaibiyah, which was situated right on the boundary of the sacred Makkan territory. Here, he was visited by Budail bin Warqa the chief of the Bani Khuza'ah, along with some men of his tribe. They asked what he had come for. The Holy Prophet replied that he and his Companions bad come only for pilgrimage to the House of Allah and for going round it in worship and not for war. The men of Khuza'ah went and told this to the Quraish chiefs and counseled them not to interfere with the pilgrims. But the Quraish were obstinate. They sent Hulays bin Alqamah, the chief of the Ahabish, to the Holy Prophet to persuade him to go back. Their object was that when Muhammad (upon whom be Allah's peace) would not listen to Hulays, he would come back disappointed and then the entire power of the Ahabish would be on their side. But when Hulays went and saw that the whole
caravan had put on the pilgrims garments, had brought sacrificial camels with festive collars round their necks, and had come for doing reverence to the House of Allah and not to fight, he returned to Makkah without having any dialogue with the Holy Prophet and told the Quraish chiefs plainly that those people bad no other object but to pay a visit to the Ka'bah; if they debarred them from it, the Ahabish would not join them in that, because they had not become their allies to support them if they violated the sacred customs and traditions.</p>
<p>Then the Quraish sent \`Urwah bin Mas'ud Thaqafi; he had lengthy negotiations with the Holy Prophet in an effort to persuade him to give up his intention to enter Makkah. But the Holy Prophet gave him also the same reply that he had given to the chief of the Khuza'ah, that they had not come to fight but to do honor to the House of Allah and carry out a religious duty. Urwah went back and said to the Quraish: "I have been to the courts of the Caesar and Khosroes, and the Negus also, but by God, never have I seen any people so devoted to a king as are the Companions of Muhammad (upon whom be Allah's peace and blessings) to him. If Muhammad makes his ablutions they would not let the water thereof fall on the ground but would rub it on their bodies and clothes. Now you may decide as to what you should do."</p>
<p>In the meantime when the messages were coming and the negotiations were going on, the Quraish tried again and again to quietly launch sudden attacks on the Muslim camp in order to provoke the Companions and somehow incite them to war, but every time they did so the Companions' forbearance and patience and the Holy Prophet's wisdom and sagacity frustrated their designs. On one occasion forty or fifty of their men came at night and attacked the Muslim camp with stones and arrows. The Companions arrested all of them and took them before the Holy Prophet, but he let them go. On another occasion 80 men came from the direction of Tan'im right at the time of the Fajr Prayer and made a sudden attack. They were also caught, but the Holy Prophet forgave them, too. Thus, the Quraish went on meeting failure after failure in every one of their designs.</p>
<p>At last, the Holy Prophet sent Hadrat Uthman (may Allah be pleased with him) as his own messenger to Makkah with the message that they had not come to fight but only for pilgrimage and had brought their sacrificial camels along, and they would go back after performing the rite of pilgrimage and offering the sacrifice. But the Quraish did not agree and withheld Hadrat Uthman in the city. In the meantime a rumor spread that Hadrat Uthman had been killed; and when he did not return in time the Muslims took the rumor to be true. Now they could show no more forbearance. Entry into Makkah was different for there was no intention to use force. But when the ambassador was put to death, the Muslims had no alternative but to prepare for war. Therefore, the Holy Prophet summoned all his Companions together and took a solemn pledge from them that they would fight to death. In view of the critical occasion it was not an ordinary undertaking. The Muslims numbered only 1400 and had come
without any weapons, were encamping at the boundary of Makkah, 250 miles away from their own city, and the enemy could attack them in full strength, and could surround them with its allies from the adjoining tribes as well. In spite of this, none from the caravan except one man failed to give his pledge to fight to death, and there could be no greater proof of their dedication and sincerity than that in the cause of Allah. This pledge is well known in the history of Islam as the pledge of Ridwan.</p>
<p>Later it was known that the news about Hadrat Uthman was false. Not only did he return but under Suhail bin 'Amr from the Quraish also arrived a deputation to negotiate peace with the Holy Prophet. Now, the Quraish no more insisted that they would disallow the Holy Prophet and his Companions to enter Makkah. However, in order to save their face they only insisted that he went back that year but could come the following year to perform the umrah. After lengthy negotiations peace was concluded on the following terms:</p>
<ol>
  <li>
    <p>War would remain suspended for ten years, and no party would indulge in any hostility, open or secret, against the other.</p>
  </li>
  <li>
    <p>If any one during that period from among the Quraish went over to Muhammad, without his guardian's permission, he would return him to them, but if a Companion of Muhammad came over to the Quraish, they would not return him to him.</p>
  </li>
  <li>
    <p>Every Arab tribe would have the option to join either side as its ally and enter the treaty.</p>
  </li>
  <li>
    <p>Muhammad and his men would go back that year and could come the following year for umrah and stay in Makkah for three days, provided that they brought only one sheathed sword each, and no other weapon of war. In those three days the Makkans would vacate the city for them (so that there was no chance of a clash), but they would not be allowed to take along any Makkan on return.</p>
  </li>
</ol>
<p>When the conditions of the treaty were being settled, the whole of the Muslim army was feeling greatly upset. No one understood the expedience because of which the Holy Prophet was accepting the conditions. No one was far sighted enough to foresee the great benefit that was to result from this treaty. The disbelieving Quraish looked at it as their victory, and the Muslims were upset as to why they should be humiliated to accepting those mean conditions. Even a statesman of th caliber of Hadrat Umar says that he had never given way to doubt since the time he had embraced Islam but on this occasion he also could not avoid it. Impatient he went to Hadrat Abu Bakr and said "Is he (the Holy Prophet) not Allah's Messenger, and are we not Muslims, and are they not polytheists? Then, why should we agree to what is humiliating to our Faith?" He replied "O Umar, he is surely Allah's Messenger, and Allah will never make him the loser." Unsatisfied he went to the Holy Prophet himself and
put the same questions to him, and he also gave him the same replies as Hadrat Abu Bakr had given. Afterwards Hadrat Umar continued to offer voluntary prayers and give aims so that Allah may pardon his insolence that he had shown towards the Holy Prophet on that occasion.</p>
<p>Two things in the treaty were highly disturbing for the Muslims first, the second condition, about which they said that it was an expressly unfair condition, for if they had to return a fugitive from Makkah, why should not the Quraish return a fugitive from Madinah? To this the Holy Prophet replied: "What use would be he to us, who fled from us to them? May Allah keep him away from us!And if we return the one who flees to us from them, Allah will create some other way out for him." The other thing that was rankling in their minds was the fourth condition. The Muslims thought that agreeing to it meant that they were going back unsuccessful and this was humiliating. Furthermore, the question that was causing them feel upset wad that they had accepted the condition of going back without performing the pilgrimage to the Ka'bah, whereas the Holy Prophet had seen in the vision that they were performing tawaf at Makkah. To this the Holy Prophet replied that in his vision the year had
not been specified. According to the treaty conditions, therefore, they would perform the <em>tawaf</em> the following year if it pleased Allah.</p>
<p>Right at the time when the document was being written, Suhail bin 'Amr's own son, Abu Jandal, who had become a Muslim and been imprisoned by the pagans of Makkah somehow escaped to the Holy Prophet's camp. He had fetters on his feet and signs of violence on his body. He implored the Holy Prophet that he help secure his release from imprisonment. The scene only increased the Companions' dejection, and they were moved beyond control. But Suhail bin 'Amr said the conditions of the agreement had been concluded between them although the writing was not yet complete; therefore, the boy should be returned to them. The Holy Prophet admitted his argument and Abu Jandal was returned to his oppressors.</p>
<p>When the document was finished, the Holy Prophet spoke to the Companions and told them to slaughter their sacrificial animals at that very place, shave their heads and put off the pilgrim garments, but no one moved from his place. The Holy Prophet repeated the order thrice but the Companions were so overcome by depression and dejection that they did not comply. During his entire period of apostleship on no occasion had it ever happened that he should command his Companions to do a thing and they should not hasten to comply with it. This caused him a great shock, and he repaired to his tent and expressed his grief before his wife, Hadrat Umm Salamah. She said, "You may quietly go and slaughter your own camel and call the barber and have your head shaved. After that the people would automatically do what you did and would understand that whatever decision had been taken would not be changed." Precisely the same thing happened. The people slaughtered their animals, shaved their
heads or cut their hair short and put off the pilgrim garb, but their hearts were still afflicted with grief.</p>
<p>Later, when this caravan was returning to Madinah, feeling depressed and dejected at the truce of Hudaibiyah, this Surah came down at Dajnan (or according to some others, at Kura' al-Ghamim), which told the Muslims that the treaty that they were regarding an their defeat, was indeed a great victory. After it had come down, the Holy Prophet summoned the Muslims together and said: "Today such a thing has been sent down to me, which is more valuable to me than the world and what it contains." Then be recited this Surah, especially to Hadrat Umar, for he was the one who was feeling most dejected.</p>
<p>Although the believers were satisfied when they heard this Divine Revelation, not much longer afterwards the advantages of this treaty began to appear one after the other until every one became fully convinced that this peace treaty indeed was a great victory:</p>
<ol>
  <li>
    <p>In it for the first time the existence of the Islamic State in Arabia was duly recognized. Before this in the eyes of the Arabs the position of the Holy Prophet Muhammad (upon whom be Allah's peace) and his Companions was no more than of mere rebels against the Quraish and other Arab tribes, and they regarded them as the outlaws. Now the Quraish themselves by concluding this agreement with the Holy Prophet recognized his sovereignty over the territories of the Islamic State and opened the way for the Arab tribes to enter treaties of alliance with either of the political powers they liked.</p>
  </li>
  <li>
    <p>By admitting the right of pilgrimage to the House of Allah for the Muslims, the Quraish also admitted that Islam was not an anti-religious creed, as they had so far been thinking, but it was one of the admitted religions of Arabia, and like the other Arabs, its followers also had the right to perform the rites of hajj and umrah. This diminished the hatred in the Arabs hearts that had been caused by the propaganda made by the Quraish against Islam.</p>
  </li>
  <li>
    <p>The signing of a no-war pact for ten years provided full peace to the Muslims, and spreading to every nook and corner of Arabia they preached Islam with such spirit and speed that within two years after Hudaibiyah the number of the people who embraced Islam far exceeded those who bad embraced it during the past 19 year or so. It was all due to this treaty that two years later when in consequence of the Quraish's violating the treaty the Holy Prophet invaded Makkah, he was accompanied by an army 10,000 strong, whereas on the occasion of Hudaibiyah only 1,400 men had joined him in the march.</p>
  </li>
  <li>
    <p>After the suspension of hostilities by the Quraish the Holy Prophet had the opportunity to establish and strengthen Islamic rule in the territories under him and to turn the Islamic society into a full fledged civilization and way of life by the enforcement of Islamic law. This is that great blessing about which Allah says in verse 3 of Surah Al-Ma'idah:"Today I have perfected your Religion for you and completed My blessing on you and approved Islam as the Way of Life for you." (for explanation, see Introduction to Surah Al-Ma'idah and its E. N. 15).</p>
  </li>
  <li>
    <p>Another gain that accrued from the truce with the Quraish was that being assured of peace from the south the Muslims overpowered all the opponent forces in the north and central Arabia easily. Just three months after Hudaibiyah, Khaiber, the major stronghold of the Jews, was conquered and after it the Jewish settlements of Fadak, Wad-il Qura, Taima and Tabuk also fell to Islam one after the other. Then all other tribes of central Arabia, which were bound in alliance with the Jews and Quraish, came under the sway of Islam. Thus, within two years after Hudaibiyah the balance of power in Arabia was so changed that the strength of the Quraish and pagan gave way and the domination of Islam became certain.</p>
  </li>
</ol>
<p>These were the blessings that the Muslims gained from the peace treaty which they were looking upon as their defeat and the Quraish as their victory. However, what had troubled the Muslims most in this treaty, was the condition about the fugitives from Makkah and Madinah, that the former would be returned and the latter would not be returned. But not much long afterwards this condition also proved to be disadvantageous for the Quraish, and experience revealed what far reaching consequences of it had the Holy Prophet fore seen and then accepted it. A few days after the treaty a Muslim of Makkah, Abu Basir, escaped from the Quraish and reached Madinah. The Quraish demanded him back and the Holy Prophet returned him to their men who had been sent from Makkah to arrest him. But while on the way to Makkah he again fled and went and sat on the road by the Red Sea shore, which the trade caravans of the Quraish took to Syria. After that every Muslim who succeeded in escaping from the
Quraish would go and join Abu Basir instead of going to Madinah, until 70 men gathered there. They would attack any Quraish caravan that passed the way and cut it into pieces at last, the Quraish themselves begged the Holy Prophet to call those men to Madinah, and the condition relating to the return of the fugitives of itself became null and void.</p>
<p>The Surah should be read with this historical background in view in order to fully understand it.</p>;
`
