export default `
 <h2>Name</h2>
<p>It is derived from the very first word <em>wadh-dhariyat</em>, which implies that it is a Surah which begins with the word <em>adh-dhariyat</em>.</p>
<h2>Period of Revelation</h2>
<p>The subject matter and the style clearly show that it was sent down in the period when although the Holy Prophet's invitation was being resisted and opposed with denial and ridicule and false accusations stubbornly, persecution had not yet started. Therefore, this Surah also seems to have been revealed in the same period in which the Surah Qaf was revealed.</p>
<h2>Subject Matter and Topics</h2>
<p>The Surah mostly deals with the Hereafter, and in the end it presents the invitation to <em>Tauhid</em>. In addition, the people have also been warned that refusal to accept the message of the Prophets and persistence in the concepts and creeds of ignorance have proved to be disastrous for those nations themselves which have adopted this attitude and way of life in the past.</p>
<p>About the Hereafter what this Surah presents in short but pithy sentences is this: The people's different and conflicting beliefs about the end of human life are themselves an express proof that none of these beliefs and creeds is based on knowledge; everyone by himself has formed an ideology on the basis of conjecture and made the same his creed. Someone thought that there would be no life-after-death; someone believed in the life- after-death, but in the form of the transmigration of souls someone believed in the life hereafter and the meting out of the rewards and punishments but invented different sorts of props and supports to escape retribution. About a question of such vital and fundamental importance a wrong view of which renders man's whole life-work wrong and waste and ruins his future for ever, it would be a disastrous folly to build an ideology only on the basis of speculation and conjecture, without knowledge. It would mean that man should remain involved in a grave
misunderstanding, pass his whole life in the heedlessness of error, and after death should suddenly meet with a situation for which he had made no preparation at all. There is only one way of forming the right opinion about such a question, and it is this: Man should seriously ponder over the knowledge about the Hereafter that the Prophet of Allah is conveying to him from Him, and should study carefully the system of the earth and heavens and his own existence: and should see whether the evidence of that knowledge's being sound and correct is afforded by everything around him or not. In this regard, the arrangement of the wind and rain, the structure of the earth and the creatures found on it, man's own self, the creation of the heavens and of everything in the world in the form of pairs have been presented as evidence of the Hereafter, and instances have been cited from human history to show that the temper of the empire of the Universe requires that the law of retribution must
operate here.</p>
<p>After this, giving the invitation to <em>Tauhid</em> briefly, it has been said : "Your Creator has not created you for the service of others but for His own service. He is not like your false gods, which receive sustenance from you and godhead of which cannot function without your help, but He is a God Who is the Sustainer of all, Who does not stand in need of sustenance from anyone and Whose Godhead is functioning by His own power and might.</p>
<p>In this very connection, it has also been stated that whenever the Prophets of Allah have been opposed and resisted, they have not been opposed and resisted on the basis of any rational ground but on the basis of the same obduracy and stubbornness and false pride that is being shown against the Prophet Muhammad (peace and blessings of Allah be upon him), and there is no other motive for it than rebellion and arrogance. Then the Holy Prophet has been instructed not to bother about the rebels but to go on performing his mission of invitation and admonition, for it is useful and beneficial for the believers although it may not be so for the other people. As for the wicked people who still persist in their rebellion, they should know that their predecessors who followed the same way of life, have already received their shares of the punishment, and these people's share of the punishment has been made ready for them.</p>;
`
