export default `
 <h2>Name</h2>
<p>It is derived from the very first cord "<em>Wat Tur-i</em>."</p>
<h2>Period of Revelation</h2>
<p>From the internal evidence of the subject matter it appears that this Surah too was revealed in the same stage of the Holy Prophet's life at Makkah in which the Surah Adh-Dhariyat was revealed. While going through it one can clearly feel that during the period of its revelation the Holy Prophet (peace and blessings of Allah be upon him) was being showered with objections and accusations but there is no evidence yet to show that severe persecution of the Muslims had started.</p>
<h2>Subject Matter and Topics</h2>
<p>The subject matter of its first section (vv. 1-28) is the Hereafter. As arguments for its possibility, necessity and occurrence had already been given in Surah Adh-Dhariyat, these have not been repeated here. However, swearing an oath by some realities and signs which testify to the Hereafter, it has been stated most emphatically that it will surely come to pass, and none has the power to prevent its occurrence. Then, it has been stated as to what will be the fate of those who deny it when it actually occurs, and how will those who believe in it and adopt the way of piety and righteousness accordingly, be blessed by Allah.</p>
<p>Then, in the second section (vv. 29-49) the Quraish chiefs' attitude towards the message of the Holy Prophet (peace and blessings of Allah he upon him) has been criticized. They called him a sorcerer, a madman, or a poet, and would thus mislead the common people against him so that they should not pay any serious attention to the message he preached. They looked upon him as a calamity that had suddenly descended on them and would openly wish that he met with a disaster so that they were rid of him. They accused him of fabricating the Qur'an by himself and of presenting it in the name of Allah, and this was, God forbid, a fraud that he was practicing. They would often taunt him, saying that God could not have appointed an ordinary man like him to the office of Prophethood. They expressed great disgust at his invitation and message and would avoid him as if he was asking them for a reward for it. They would sit and take counsels together to devise schemes in order to put an end to
his mission. And while they did all this they never realized what creeds of ignorance they were involved in and how selflessly and sincerely was Muhammad (peace and blessings of Allah be upon him) exerting himself to deliver them from their error. While criticizing them for this attitude and conduct, Allah has put them certain questions, one after the other, each of which is either an answer to some objection of theirs, or a criticism of some error. Then, it has been said that it would absolutely be of no avail to show them a miracle in order to convince them of his Prophethood, for they were such stubborn people as would misinterpret anything they were shown only to avoid affirming the faith.</p>
<p>In the beginning of this section as well as in its end, the Holy Prophet (peace and blessings of Allah be upon him) has been given the instruction that he should persistently continue giving his invitation and preaching his message in spite of the accusations and objections of his opponents and enemies, and should endure their resistance patiently till Allah's judgment comes to pass. Besides, he has been consoled, as if to say "Your Lord has not left you alone to face your enemies, after raising you as a Prophet, but He is constantly watching over you. Therefore, endure every hardship patiently till the Hour of His judgment comes, and seek through praising and glorifying your Lord the power that is required for exerting in the cause of Allah under such conditions.</p>;
`
