export default `
 <h2>Name</h2>
<p>The Surah derives its name from the very first word <em>wan Najm</em>. This title also does not relate to the subject matter, but is a name given to the Surah as a symbol.</p>
<h2>Period of Revelation</h2>
<p>According to a Tradition related by Bukhari, Muslim, Abu Da'ud and Nasai, on the authority of Hadrat Abdullah bin Mas'ud, the first Surah in which a verse requiring the performance of a <em>sajdah</em> (prostration) as sent down, is Surah An-Najm. The parts of this <em>Hadith</em> which have been reported by Aswad bin Yazid, Abu Ishaq and Zubair bin Mu'awiyah from Hadrat Ibn Mas'ud, indicate that this is the first Surah of the Qur'an, which the Holy Prophet (peace and blessings of Allah be upon him) had publicly recited before an assembly of the Quraish (and according to Ibn Marduyah, in the Ka'bah) in which both the believers and the disbelievers were present. At the end, when he recited the verse requiring the performance of a <em>sajdah</em> and fell down in prostration, the whole assembly also fall down in prostration with him, and even those chiefs of the polytheists who were in the forefront of the opposition to the Holy Prophet (peace and blessings of Allah be upon him)
could not resist falling down in prostration. Ibn Mas'ud (may Allah be pleased with him) says that he saw only one man, Umayyah bin Khalaf, from among the disbelievers, who did not fall down in prostration but took a little dust and rubbing it on his forehead said that that was enough for him. Later, as Ibn Mas'ud relates, he saw this man die in the state of disbelief.</p>
<p>Another eye witness of this incident is Hadrat Muttalib bin Abi Wada'ah, who had not yet become a Muslim. Nasai and Musnad Ahmad contain his own words to the effect: "When the Holy Prophet recited the Surah An-Najm and performed the <em>sajdah</em> and the whole assembly fell down in prostration along with him, I did not perform the <em>sajdah</em>. Now to compensate for the same whenever I recite this Surah I make sure never to abandon its performance."</p>
<p>Ibn Sad says that before this, in the Rajab of the 5th year of Prophethood, a small group of the Companions had emigrated to Abyssinia. Then, when in the Ramadan of the same year this incident took place the news spread that the Holy Prophet (peace and blessings of Allah be upon him) had recited Surah An-Najm publicly in the assembly of the Quraish and the whole assembly, including the believers as well as the disbelievers, had fallen down in prostration with him. When the emigrants to Abyssinia heard this news they formed the impression that the disbelievers of Makkah had become Muslims. Thereupon, some of them returned to Makkah in the Shawwal of the 5th year of Prophethood, only to learn that the news was wrong and the conflict between Islam and disbelief was raging as furiously as before. Consequently, the second emigration to Abyssinia took place, in which many more people left Makkah.</p>
<p>Thus, it becomes almost certain that this Surah was revealed in the Ramadan of 5th year of Prophethood.</p>
<h2>Historical Background</h2>
<p>The details of the period of revelation as given above point to the conditions in which this Surah was revealed. During the first five years of his appointment as a Prophet, the Holy Prophet (peace and blessings of Allah be upon him) had been extending invitation to Allah's Religion by presenting the Divine Revelations before the people only in private and restricted meetings and assemblies. During this whole period he could never have a chance to recite the Quran before a common gathering openly, mainly because of the strong opposition and resistance from the disbelievers. They were well aware of how magnetic and captivating was the Holy Prophet's personality and his way of preaching and how impressive were the Revelations of the Qur'an. Therefore, they tried their best to avoid hearing it them- selves and to stop others also from hearing it and to suppress his invitation by false propaganda by spreading every kind of suspicion against him. For this object, on the one hand,
they were telling the people that Muhammad (peace and blessings of Allah be upon him) had gone astray and was now bent upon misleading others as well; on the other hand, they would raise on uproar whenever he tried to present the Qur'an before the people so that no one could know what it was for which he was being branded as a misled and misguided person.</p>
<p>Such were the conditions when the Holy Prophet (peace and blessings of Allah be upon him) suddenly stood up one day to make a speech in the sacred precincts of the Ka'bah, where a large number of the Quraish had gathered together. Allah at that time made him deliver this discourse, which we have now in the form of the Surah An-Najm with us. Such was the intensity of the impression that when the Holy Prophet (peace and blessings of Allah be upon him) started reciting it the opponents were so completely overwhelmed that they could not think of raising any disorder, and when at the conclusion he fell down in prostration, they too fell down in prostration along with him. Later they felt great remorse at the weakness they had involuntarily shown. The people also started taunting them to the effect that whereas they had been forbidding others to listen to the Qur'an, that day not only had they themselves listened to it, with complete absorption but had even fallen down in prostration
along with Muhammad (peace and blessings of Allah be upon him). At last, they had to invent a story in order to get rid of the people's taunt and ridicule. They said "After he had recited <em>afara'ait-ul Lata wal Uzza wa Manat ath-thalitha-al ukhra</em>, we heard from Muhammad the words: <em>tilk al-gharaniqa- tal-'ula, wa anna shafa'at-u-hunna latarja</em> : 'They are exalted goddesses: indeed, their intercession may be expected.' From this we understood that Muhammad had returned to our faith." As a matter of fact, only a mad person could think that in the context of this Surah the sentences they claimed to have heard could have any place and relevance.(For details, please see E. N.'s 96 to 301 of Surah Al Hajj).</p>
<h2>Subject Matter and Topics</h2>
<p>The theme of the discourse is to warn the disbelievers of Makkah about the error of the attitude that they had adopted towards the Qur'an and the Prophet Muhammad (peace and blessings of Allah be upon him).</p>
<p>The discourse starts in a way as if to say: "Muhammad is neither deluded nor gone astray, as you are telling others in your propaganda against him, nor has he fabricated this teaching of Islam and its message, as you seem to think he has. In fact, whatever he is presenting is nothing but Revelation which is sent down to him. The verities that be presents before you, are not the product of his own surmise and speculation but realities of which he himself is an eye witness. He has himself seen the Angel through whom this knowledge is conveyed to him. He has been directly made to observe the great Signs of his Lord: whatever he says is not what he has himself thought out but what he has seen with his own eyes. Therefore, your disputing and wrangling with him is just like the disputing and wrangling of a blind man with a man of sight over a thing which the blind man cannot see but he can see."</p>
<p>After this, three things have been presented in their successive order:</p>
<p>First, the listeners have been made to understand that: "The religion that you are following is based on mere conjecture and invented ideas. You have set up a few goddesses like Lat and Manat and Uzza as your deities, whereas they have no share whatever in divinity. You regard the angels as the daughters of Allah, whereas you regard a daughter as disgraceful for your own selves. You think that these deities of fours can influence Allah in your favor, whereas the fact is that all the angels together, who are stationed closest to Allah, cannot influence Him even in their own favor. None of such beliefs that you have adopted, is based on knowledge and reason, but are wishes and desires for the sake of which you have taken some whims as realities. This is a grave error. The right and true religion is that which is in conformity to the reality, and the reality is never subject to thee people's wishes and desires so that whatever they may regard as a reality and truth should become
the reality and truth. Speculation and conjecture cannot help to determine as to what is according to the truth and what is not; it is knowledge. When that knowledge is presented before you, you turn away from it, and brand the one who tells you the truth as misguided. The actual cause of your being involved in this error is that you are heedless of the Hereafter. Only this world is your goal. Therefore, you have neither any desire for the knowledge of reality, nor you bother to see 'whether the beliefs you hold are according to the truth or not.</p>
<p>Secondly, the people have been told that: Allah is the caster and Sovereign of the entire Universe. The righteous is he who follows His way, and the misguided he who has turned away from His way. The error of the misguided and the righteousness of the righteous are not hidden from Him. He knows whatever everyone is doing: He will requite the evil with evil and the good with good. The final judgment will not depend on what you consider yourself to be, and on tall claims you make of your purity and chastity but on whether you are pious or impious, righteous or unrighteous, in the sight of God. If you refrain from major sins, He in His mercy will overlook your minor errors.'' .</p>
<p>Thirdly, a few basic principles of the true Religion which had been presented hundreds of years before the revelation of the Qur'an in the Books of the Prophets Abraham and Moses have been reiterated so that the people did not remain involved in the misunderstanding that the Prophet Muhammad (peace and blessings of Allah be upon him) had brought some new and novel religion, but they should know that these are the fundamental truths which the former Prophets of Allah have always been presenting in their respective ages. Besides, the same Books have been quoted to confirm the historical facts that the destruction of the 'Ad and the Thamud and of the people of the Prophets Noah and Lot was not the result of accidental calamities, but Allah has destroyed them in consequence of the same wickedness and rebellion from which the disbelievers of Makkah were not inclined to refrain and desist in any case.</p>
<p>After presenting these themes and discourses the Surah has been concluded, thus: "The Hour of Judgment has approached near at hand, which no one can avert. Before the occurrence of that Hour you are being warned through Muhammad (peace and blessings of Allah be upon him) and the Quran in the like manner as the former people had been warned before. Now, is it this warning that you find novel and strange? Which you mock and ridicule? Which you turn away from and cause disorder so that no one else also is able to hear what it is ? Don't you feel like weeping at your folly and ignorance? Abandon this attitude and behavior, bow down to Allah and serve Him alone!"</p>
<p>This was that impressive conclusion hearing which even the most hardened deniers of the Truth were completely overwhelmed, and when after reciting these verses of Divine Word the Holy Messenger of Allah (peace and blessings of Allah be upon him) fell down in prostration, they too could not help falling down in prostration along with him.</p>
`
