export default `
 <h2>Name</h2>
<p>This Surah is entitled Ar Rahman, the word with which it begins. This title, however, deeply relates to the subject matter of the Surah too, for in it, from the beginning to the end, the manifestations and fruits of Allah's attribute of mercy and grace have been mentioned.</p>
<h2>Period of Revelation</h2>
<p>The commentators generally hold the view that this is a Makki Surah, though according to some traditions which have been cited on the authority of Hadrat Abdullah bin Abbas, Ikrimah and Qatadah, it was revealed at Madinah. But, firstly, there are also some other traditions from these very authorities, which contradict this view; secondly, its subject matter bears a closer resemblance with the Makki Surahs than with the Madani Surahs; rather it appears to belong to the very early Makkah period. However, there are several authentic traditions which testify that it had been revealed in Makkah itself many years before the <em>hijrah</em>.</p>
<p>Musnad Ahmad contains a tradition from Hadarat Asma, daughter of Abu Bakr (may Allah bless them both), to the effect: "I saw the Messenger of Allah offering his Prayers in the sacred precincts of the Ka'bah facing the corner in which the "Black Stone" is fixed. This relates to the time when the Divine Command, <em>fasda bi-ma tumar</em> ("So, proclaim publicly, O Prophet, what you are being commanded") had not yet been revealed. The polytheists at that time were hearing the words, <em>Fa-biayyi alaa'i Rabbi kuma tukadhdhi ban</em>, being recited by him in the Prayer." This shows than this Surah had been sent down even before Surah Al-Hijr.</p>
<p>Al-Bazzar, Ibn Jarir, Ibn Al- Mundhir, Daraqutni (in <em>Al Afrad</em>), Ibn Marduyah and Ibn Al Khatib (in <em>Al- Tarikh</em>) have related, on the authority of Hadrat Abdullah bin Umar, that once the Holy Prophet (peace and blessings of Allah be upon him) recited Surah Ar-Rahman himself, or heard it recited before him : then he said to the people: How is it that I am not hearing from you the kind of good answer that the jinn had given to their Lord?When the people asked what it was he replied: "As I recited the Divine Words, <em>Fa bi- ayyi alaa'i Rabbi-kuma tukadhdhiban</em>, the jinn in response would repeat the words <em>La bi shai'in min ni'mati Rabbi- na nukadhdhib</em> : "We do not deny any of our Lord's blessings."</p>
<p>A similar theme has been related by Tirmidhi, Hakim and Hafiz Abu Bakr al-Bazzar from Hadrat Jabir bin Abdullah. Their tradition contains these words: "When the people kept silent on hearing the Surah Ar-Rahman, the Holy Prophet said 'I recited this very Surah before the jinn in the night when they had gathered together to hear the Qur'an. They responded to it better than you have. As I recited the Divine Words, <em>Fa bi ayyi alaa'i Rabbikuma tukadhdhiban</em> ("O jinn and men, which blessings of your Lord will you deny?") they would respond to it, saying: O our Lord, do not deny any of your blessings Praise is for You alone'!"</p>
<p>This tradition indicates that on the occasion of the incident that bas been related in Surah Al Ahqaf(vv. 29- 32) of the jinn's hearing the Qur'an from the Holy Prophet (peace and blessings of Allah be upon him) he was reciting Surah Ar Rahman in the Prayer. This happened in the 10th year of the Prophethood when the Holy Prophet had halted at Makkah on his way back from Ta'if. Although in some other traditions it has been reported that the Holy Prophet did not know then that the jinn were hearing him recite the Qur'an, but afterwards Allah had informed him of this, it is not unreasonable to suppose that just as Allah had informed him of the jinn's hearing the Qur'an so also Allah Himself might have told him as to what answer they were giving on hearing Surah Ar Rahman.</p>
<p>These traditions only indicate that Surah Ar Rahman had been revealed even before Surahs Al-Hijr and Al-Ahqaf. Besides, we come across another tradition which shows that it is one of those Surahs which were the earliest Revelations at Makkah. Ibn Ishaq has related this on the authority of Hadrat Urwah bin Zubair: The Companions one day said to one another: "The Quraish have never heard any one recite the Qur'an publicly to them, and who would read out the Divine Word aloud to them Hadrat Abdullah bin Masud said that he would. The Companions expressed the apprehension that he might be subjected to a harsh treatment and said that it should better be done by a person of a powerful family, who would protect him if the Quraish tried to subject him to violence. Hadrat Abdullah said: 'Let me alone : my Protector is Allah.' So early next morning he went to the Ka'bah while the Quraish chiefs were sitting in their respective conferences. Hadrat Abdullah arrived at the Maqam (station of
Abraham) and began to recite Surah Ar- Rahman raising his voice as he did so. The Quraish first tried for a while to understand what he was saying. Then,when they realized that it was the Word that Muhammad (peace and blessings of Allah be upon him) was representing as the Word of God, they fell upon him and began to hit him in the face. But Hadrat Abdullah was not deterred : he continued to receive the slaps and to read the Qur'an as long as he could, At last, when he returned with a swollen face, the Companions said that they apprehended the same. He replied: 'God's enemies were never so light for me as they were today. If you say I'll recite the Qur'an to them again tomorrow.' They all said, 'No, you have done enough; you have made them listen to what they didn't want to bear.'" (Ibn Hisham, vol. 1, p. 336).</p>
<h2>Theme and Subject Matter</h2>
<p>This is the only Surah of the Qur'an in which besides men the jinn also, who are the other creation of the earth endowed with freedom of will and action, have been directly addressed, and both men and jinn have been made to realize the wonders of Allah's power, His countless blessings, their own helplessness and accountability before Him, and have been warned of the evil consequences of His disobedience and made aware of the best results of His obedience. Although at several other places in the Qur'an there are clear pointers to show that like the men the jinn too are a creation who have been endowed with freedom of will and action and are accountable, who have been granted the freedom of belief and unbelief, of obedience and disobedience, and among them too there are the believers and the unbelievers, the obedient and the rebellious, as among human beings, and among them too there exist such groups as have believed in the Prophets sent by God and in the Divine Books, this Surah
clearly points out that the message of the Holy Prophet (peace and blessings of Allah be upon him) and the Qur'an is meant both for men and for jinn and that his Prophethood is not restricted to human beings alone.</p>
<p>Although in the beginning of the Surah the address is directed only to human beings, for to them only belongs the vicegerency" of the earth, among them only have the Messengers of Allah been raised, and in their tongues only have the Divine Books been revealed, yet from verse 13 onward both the men and the jinn have been addressed and one and the same invitation has been extended to both.</p>
<p>The themes of the Surah have been couched in brief sentences in a specific sequence:</p>
<p>In vv. 1-4 it has been stated that the teaching of the Qur'an is from Allah Almighty and it is the very demand of His mercy that He should provide guidance to mankind through this teaching, for it is He Who has created man as a rational and intelligent being.</p>
<p>In vv. 5-6 it has been said that the whole system of the Universe is functioning under Allah's Sovereignty and everything in the earth and heavens is subject to His Command alone.</p>
<p>In vv. 7-9 another important truth that has been expressed is that Allah has established the entire system of the Universe precisely and equitably on justice, and the nature of this system requires that those who dwell in it also should adhere to justice within the bounds of their authority and should not disturb the balance.</p>
<p>In vv. 10-25 besides mentioning the wonders and excellences of Allah's might, references have been made to His those bounties from which the jinn and men are deriving benefit.</p>
<p>In vv.26-30 both the men and the jinn have been reminded of the truths that in this Universe no one except One God is immortal and imperishable, and there is none, from the lowest to the highest, who does not stand in need of God for his survival and other requirements. Whatever is happening here, from the earth to the heavens, is happening under His administration and control.</p>
<p>In vv. 31-36 both the groups have been warned that the time is fast approaching when they will be called to account, which they will not be able to avoid, for God's Kingdom is encircling them from every side; it is not in their power to flee it; if they are involved in the misunderstanding that they can, they may try to do so.</p>
<p>In vv. 37-38 it has been said that this accountability will be held on the Day of Resurrection.</p>
<p>In vv. 39-45 the evil end of the guilty ones, from among men and jinn, who have been disobeying Allah in the world has been mentioned.</p>
<p>And from verse 46 to the end of the Surah mention has been made of those rewards and blessings which will be granted to the righteous men and jinn who have led pious lives in the world and lived with a clear understanding that they will have to appear before their Lord one day and render an account of their deeds and actions.</p>
<p>This whole discourse is couched in oratorical language. It is a spirited and eloquent address in the course of which after mentioning each of the wonders of Allah's great power, and each of the blessings bestowed by Him, and each of the manifestations of His Sovereignty and dominion, and each of the details of His punishment and rewards, the jinn and men have been over and over again questioned: "Which then of the bounties and favors of your Lord will you deny ?" Below we shall explain that <em>alaa</em> is a word with many shades of meaning, which has been used in different senses at different places in this discourse, and this question to the the jinn and men bears its own special meaning at every place according to the context.</p>
`
