export default `
 <h2>Name</h2>
<p>This Surah takes its name from vv. 136, 138 and 139 in which some superstitious beliefs of the idolatrous Arabs concerning the lawfulness of some cattle (<em>an\`am</em>) and the unlawfulness of some others have been refuted.</p>
<h2>Period of Revelation</h2>
<p>According to a tradition of Ibn Abbas, the whole of the Surah was revealed at one sitting at Makkah. Asma, a daughter of Yazid and a first cousin of Hadrat Mu'az-bin Jabl, says, "During the revelation of this Surah, the Holy Prophet was riding on a she-camel and I was holding her nose-string. The she-camel began to feel the weight so heavily that it seemed as if her bones would break under it." We also learn from other traditions that the Holy Prophet dictated the whole of the Surah the same night that it was revealed.</p>
<p>Its subject-matter clearly shows that it must have been revealed during the last year of the Holy Prophet's life at Makkah. The tradition of Asma, daughter of Yazid, also confirms this. As she belonged to the <em>Ansar</em> and embraced Islam after the migration of the Holy Prophet to Yathrib, her visit to the Holy Prophet at Makkah must have taken place during the last year of his life there. For before this, his relations with those people were not so intimate that a woman from there might have come to visit him at Makkah.</p>
<h2>Occasion of Revelation</h2>
<p>After determining the period of its revelation, it is easier to visualize the background of the Surah. Twelve years had passed since the Holy Prophet had been inviting the people to Islam. The antagonism and persecution by the Quraish had become most savage and brutal, and the majority of the Muslims had to leave their homes and migrate to Habash (Abyssinia). Above all, the two great supporters of the Holy Prophet. Abu Talib and Hadrat Khadijah, were no more to help and give strength to him. Thus he was deprived of all the worldly support. But in spite of this, he carried on his mission in the teeth of opposition. As a result of this, on the one hand, all the good people of Makkah and the surrounding clans gradually began to accept Islam ; on the other hand, the community as a whole, was bent upon obduracy and rejection. Therefore, if anyone showed any inclination towards Islam, he was subjected to taunts and derision, physical violence and social boycott. It was in these dark
circumstances that a ray of hope gleamed from Yathrib, where Islam began to spread freely by the efforts of some influential people of Aus and Khazraj, who had embraced Islam at Makkah. This was a humble beginning in the march of Islam towards success and none could foresee at that time the great potentialities that lay hidden in it. For, to a casual observer, it appeared at that time as if Islam was merely a weak movement it had no material backing except the meager support of the Prophet's own family and of the few poor adherents of the Movement. Obviously the latter could not give much help because they themselves had been cast out by their own people who had become their enemies and were persecuting them.</p>
<h2>Topics</h2>
<p>These were the conditions, when this discourse was revealed. The main topics dealt with in this discourse may be divided under seven headings:</p>
<ol>
  <li>
    <p>Refutation of <em>shirk</em> and invitation to the creed of <em>Tauhid</em>.</p>
  </li>
  <li>
    <p>Enunciation of the doctrine of the "Life-after- death." and refutation of the wrong notion that there was nothing beyond this worldly life.</p>
  </li>
  <li>
    <p>Refutation of the prevalent superstitions.</p>
  </li>
  <li>
    <p>Enunciation of the fundamental moral principles for the building up of the Islamic Society.</p>
  </li>
  <li>
    <p>Answers to the objections raised against the person of the Holy Prophet and his mission.</p>
  </li>
  <li>
    <p>Comfort and encouragement to the Holy Prophet and his followers who were at, that time in a state of anxiety and despondency because of the apparent failure of the mission.</p>
  </li>
  <li>
    <p>Admonition, warning and threats to the disbelievers and opponents to give up their apathy and haughtiness. It must, however, be noted that the above topics have not been dealt with one by one under separate headings, but the discourse goes on as a continuous whole and these topics come under discussion over and over again in new and different ways.</p>
  </li>
</ol>
<h2>The Background of Makki Surahs</h2>
<p>As this is the first long Makki Surah in the order of the compilation of the Quran, it will be useful to explain the historical background of Makki Surahs in general, so that the reader may easily understand the Makki Surahs and our references to its different stages in connection with our commentary on them.</p>
<p>First of all, it should be noted that comparatively very little material is available in regard to the background of the revelation of Makki Surahs whereas the period of the revelation of all the Madani Surahs is known or can be determined with a little effort. There are authentic traditions even in regard to the occasions of the revelation of the majority of the verses. On the other hand, we do not have such detailed information regarding the Makki Surahs. There are only a few Surahs and verses which have authentic traditions concerning the time and occasion of their revelation. This is because the history of the Makki period had not been compiled in such detail as that of the Madani period. Therefore we have to depend on the internal evidence of these Surahs for determining the period of their revelation: for example, the topics they discuss, their subject. matter, their style and the direct or indirect references to the events and the occasions of their revelation. Thus it is
obvious that with the help of such evidence as this, we cannot say with precision that such and such Surah or verse was revealed on such and such an occasion. The most we can do is to compare the internal evidence of a Surah with the events of the life of the Holy Prophet at Makkah, and then come to a more or less correct conclusion as to what particular stage a certain Surah belongs.</p>
<p>If we keep the above things in view, the history of the mission of the Holy Prophet at Makkah can be divided into four stages.</p>
<p>The first stage began with his appointment as a Messenger and ended with the proclamation of Prophethood three years later. During this period the Message was given secretly to some selected persons only, but the common people of Makkah were not aware of it.</p>
<p>The second stage lasted for two years after the proclamation of his Prophethood. It began with opposition by individuals: then by and by, it took the shape of antagonism, ridicule, derision,, accusation, abuse, and false propaganda then gangs were formed to persecute those Muslims who were comparatively poor, weak' and helpless.</p>
<p>The third stage lasted for about six years from the beginning of the persecution to the death of Abu Talib and Hadrat Khadijah in the tenth year of Prophethood. During this period, the persecution of the Muslims became' so savage and brutal that many of them were forced to migrate to Habash. Social and economic boycott was applied against the Holy Prophet and the members of his family, and those Muslims who continued to stay in Makkah were forced to take refuge in Shi'b-i-A'bi Talib which was besieged.</p>
<p>The fourth stage lasted for about three years from the tenth to the thirteenth year of Prophethood. This was a period of hard trials and grievous sufferings for the Holy Prophet and his followers. Life had become unendurable at Makkah and there appeared to be no place of refuge even outside it. So much so that when the Holy Prophet went to Ta'if, it offered no shelter or protection. Besides this, on the occasion of Haj, he would appeal to each and every Arab clan to accept his invitation to Islam but met with blank refusal from every quarter. At the same time, the people of Makkah were holding counsels' to get rid of him by killing or imprisoning or banishing him from their city. It was at that most critical time that Allah opened for Islam the hearts of the <em>Ansar</em> of Yathrab where he migrated at their invitation.</p>
<p>Now that we have divided the life of the Holy Prophet at Makkah into four stages, it has become easier for us to tell, as far as possible, the particular stage in which a certain Makki Surah was revealed. This is because the Surahs belonging to a particular stage can be distinguished from those of the other stages with the help of their subject matter and style. Besides this, they also contain such references as throw light on the circumstances and events that form the background of their revelation. In the succeeding Makki Surahs, we will determine on the basis of the distinctive features of each stage, and point out in the Preface, the particular stage in which a certain Makki Surah was revealed.</p>
<h2>Subject: Islamic Creed.</h2>
<p>This Surah mainly discusses the different aspects of the major articles of the Islamic Creed: <em>Tauhid</em>, Life-after-death, Prophethood and their practical application to human life. Side by side with this, it refutes the erroneous beliefs of the "opponents and answers their objections, warns and admonishes them and comforts the Holy Prophet and his followers, who were then suffering from persecution.</p>
<p>Of course, these themes have not been dealt with under separate heads but have been blended in an excellent manner.</p>
<h3>Topics and their Interconnection</h3>
<p>These verses are of introductory and admonitory nature. The disbelievers have been warned that if they do not accept the Islamic Creed and follow the 'Light' shown by the Revelation from the All-Knowing and All-Powerful Allah, they would go to the same doom as the former disbelievers did. Their arguments for rejecting the Prophet and the Revelation sent down to him have been refuted and a warning has been given to them that they should not be deluded by the respite that is being granted to them. <strong>1 - 12</strong></p>
<p>These verses inculcate <em>Tauhid</em>, and refute <em>shirk</em> which is the greatest obstacle in the way of its acceptance. <strong>13 - 24</strong></p>
<p>In these verses, a graphic scene of the life in the Hereafter has been depicted in order to warn the disbelievers of the consequences of the rejection of the Articles of Faith. <strong>25 - 32</strong></p>
<p>Prophethood is the main theme which has been discussed from the point of view of the Holy Prophet, his Mission, the limitations of his powers, the attitude towards his followers and also from the point of view of the disbelievers. <strong>33 - 73</strong></p>
<p>In continuation of the same theme, the story of Prophet Abraham has been related to bring home to the pagan Arabs that the Mission of Prophet Muhammad, which they were opposing, was the same as that of Prophet Abraham (Allah's peace be upon them). This line of argument was adopted because they considered themselves to be his followers, especially the Quraish who were proud of being his descendants as well. <strong>74 - 90</strong></p>
<p>Another proof of his Prophethood is the Book, which has been sent down to him by Allah, for its teachings show the right guidance in regard to creed and practice. <strong>91 - 108</strong></p>
<p>Divine restrictions have been contrasted with the superstitious restrictions of the pagan Arabs in order to show the striking differences between the two and thus prove the Quran to be a Revealed Book. <strong>109 - 154</strong></p>
<p>The Jews, who were criticized in vv. 144 - 147 along with the pagan Arabs, have been urged to compare the teachings of the Quran with those of the Torah so that they might recognize their similarity and give up their lame excuses against it, and adopt its Guidance to escape the retribution on the Day of Resurrection. <strong>155 - 160</strong></p>
<p>This is the conclusion of the discourse: the Holy Prophet has been instructed in a beautiful and forceful manner to proclaim fearlessly the articles of the Islamic Creed and their implications. <strong>161 - 165</strong></p>;
`
