export default `
 <h2>Name</h2>
<p>In verse 10 of this Surah it has been enjoined that the women who emigrate to <em>dar al-Islam</em> (the Islamic State) and claim to be Muslims, should be examined hence the title <em>Al-Mumtahinah</em>. The word is pronounced both as <em>mumtahinah</em> and as <em>mumtahanah</em>, the meaning according to the first pronunciation being "the Surah which examines", and according to the second, "the woman who is examined."</p>
<h2>Period of Revelation</h2>
<p>The Surah deals with two incidents, the time of the occurrence of which is well known historically. The first relates to Hadrat Hatib bin Abz Balta'a, who, a little before the conquest of Makkah, had sent a secret letter to the Quraish chiefs informing them of the Holy Prophet's intention to attack them. The second relates to the Muslim women, who had started emigrating from Makkah to Madinah, after the conclusion of the Truce of Hudaibiyah, and the problem arose whether they also were to be returned to the disbelievers, like the Muslim men, according to the conditions of the Truce. The mention of these two things absolutely determines that this Surah came down during the interval between the Truce of Hudaibiyah and the Conquest of Makkah. Besides, there is a third thing also that has been mentioned at the end of the Surah to the effect; What should the Holy Prophet (upon whom be Allah's peace) make the women to pledge when they come to take the oath of allegiance before him as
believers?About this part also the guess is that this too was sent down some time before the conquest of Makkah, for after this conquest a large number of the Quraish women, like their men, were going to enter Islam simultaneously and had to be administered the oath of allegiance collectively.</p>
<h2>Theme and Topics</h2>
<p>This Surah has three parts;</p>
<p>The first part consists of vv. 1-9, and the concluding verse 13 also relates to it. In this strong exception has been taken to the act of Hadrat Hatib bin Abi Balta'a in that he had tried to inform the enemy of a very important war secret of the Holy Prophet (upon whom be Allah's peace) only for the sake of safe guarding his family. This would have caused great bloodshed at the conquest of Makkah had it not been made ineffective in time. It would have cost the Muslims many precious lives; many of the Quraish would have been killed, who were to render great services to Islam afterward; the gains which were to accrue from conquering Makkah peacefully would have been lost, and all these serious losses would have resulted only because one of the Muslims had wanted to safeguard his family from the dangers of war. Administering a severe warning at this blunder Allah has taught the believers the lesson that no believer should, under any circumstances and for any motive, have relations
of love and friendship with the disbelievers, who are actively hostile to Islam, and a believer should refrain from everything which might be helpful to them in the conflict between Islam and disbelief. However, there is no harm in dealing kindly and justly with those disbelievers, who may not be practically engaged in hostile activities against Islam and persecution of the Muslims.</p>
<p>The second part consists of vv. 10-11. In this a social problem has been settled, which was agitating the minds at that time. There were many Muslim women in Makkah, whose husbands were pagans, but they were emigrating and reaching Madinah somehow. Likewise, there were many Muslim men in Madinah, whose wives were pagans and had been left behind in Makkah. The question arose whether the marriage bond between them continued to be valid or not. Allah settled this problem for ever, saying that the pagan husband is not lawful for the Muslim women, nor the pagan wife lawful for the Muslim husband. This decision leads to very important legal consequences, which we shall explain in our notes below.</p>
<p>The third section consists of verse 12, in which the Holy Prophet (upon whom be Allah's peace) has been instructed to ask the women who accept Islam to pledge that they would refrain from the major evils that were prevalent among the womenfolk of the pre-Islamic Arab society, and to promise that they would henceforth follow the ways of goodness which the Messenger of Allah may enjoin.</p>;
`
