export default `
 <h2>Name</h2>
<p>The Surah derived its name from the words <em>lima tuharrimu</em> of the very first verse. This too is not a title of its subject matter, but the name implies that it is the Surah in which the incident of <em>tahrim</em> (prohibition, forbiddance) has been mentioned.</p>
<h2>Period of Revelation</h2>
<p>In connection with the incident of <em>tahrim</em> referred to in this Surah, the traditions of the <em>Hadith</em> mention two ladies who were among the wives of the Holy Prophet (upon whom be peace) at that time Hadrat Safiyyah and Hadrat Mariyah Qibtiyyah. The former (i. e. Hadrat Safiyyah) was taken to wife by the Holy Prophet after the conquest of Khaiber, and Khaiber was conquered, as has been unanimously reported, in A. H. 7. The other lady, Hadrat Mariyah, had been presented to the Holy Prophet by Muqawqis, the ruler of Egypt, in A. H. 7 and she had borne him his son, Ibrahim, in Dhil-Hijjah, A. H. 8.These historical events almost precisely determine that this Surah was sent down some time during A.H. 7 or A. H 8.</p>
<h2>Theme and Topics</h2>
<p>This is a very important Surah in which light has been thrown on some questions of grave significance with reference to some incidents concerning the wives of the Holy Prophet (upon whom be Allah's peace).</p>
<p>First, that the powers to prescribe the bounds of the lawful and the unlawful, the permissible and the forbidden, are entirely and absolutely in the hand of Allah and nothing has been delegated even to the Prophet of Allah himself, not to speak of any other man. The Prophet as such can declare something lawful or unlawful only if he receives an inspiration from Allah to do so whether that inspiration is embodied in the Qur'an, or imparted to, him secretly. However, even the Prophet is not authorized to declare anything made permissible by Allah unlawful by himself, much less to say of another man.</p>
<p>Second, that in any society the position of a Prophet is very delicate. A minor incident experienced by an ordinary man in his life may not be of any consequence, but it assumes the status of law when experienced by a Prophet. That is why the lives of the Prophets have been kept under close supervision by Allah so that none of their acts, not even a most trivial one, may deviate from Divine Will. Whenever such an act has emanated from a Prophet, it was rectified and rectified immediately so that the Islamic law and its principles should reach the people in their absolute purity not only through the Divine Book but also through the excellent example of the Prophet, and they should include nothing which may be in disagreement with Divine Will,</p>
<p>Thirdly, and this automatically follows from the above mentioned point, that when the Holy Prophet (upon whom be peace) was checked on a minor thing, which was not only corrected but also recorded, it gives us complete satisfaction that whatever actions and commands and instructions we now find in the pure life of the Holy Prophet concerning which there is nothing on record in the nature of criticism or correction from Allah, they are wholly based on truth, are in complete conformity with Divine Will and we can draw guidance from them with full confidence and peace of mind.</p>
<p>The fourth thing that we learn from this discourse is that about the Holy Messenger himself, whose reverence and respect Allah Himself has enjoined as a necessary part of the Faith of His servants, it has been stated in this Surah that once during his sacred life he made a thing declared lawful by Allah unlawful for himself only to please his wives; then Allah has severely reproved for their errors those very wives of the Holy Prophet, whom He Himself has declared as mothers of the faithful and worthy of the highest esteem and honor by them. Then, this criticism of the Prophet and the administration of the warning to the wives also has not been made secretly but included in the Book, which the entire <em>Ummah</em> has to read and recite for ever. Obviously, neither the intention of making mention of it in the Book of Allah was, nor it could be, that Allah wanted to degrade His Messenger and the mothers of the faithful in the eyes of the believers; and this also is obvious that
no Muslim has lost respect for them, in his heart after reading this Surah of the Qur'an. Now, there cannot be any other reason of mentioning this thing in the Qur'an than that Allah wants to acquaint the believers with the correct manner of reverence for their great personalities. The Prophet is a Prophet, not God, that he may commit no error. Respect of the Prophet has not been enjoined because he is infallible, but because he is a perfect representative of Divine Will, and Allah has not permitted any of his errors to pass by unnoticed. This gives us the satisfaction that the noble pattern of life left by the Prophet wholly and fully represents the will of Allah. Likewise, the Companions of the holy wives of the Prophet, were human, not angels or super men. They could commit mistakes. Whatever ranks they achieved became possible only because the guidance given by Allah and the training imparted by Allah's Messenger had moulded them into the finest models. Whatever esteem and
reverence they deserve is on this very basis and not on the presumption that they were infallible. For this reason, whenever in the sacred lifetime of the Prophet (upon him be peace) the Companions or holy wives happened to commit an error due to human weakness, they were checked. Some of their errors were corrected by the Holy Prophet, as has been mentioned at many places in the <em>Hadith</em> ; some other errors were mentioned in the Qur'an and Allah Himself corrected them so that the Muslims might not form any exaggerated notion of the respect and reverence of their elders and great men, which might raise them from humanity to the position of gods and goddesses. If one studies the Quran carefully, one will see instances of this one after the other. In Surah Al-Imran, in connection with the Battle of Uhud, the Companions have been addressed and told:</p>
<p>"Allah did fulfill His promise (of help) to you : in the initial stage of the battle, it was you who were killing them by Allah's leave until you lost heart and disputed about your duty and disobeyed your leader, when Allah showed you what (the spoils) you coveted for there were among you sortie who hankered after the life of this world, and others: who cherished the life after death. Then Allah caused your retreat before the disbelievers in order to test you, but the fact is that even then Allah pardoned you, for Allah is very gracious to the believers." (v. 152).</p>
<p>In surah An-Nur, in connection with the Slander against Hadrat Aisha, the Companions were told,</p>
<p>"When you heard of it, why did not the believing men and the believing women have a good opinion of themselves, and why did they not say: this is a manifest slander?......Were it not for Allah's grace and mercy towards you in this world and in the Hereafter, a painful scourge would have visited you because of the slander. (Just consider) when you passed this lie on from one tongue to the other and uttered with your mouths that of which you had no knowledge. You took it as a trifling matter whereas it was a grave offense in the sight of Allah. Why did you not, as soon as you heard of it, say 'It is not proper for us to utter such a thing? Glory be to Allah! This is a great slander'."Allah admonishes you that in future you should never repeat anything like this, if you are true believers." (vv. 12-I7).</p>
<p>In surah Al-Ahzab, the holy wives have been addressed thus: "O Prophet, say to your wives If you seek the world and its adornments, come, I shall give you of these and send you off in a good way. But if you seek Allah and His Messenger and the abode of the Hereafter, you should rest assured that Allah has prepared a great reward for those of you, who do good." (vv. 28-29).</p>
<p>In Surah Jumu'ah about the Companions it was said:</p>
<p>"And when they saw some merchandise and amusement they broke off to it and left you (O Prophet) standing (in the course of the Sermon). Say to them : that which is with Allah is far better than amusement and merchandise, and Allah is the best of all providers." (v. 11).</p>
<p>In Surah Al-Mumtahinah, Hadrat Hatib bin Abi Balta'ah, a Companion who had fought at Badr, was severely taken to task because he had sent secret information to the disbelieving Quraish about the Holy Prophet's invasion before the conquest of Makkah.</p>
<p>All these instances are found in the Qur'an itself, in the same Qur'an in which Allah Himself has paid tribute to the Companions and the holy wives for their great merits, and granted them the certificate of His good pleasure, saying: "Allah became well pleased with them and they with Allah." It was this same moderate and balanced teaching of the reverence and esteem of the great men, which saved the Muslims from falling into the pit of man worship in which the Jews and the Christians fell, and it is a result of the same that in the books that the eminent followers of the <em>Sunnah</em> have compiled on the subjects of the <em>Hadith</em>, Commentary of the Qur'an and History, not only have the excellences and great merits of the Companions and holy wives and other illustrious men been mentioned, but also no hesitance has been shown in mentioning the incidents relating to their weaknesses, errors and mistakes, whereas those scholars were more appreciative of the merits and
excellences of the great men and understood the bounds and limits of reverence better than those who claim to be the upholders of reverence for the elders today.</p>
<p>The fifth thing that has been explicitly mentioned in this Surah is that Allah's Religion is absolutely fair and just. It has for every person just that of which he becomes worthy on the basis of his faith and works. No relationship or connection even with the most righteous person can be beneficial for him in any way and no relationship or connection with the most evil and wicked person can be harmful for him in any way. In this connection three kinds of women have been cited as examples before the holy wives in particular. One example is of the wives of the Prophets Noah and Lot, who, if they had believed and cooperated with their illustrious husbands, would have occupied the same rank and position in the Muslim community. which is enjoyed by the wives of the Holy Prophet Muhammad (upon whom be Allah's peace and blessings). But since they were disbelievers, their being the wives of the Prophets did not help them and they fell into Hell. The second example is of the wife of
Pharaoh, who in spite of being the wife of a staunch enemy of God believed and chose a path of action separate from that followed by the Pharaoh's people, and her being the wife of a staunch disbeliever did not cause her any harm, and Allah made her worthy of Paradise. The third example is of Hadrat Maryam (Mary) (peace be upon her), who attained to the high rank because she submitted to the severe test to which Allah had decided to put her. Apart from Mary no other chaste and righteous girl in the world ever has been put to such a hard test that in spite of being unmarried, she might have been made pregnant miraculously by Allah's command and informed what service her Lord willed to take from her. When Hadrat Maryam accepted this decision, and agreed to bear, like a true believer, everything that she inevitably had to bear in order to fulfill Allah's will, then did Allah exalt her to the noble rank of <em>Sayyidatu an-nisa' fil- Jannah</em> : "Leader of the women in Paradise"
(Musnad Ahmad).</p>
<p>Besides, another truth that we learn from this Surah is that the Holy Prophet (upon whom be peace) did not receive from Allah only that knowledge which is included and recorded in the Qur'an, but he was given information about other things also by revelation, which has not been recorded in the Qur'an. Its clear proof is verse 3 of this Surah. In it we are told that the Holy Prophet (upon whom be peace) confided a secret to one of his wives, and she told it to another. Allah informed the Holy Prophet of this secret. Then, when the Holy Prophet warned his particular wife on the mistake of disclosure and she said:"Who has informed you of this mistake of mine7" he replied: "I have been informed of it by Him Who knows everything and is All Aware." Now, the question is where in the Qur'an is the verse in which Allah has said "O Prophet, the secret that you had confided to one of your wives, has been disclosed by her to another person, or to so and so?If there is no such verse in the
Qur'an, and obviously there is none, this is an express proof of the fact that revelation descended on the Holy Prophet besides the Qur'an as well. This refutes the claim of the deniers of <em>Hadith</em>, who allege that nothing was sent down to the Holy Prophet (upon whom be peace) apart from the Qur'an.</p>
`
