export default `
 <h2>Name</h2>
<p>The Surah takes its name <em>al-Mulk</em> from the very first sentence.</p>
<h2>Period of Revelation</h2>
<p>It could not be known from any authentic tradition when this Surah was revealed, but the subject matter and the style indicate that it is one of the earliest Surahs to be revealed at Makkah.</p>
<h2>Theme and Subject Matter</h2>
<p>In this surah, on the one hand, the teachings of Islam have been introduced briefly, and, on the other, the people living in heedlessness have been aroused from their slumber in a most effective way. A characteristic of the earliest surahs of the Makkan period is that they present the entire teachings of Islam and the object of the Holy Prophet's mission, not in detail, but briefly, so that they are assimilated by the people easily. Moreover, they are particularly directed to make the people shun heedlessness, to make them think, and to arouse their dormant conscience.</p>
<p>In the first five verses man has been made to realize that the universe in which he lives is a most well organized and fortified Kingdom in which he cannot detect any fault, any weakness or flaw, how ever hard he may try to probe. This Kingdom has been brought from nothing into existence by Allah Almighty Himself and All the powers of controlling, administering and ruling it are also entirely in Allah's hand and His power is infinite. Besides, man has also been told that in this wise system he has not been created without a purpose, but he has been sent here for a test and in this test he can succeed only by his righteous deeds and conduct.</p>
<p>In vv. 6-11, dreadful consequences of disbelief which will appear in the Hereafter have been mentioned, and the people told that Allah, by sending His Prophets, has warned them of these consequences in this very world, as if to say "Now, if you do not believe in what the Prophets say and correct your attitude and behavior accordingly, in the Hereafter you will yourself have to admit that you really deserved the punishment that was being meted out to you."</p>
<p>In vv. 12-l4, the truth that has been impressed on the minds is that the Creator cannot be unaware of His creation, as if to say: "He is aware of each open and hidden secret of yours, even of the innermost ideas of your hearts. Hence, the right basis of morality is that man should avoid evil, fearing the accountability of the unseen God, whether in the world there is a power to take him to task for this or not, and whether in the world there is a possibility of being harmed by such a power or not. Those who adopt such a conduct in the world alone will deserve forgiveness and a rich reward in the Hereafter."</p>
<p>In vv. 15-23, making allusions, one after the other to those common truths of daily occurrence, which man does not regard as worthy of much attention, he has been invited to consider them seriously. It has been said: "Look: the earth on which you move about with full satisfaction and peace of mind, and from which you obtain your sustenance has been subdued for you by Allah; otherwise this earth might at any time start shaking suddenly so as to cause your destruction, or a typhoon might occur, which may annihilate you completely. Look at the birds that fly above you; it is only Allah Who is sustaining them in the air. Look at your own means and resources: if Allah wills to inflict you with a scourge, none can save you from it; and if Allah wills to close the doors of sustenance on you, none can open them for you. These things are there to make you aware of the truth, but you see them like animals, which are unable to draw conclusions from observations, and you do not use your
sight, hearing and minds which Allah has bestowed on you as men; that is why you do not see the right way."</p>
<p>In vv. 24-27, it has been said: "You have ultimately to appear before your God in any case. It is not for the Prophet to tell you the exact time and date of the event. His only duty is to warn you beforehand of its inevitable occurrence. Today you do not listen to him and demand that he should cause the event to occur and appear prematurely before you; but when it does occur, and you see it with your own eyes, you will then be astounded. Then, it will be said to you "This is the very thing you were calling to be hastened."</p>
<p>In vv. 28-29 replies have been given to what the disbelievers of Makkah said against the Holy Prophet (upon whom be peace) and his Companions. They cursed the Holy Prophet and prayed for his and the believers destruction. To this it has been said: "Whether those who call you to the right way are destroyed, or shown mercy by Allah, how will their fate change your destiny? You should look after yourselves and consider who would save you if you were overtaken by the scourge of God?You regard those who believe in God and put their trust in Him as the misguided. A time will come when it will become evident as to who was misguided in actual truth.</p>
<p>In conclusion, the people have been asked this question and left to ponder over it "If the water which has come out from the earth at some place in the desert or hill country of Arabia and upon which depends your whole life activity, should sink and vanish underground, who beside Allah can restore to you this life giving water?"</p>
`
