export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>al-Haaqqah</em> with which it opens.</p>
<h2>Period of Revelation</h2>
<p>This too is one of the earliest surahs to be revealed at Makkah. Its subject matter shows that it was sent down at the time when opposition to the Holy Prophet (upon whom be peace) had started but had not yet become tyrannical. Musnad Ahmad contains a tradition from Hadrat Umar, saying: "Before embracing Islam one day I came out of my house with a view to causing trouble to the Holy Prophet, but he had entered the <em>Masjid al-Haram</em> before me. When I arrived I found that he was reciting surah Al-Haaqqah in the Prayer. I stood behind him and listened. As he recited the Qur'an I wondered at its literary charm and beauty. Then suddenly an idea came to my mind that he must be a poet as the Quraish alleged. Just at that moment he recited the words: "This is the Word of an honorable Messenger: it is not the word of a poet." I said to myself: Then, he must be a soothsayer, if not a poet. Thereupon be recited the words:"Nor is it the word of a soothsayer: little it is that you
reflect. It is a Revelation from the Lord and Sustainer of the worlds. On hearing this Islam entered deep into my heart." This tradition of Hadrat Umar shows that this surah had been sent down long before his acceptance of Islam, for even after this event he did not believe for a long time, and he continued to be influenced in favor of Islam by different incidents from time to time, till at last in the house of his own sister he came by the experience that made him surrender and submit to the Faith completely. (For details, see introduction to surah Maryam and Introduction to surah Al-Waqiah).</p>
<h2>Theme and Subject Matter</h2>
<p>The first section (vv. 1-37) is about the Hereafter and the second (vv. 38-52) about the Qur'an's being a revelation from Allah and the Holy Prophet's being a true Messenger of Allah.</p>
<p>The first section opens with the assertion that the coming of the Resurrection and the occurrence of the Hereafter is a truth which has to take place inevitably. Then in vv. 4-12, it has been stated that the communities that denied the Hereafter in the past became worthy of Allah's scourge ultimately. In vv. 13-17 the occurrence of Resurrection has been depicted. In vv. 18-37 the real object for which Allah has destined a second life for mankind after the present worldly life has been enunciated. In it we are told that on that Day all men shall appear in the Court of their Lord, where no secret of theirs shall remain hidden each man's record will be placed in his hand. Those who had spent lives in the world with the realization that one day they would have to render an account of their deeds before their Lord, and who had worked righteously in the world and provided beforehand for their well being in the Hereafter, will rejoice when they see that they have been acquitted and
blessed with the eternal bliss of Paradise. On the contrary, those who neither recognized the rights of Allah, nor discharged the rights of men, will have no one to save them from the punishment of Allah, and they will be cast into Hell.</p>
<p>In the second section (vv. 38-52) the disbelievers of Makkah have been addressed and told: "You think this Qur'an is the word of a poet or soothsayer, whereas it is a Revelation sent dawn by Allah, which is being presented by the noble Messengers. The Messenger by himself had no power to increase or decrease a word in it. If he forges something of his own composition into it, We will cut off his neck-vein (or heart- vein). For this is the Truth absolute and pure: and those who give it a lie, will have ultimately to regret and repent.</p>
`
