export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>dhil Ma'arij</em> in verse 3.</p>
<h2>Period of Revelation</h2>
<p>The subject matter bears evidence that this Surah too was sent down in conditions closely resembling those under which Surah Al Haaqqah was sent down.</p>
<h2>Theme and Subject Matter</h2>
<p>It admonishes and gives warning to the disbelievers who made fun of the news about Resurrection and the Hereafter, and Hell and Heaven, and challenged the Holy Prophet (upon whom be peace) to cause Resurrection with which he threatened them to take place if what he said was true and they had become worthy of the punishment in Hell by denying it. The whole Surah is meant to answer this denial.</p>
<p>The Surah opens with words to the effect:"A demander has demanded a torment, the torment which must befall the deniers; and when it takes place, there will be none to prevent it, but it will take place at its own appointed time. Allah has His own way of doing things, but He is not unjust. Therefore, have patience, O Prophet, at what they say. They think it is far off, but We see it as near at hand."</p>
<p>Then it is said:"Resurrection, which they desire to be hastened out of jest and fun, is terrible, and when it comes, it will cause great distress to the culprits. At that time they will even be prepared to give away their wives and children and their nearest kinsfolk in ransom to escape the punishment, but they will not be able to escape it.</p>
<p>Then the people have been warned to the effect; "On that Day the destinies of men will be decided strictly on the basis of their belief and their conduct. Those who turn away from the Truth in the world and amass wealth and withhold it from the needy, will be doomed to Hell; and those who fear the punishment of God here, believe in the Hereafter, keep up the Prayer, discharge the rights of the needy out of their wealth, strictly avoid immoral and wicked deeds, practice honesty in all their dealings, fulfill their pledges and trust and bear true witness, will have a place of honor in Paradise"</p>
<p>In conclusion, the disbelievers of Makkah who rushed in upon the Holy Prophet (upon whom be peace) from every side as soon as they saw him, in order to make fun of him, have been warned to the effect: "If you do not believe, Allah will replace you by other people who will be better than you", and the Holy Prophet (upon whom be peace) has been consoled, so as to say: "Do not take to heart their mockery and jesting; leave them to indulge in their idle talk and foolish conduct if they are bent upon experiencing the disgrace and humiliation of the Resurrection; they will themselves see their evil end."'</p>;
`
