export default `
 <h2>Name</h2>
<p>"Nuh" is the name of this Surah as well as the title of its subject matter, for in it, from beginning to the end, the story of the Prophet Noah has been related.</p>
<h2>Period of Revelation</h2>
<p>This also is one of the earliest Surahs to be revealed at Makkah, but the internal evidence of its subject matter shows that it was sent down in the period when opposition to the Holy Prophet's message of Islam by the disbelievers of Makkah had grown very strong and active.</p>
<h2>Theme and Subject</h2>
<p>In this surah the story of the Prophet Noah has not been related only for the sake of story telling, but its object is to warn the disbelievers of Makkah, so as to say:"You, O people of Makkah, are adopting towards Muhammad (upon whom be Allah's peace and blessings) the same attitude as the people of the Prophet Noah had adopted towards him; if you do not change this attitude, you too would meet with the same end." This had not been said in so many words anywhere in the Surah, but in the background of the conditions under which this story was narrated to the people of Makkah, this subject itself became obvious.</p>
<p>Vv. 2-4 briefly explain how he began his mission and what he preached.</p>
<p>Then after suffering hardships and troubles in the way of preaching his mission for ages the report that he made to his Lord has been given in vv. 5-20. In it he states how he had been trying to bring his people to the right path and how his people had stubbornly opposed him.</p>
<p>After this, the Prophet Noah's final submission has been recorded in vv. 21-24, in which he prays to his Lord, saying: "These people have rejected my invitation: they are blindly following their chiefs, who have devised a tremendous plot of deceit and cunning. Time now has come when these people should be deprived of every grace to accept guidance." This was not an expression of impatience by the Prophet Noah, but when after having preached his message under extremely trying circumstances for centuries be became utterly disappointed with his people, he formed the opinion that no chance whatever was left of their coming to the right path. His this opinion fully conformed to Allah's own decision. Thus, in the next verse (25), it has been said: "The torment of Allah descended on those people because of their misdeeds."</p>
<p>In the concluding verse, the Prophet Noah's supplication that he made to his Lord, right at the time the torment descended, has been recorded. In it he prays for his own and for all the believers' forgiveness, and makes a submission to Allah to the effect: "Do not leave any of the disbelievers alive on the earth, for they have become utterly devoid of every good: they will not beget any but disbelieving and wicked descendants."</p>
<p>While studying this Surah one should keep in view the details of the Prophet Noah's story which have been given in the Qur'an above. For this see Al-Araf: 59-64 Yunus: 71,73, Hud: 25-49, Al-Mu'minun: 23-31, Ash- Shua'ra: 105-122, Al-Ankabut: 14,15, As-Saaffat: 75-82, Al-Qamar: 9-16.</p>
`
