export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>al-muddaththir</em> in the first verse. This also is only a name, not a title of its subject matter.</p>
<h2>Period of Revelation</h2>
<p>The first seven verses of this Surah belong to the earliest period at Makkah. Even according to some traditions which have been related in Bukhari, Muslim, Tirmidhi, Musnad Ahmad, etc., on the authority of Hadrat Jabir bin Abdullah, these are the very earliest verses of the Qur'an to be revealed to the Holy Prophet (upon whoa be peace). But the Muslim <em>Ummah</em> almost unanimously agreed that the earliest Revelation to the Holy Prophet (upon whom be peace) consisted of the first five verses of Surah Al-Alaq(XCVI) However, what is established by authentic traditions is that after this first Revelation, no Revelation came down to the Holy Prophet (upon whom be peace) for quite some time. Then, when it was resumed, it started with theme verses of Surah Al- Muddaththir. Imam Zuhri has given the following details of it:</p>
<p>"Revelation to the Holy Prophet remained suspended for quite some time, and it was such a period of deep grief and distress for him that he started going early to the tops of the mountains to throw himself down from them. But whenever he stood on the edge of a peak, the Angel Gabriel would appear and tell him that he was Allah's Prophet. This would console him and restore to him full peace of mind." (Ibn Jarir).</p>
<p>After this Imam Zuhri relates the following tradition on the authority of Hadrat Jabir bin Abdullah:</p>
<p>"The Ho]y Messenger of Allah describing the period of <em>falrat al-wahi</em> (break in revelation) said: One day when I was passing on the way, I suddenly heard a call from heaven. I raised my head and saw that the same Angel who had visited me in the Cave of Hira was sitting on a throne between heaven and earth. This struck terror in my heart, and reaching home quickly, I said: 'Cover me up, cover me up'. So the people of the house covered me up with a quilt (or blanket). At that time Allah sent down the Revelation: <em>Ya ayyuhal-Muddaththiru..</em>. From then on revelation became intense and continuous." (Bukhari, Muslim Musnad Ahmad, Ibn Jarir).</p>
<p>The rest of the Surah (vv. 8-56) was revealed when the first Hajj season came after public preaching of Islam had begun in Makkah. This has been fully well described in the <em>Sirah</em> by Ibn Hisham and we shall cite it below.</p>
<h2>Theme and Subject Matter</h2>
<p>As has been explained above, the earliest Revelation to the Holy Prophet (upon whom be peace) consisted of the first five verses of Surah Al-Alaq, in which it had been Said: "Read (O Prophet), in the name of your Lord, Who created: created man from a clot of congealed blood. Read: and your Lord is Most Generous, Who taught knowledge by the pen, taught man what he did not know."</p>
<p>This was the first experience of Revelation met with suddenly by the Holy Prophet (upon whom be peace). in this message it was not told what great mission he had been entrusted with and what duties he had to perk form in future. He was only initiated into it and then left alone for a time so that the great strain this experience had caused should pass away and he should mentally become prepared to receive the Revelation and perform the prophetic mission in the future. After this intermission when Revelation Was resumed, the first seven verses of this Surah Were revealed:In these he Was for the first time commanded to arise and warn the people of the consequences of the way of life they were following and to proclaim the greatness of God in the world where others were being magnified without any right. Along with that he was given this instruction: The demand of the Unique mission that you have to perform, now is that your life should be pure in every respect and you should carry
out the duty of reforming your people sincerely irrespective of any worldly gain. Then, in the last sentence, he was exhorted to endure with patience, for the sake of his Lord, all the hardships and troubles that he might have to face while performing his mission.</p>
<p>In the implementation of this Divine Command when the Holy Messenger of Allah began to preach Islam and recite the Qur'anic Surahs revealed successively, the people of Makkah felt alarmed, and it provoked a great storm of opposition and hostility. A few months passed in this state until the Hajj season approached. The people of Makkah feared that if Muhammad (upon whom be Allah's peace) started visiting the caravans of the pilgrims coming from all over Arabia at their halting places and reciting the spell binding and unique Revelations of the Qur'an in their assemblies on the occasion of Hajj, his message would reach every part of Arabia and influence countless people. Therefore, the Quraish chiefs held a conference and settled that they would start a propaganda campaign against the Holy Prophet (upon whom be peace) among the pilgrims as soon as they arrived.</p>
<p>After they had agreed on this, Walid bin al-Mughirah said to the assembled people: "If you said contradictory things about Muhammad (upon whom be Allah's peace and blessings), we all would lose our trust among the people. Therefore, let us agree upon one opinion, which we should all say without dispute.</p>
<p>Some people said that they would call Muhammad (upon whom be Allah's peace and blessings) a soothsayer. Walid said: “No, by God, be is not a soothsayer. We have seen the soothsayers: what they murmur and what they utter has no remote resemblance with the Qur'an.”</p>
<p>Some other people said: “Then we say he is possessed.” Walid said: He is not a possessed one: we have seen mad and insane people; the way one talks disjointedly and behaves foolishly in that state is known to all: who would believe that what Muhammad (upon whom be peace) presented was the incoherent speech of a madman?”</p>
<p>The people said: “Then we say he is a poet.” Walid said: “No, he is not a poet, for we know poetry in all its forms, and what he presents conforms to no form of it.”</p>
<p>The people said: “Then he is a sorcerer.” Walid said: “He is no sorcerer either: we have seen sorcerers and we also know what methods they adopt for their sorcery. This also does not apply to Muhammad.”</p>
<p>Then he said: "Whichever of these things you said about Muhammad, it would be known to be a false accusation. By God, his speech is sweet, his root is deep and his branches are fruitful.” At this Abu Jahl urging on Walid said: “Your people will never be pleased with you unless you say something about Muhammad.” He said: “Let me think over it awhile.”</p>
<p>Then, after prolonged thought and consideration, he said: “The nearest thing to the truth is that you tell the Arabs that he is a sorcerer, who has brought a message by which he separates a man from his father; and from his brother, and from his wife and children, and from his family.” They all agreed on what Walid had proposed.</p>
<p>Then, according to a scheme the men of Quraish spread among the pilgrims in the Hajj season and they warned everyone they met of the sorcery of Muhammad (upon whom be peace) and of his stirring up divisions in the families by it." But the result was that by their this plan the Quraish chiefs themselves made the name of the Holy Messenger known throughout Arabia. (Ibn Hisham, pp. 288-289. That Walid had made this proposal on the insistence of Abu Jahl has been related by Ibn Jarir in his <em>Tafsir</em> on the authority of Ikrimah).</p>
<p>This same event has been reviewed and commented upon in the second section of this Surah. The sequence of its contents is as follows:</p>
<p>In vv. 8-10 the deniers of Truth have been warned, saying: "You will see the evil result of what you are doing today on the Resurrection Day."</p>
<p>In vv. 11-26, without naming Walid bin al-Mughirah, it has been told how Allah had blessed him and how inimical he proved to be to true Faith. In this connection, his mental conflict has been portrayed, telling that, on the one hand, he was fully convinced of the truth of Muhammad (upon whom be Allah's peace and blessings) and the Qur'an, but, on the other, he did not want to risk his leadership and position among his people. Therefore, not only he did not believe himself but after a long-drawn-out conflict with his conscience he also came out with the proposal that in order to restrain the people from believing the Qur'an should be branded as magic. After exposing his evil nature, it has been said: "Notwithstanding such evil inclinations and misdeeds, this person desires that he should be further blessed, whereas he has now become worthy of Hell, and never of further blessings."</p>
<p>In vv. 27-48, the dreadfulness of Hell has been depicted and it has been explained as to people of what character and morals really deserve it.</p>
<p>In vv. 49-53, the root cause of the disbelievers' aversion has been pointed out, saying: "Since they are fearless of the Hereafter, and look upon this worldly life as an end in itself, they flee from the Qur'an as though they were wild asses fleeing away from the lion: therefore, they propose unreasonable conditions for believing, whereas even if each and every condition of theirs was fulfilled, they could not advance even an inch on the way of Faith with their denial of the Hereafter."</p>
<p>In conclusion, it has been explicitly stated: Allah does not stand in need of anybody's faith that He may fulfill his conditions. The Qur'an is an admonition that has been presented before the people openly; now whoever wills may accept it. Allah has a right that the people should fear His disobedience and He alone has the power to forgive the one who adopts piety and an attitude of God consciousness even though one may have committed many acts of disobedience in the past.</p>;
`
