export default `
 <h2>Name</h2>
<p>The Surah has been so named after the word <em>al-Qiyamah</em> in the first verse. This is not only the name but also the title of this Surah, for it is devoted to Resurrection itself.</p>
<h2>Period of Revelation</h2>
<p>Although there is no tradition to indicate its period of revelation, yet there is in the subject matter of this Surah an internal evidence, which shows that it is one of the earliest Surahs to be sent down at Makkah. After verse 15 the discourse is suddenly interrupted and the Holy Prophet (upon whom be peace) told: "Do not move your tongue to remember this Revelation hastily. It is Our responsibility to have it remembered and read. Therefore, when We are reciting it, listen to its recital carefully. Again, it is Our responsibility to explain its meaning." Then, from verse 20 onward the same theme which was interrupted at verse 15, is resumed. This parenthetical passage, according to both the context and the traditions, has been interposed here for the reason that when the Angel Gabriel was reciting this Surah to the Holy Prophet, the Holy Prophet, lest he should forget its words later, was repeating them at the same moment. This in fact happened at the time when the coming down
and receipt of Revelation was yet a new experience for him and he was not yet fully used to receiving it calmly. There are two other instances also of this in the Qur'an. First, in Surah Ta Ha the Holy Prophet (upon whom be peace) has been told: "And see that you do not hasten to recite the Qur'an before its revelation is completed to you." (v. 114). Then, in Surah Al-A'la, it has been said: "We shall enable you to recite:, then you shall never forget. (v. 6). Later, when the Holy Prophet became fully used to receiving the Revelation well, there remained no need to give him any such instruction. That is why except for these, three, there is no other instance of this in the Qur'an.</p>
<h2>Theme and Subject Matter</h2>
<p>Most of the Surahs, from here till the end of the Qur'an, in view of their content and style, seem to have been sent down in the period when after the first seven verses of Surah Al-Muddaththir, revelation of the Qur'an began like a shower of rain:Thus, in the successively revealed Surahs Islam and its fundamental concepts and moral teachings were presented so forcefully and effectively in pithy, brief sentences and the people of Makkah warned so vehemently on their errors and deviations that the Quraish chiefs were utterly confounded. Therefore, before the next Hajj season came they held the conference for devising schemes to defeat the Holy Prophet (upon whom be peace) as has been mentioned in the Introduction to the Surah Al-Muddaththir above.</p>
<p>In this Surah, addressing thee deniers of the Hereafter, replies have been given to each of their doubts and objections, strong arguments have been given to prove the possibility, occurrence and necessity of the Resurrection and Hereafter, and also it has been pointed out clearly that the actual reason of the people's denying the Hereafter is not that they regard it as impossible rationally but because their selfish motives do not allow them to affirm it. At the same time, the people have been warned, as if to say: "The event, the occurrence of which you deny, will inevitably come: all your deeds will be brought and placed before you. As a matter of fact, even before any of you sees his record, he will be knowing fully well what he has done in the world, for no man is unaware of himself, no matter what excuses and pretenses he may offer to deceive the world and deceive himself in respect of his misdeeds."</p>;
`
