export default `
 <h2>Name</h2>
<p>This Surah is called <em>Ad-Dahr</em> as well as <em>Al-Insan</em> after the words occurring in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Most of the commentators, including Allama Zamakhshari, Imam Razi, Qadi, Baidawi, Allama Nizam ad-Din Nisaburi, Hafiz Ibn Kathir and many others, regard it as a Makki Surah, and, according to Allama Alusi, the same is the opinion of the majority of scholars. However, some commentators hold the view that the Surah was revealed at Madinah, and some others say that it was revealed at Makkah but vv. 8-10 of it were sent down at Madinah.</p>
<p>As far as the subject matter and the style of the Surah are concerned, these are very different from those of the Madani Surahs. A little study of it rather shown that it is not only a Makki Surah but it was revealed during the earliest period at Makkah, which began just after the revelation of the first seven verses of Surah Al-Muddaththir. As for vv 8-10, they are so naturally set in the theme of the Surah that if they are read in their proper context, no one can say that the theme preceding and following them had been sent down 15 to 16 years earlier but these three verses which were revealed many years later were inserted here unnaturally.</p>
<p>In fact, the basis of the idea that this Surah; or some verses of it were revealed at Madinah, is a tradition which has related from Ibn Abbas (may Allah bless him). He says that once Hadrat Hasan and Husain fell ill The Holy Prophet and some of his Companions visited them. They wished Hadrat Ali to make a vow to Allah for the recovery of the two children. Thereupon, Hadrat Ali, Hadrat Fatimah and Fiddah their maid servant, vowed a fast of three days if Allah restored the children to health. The children recovered by the grace of Allah and the three of them began to fast as avowed. As there was nothing to eat in the house, Hadrat Ali borrowed three measures (sa') of barley from somebody (according to another tradition, earned through labor). When on the first day they sat down to eat after breaking the fast, a poor man came and begged for food. They gave all their food to him, drank water and retired to bed. The next day when they again sat down to eat after breaking the fast,
an orphan came and begged for something. They again gave away the whole food to him, drank water and went to bed. On the third day when they were just going to eat after breaking the fast, a captive came up and begged for food likewise. Again the whole food was given away to him. On the fourth day Hadrat Ali took both the children with him and went before the Holy Prophet (upon whom be peace). The Holy Prophet (on whom be peace) seeing the weak condition of the three, returned with them to the house of Hadrat Fatimah and found her lying in a corner half dead with hunger. This moved him visibly. In the meantime the Angel Gabriel (peace be on him) came and said; "Look, Allah has congratulated you on the virtues of the people of your house!"When the Holy Prophet asked what it was, he recited this whole Surah in response. (According to Ibn Mahran's tradition, he recited it from verse 5 till the end. But the tradition which Ibn Marduyah has related from Ibn Abbas only says that the
verse <em>Wa yut'imun-at ta'am...</em> was sent down concerning Hadrat Ali and Hadrat Fatimah; there is no mention of this story in it). This whole story has been narrated by Ali bin Ahmad al-Wahidi in his Commentary of the Qur'an, entitled <em>Al'Basit</em>, and probably from the same it has been taken by Zamakhshari, Razi, Nisaburi and others.</p>
<p>In the first place, this tradition is very weak as regards its chain of transmission. Then, from the point of view of its subject matter also, it is strange that when a poor man, or an orphan, or a captive, comes to beg for food, he is given all the food. He could be given one member's food and the five of them could share the rest of it among themselves:Then this also is incredible that illustrious persons like Hadrat Ali and Hadrat Fatimah, who possessed perfect knowledge of Islam, should have regarded it as an act of virtue to keep the two children, who had just recovered their health and were still weak, hungry for three consecutive days. Moreover, in respect of the captives also, it has never been a practice under the Islamic government that they should be left to beg for food for themselves. For if they were prisoners of the government, the government itself was responsible to arrange food and clothing for them, and if they were in an individual's custody, he was made
responsible to feed and clothe them. Therefore, it was not possible that in Madinah a captive should have gone about begging food from door to door. However, overlooking the weaknesses of transmission and the probability of subject matter, even if the narrative is accepted as it goes, at the most what it shows is that when the people of the Holy Prophet's house acted righteously as they did, Gabriel came and gave him the good news that Allah had much appreciated their act of virtue, for they had acted precisely in the righteous way that Allah had commanded in these verses of Surah Ad-Dahr. This does not necessitate that these verses too were sent down on that very occasion. The same is the case with many traditions concerning the occasion of revelation. When about a certain verse it is said that it was sent down on a particular occasion, it in fact does not mean that the verse was sent down on the very occasion the incident took place. But it means that the verse applies precisely
and exactly to the incident. Imam Suyuti in <em>Al-Itqan</em> has quoted this from Hafiz Ibn Taimiyyah: "When the reporters say that a verse was sent down concerning a particular incident, it sometimes implies that the same incident (or matter) occasioned its revelation, and sometimes that the verse applies to the matter although it may not have occasioned its revelation."Further on he quotes Imam Badr ad-Din Zarkashi's view from his <em>Al-Burhan fi Ulum al-Quran</em> :"It is well known in respect of the Companions and their immediate successors that when one of them says that a verse was sent down concerning a particular matter, it means that the ruling contained in it applied to that matter and not that the matter itself occasioned the revelation of the verse. Thus, it only uses the ruling of the verse for the purpose of reasoning and not for stating a fact." (<em>Al-Itqan fi Ulum al-Quran</em>, vol. I, p. 31, Ed. 1929).</p>
<h2>Theme and Subject Matter</h2>
<p>The theme of this Surah is to inform man of his true position in the world and to tell him that if he understood his true position rightly and adopted the attitude of gratefulness, he would meet with such and such good end, and if he adopted the way of disbelief, he would meet with such and such evil ends In the longer Surahs of the Qur'an this same theme has been presented at length, but a special characteristic of the style of the earliest Surahs revealed at Makkah is that the subjects dealt with at length in the later period, "have been presented in a brief but highly effective way in this period in such concise, elegant sentences as may automatically be preserved in the memory of the hearers.</p>
<p>In this Surah, first of all man has been reminded that there was a time when he was nothing; then a humble beginning of him was made with a mixed drop of sperm and ovum of which even his mother was not aware; even she did not know that he had been conceived nor anyone else seeing the microscopic cell could say that it was a man, who in future would become the best of creation on the earth. After this, man has been warned, so as to say: "Beginning your creation in this way We have developed and shaped you into what you are today in order to test and try you in the world. That is why, unlike other creatures, you were made intelligent and sensible and were shown both the way of gratitude and the way of ingratitude clearly so that you may show, in the interval that you have been granted here for work, whether you have emerged as a grateful servant from the test or an unbelieving, Un- grateful wretch!"</p>
<p>Then, just in one sentence, it has been stated decisively what will be the fate to be met with in the Hereafter by those who emerged as unbelievers from this test.</p>
<p>After this, in vv. 5-22 continuously, the blessings with which those who do full justice to servitude in the world, will be favored, have been mentioned in full detail. In these verses, not only have their best rewards been mentioned but they have also been told briefly what are the acts on the basis of which they would become worthy of those rewards. Another special characteristic of the earliest Surahs revealed at Makkah is that besides introducing in them briefly the fundamental beliefs and concepts of Islam, here and there, those moral qualities and virtuous acts have been mentioned, which are praiseworthy according to Islam, and also those evils of deed and morality of which Islam strives to cleanse human life. And these two things have not been mentioned with a view to show what good or evil result is entailed by them in the transitory life of the world, but they have been mentioned only to point out what enduring results they will produce in the eternal and everlasting
life of the Hereafter, irrespective of whether an evil quality may prove useful or a good quality may prove harmful in the world.</p>
<p>This is the subject matter of the first section (vv. 1-22). In the second section, addressing the Holy Prophet (upon whom be peace), three things have been stated: first, that "it is in fact We Ourself Who are revealing this Qur'an piecemeal to you, and this is intended to inform the disbelievers, not you, that the Qur'an is not being fabricated by Muhammad (upon whom be Allah's peace and blessings) but it is "We Who are revealing it, and it is Our Own wisdom which requires that We should reveal it piece by piece and not all at once."Second, the Holy Prophet has been told: "No matter how long ,it may take for the decree of your Lord to be enforced and no matter what afflictions may befall you in the meantime, in any case you should continue to perform your mission of Apostleship patiently, and not to yield to the pressure tactics of any of these wicked and unbelieving people."The third thing he has been told is: "Remember Allah day and night, perform the Prayer and spend your
nights in the worship of Allah, for it is these things which sustain and strengthen those who call to Allah in the face of iniquity and disbelief."</p>
<p>Then in one single sentence, the actual cause of the disbelievers wrong attitude has been stated: they have forgotten the Hereafter and are enamored of the world. In the second sentence, they have been warned to the effect: "You have not come into being by yourself: We have created you. You have not made these broad chests, and strong, sturdy hands and feet for yourselves, it is We Who made these for you; and it so lies in Our power to treat you as We please. We can distort your figures, We can destroy you and replace you by some other nation. We can cause you to die and can recreate you in whatever form We like."</p>
<p>In conclusion, it has been said: This is an Admonition: whoever wills may accept it and take a path to his Lord. But man's own will and desire is not everything in the world. No one's will and desire can be fulfilled unless Allah (also) so wills. And Allah's willing is not haphazard: whatever He wills, He wills it on the basis of His knowledge and wisdom. He admits into His mercy whomever He regards as worthy of His mercy on the basis of His knowledge and wisdom, and He has prepared a painful torment for those whom He finds unjust and wicked.</p>
`
