export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>wal-mursalat</em> in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Its subject matter bears full evidence that it was revealed in the earliest period at Makkah. If this Surah is read together with the two Surahs preceding it, namely Al-Qiyamah and Ad-Dahr, and the two Surahs following it, namely An-Naba and An-Naziat, it becomes obvious that all these Surahs are the Revelations of the same period, and they deal with one and the same theme, which has been impressed on the people of Makkah in different ways.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to affirm the Resurrection and Hereafter and to warn the people of the consequences which will ultimately follow the denial and the affirmation of these truths.</p>
<p>In the first seven verses, the system of winds has been presented as an evidence of the truth that the Resurrection which is being foretold by the Qur'an and the Prophet Muhammad (upon whom be Allah's peace and blessings) must come to pass. The reasoning is that the power of All-Mighty Allah Who established this wonderful system on the earth, cannot be helpless in bringing about the Resurrection, and the express wisdom which underlies this system bears full evidence that the Hereafter must appear, for no act of an All-Wise Creator can be vain and purposeless, and if there was no Hereafter, it would mean that the whole of one's life was useless and absurd.</p>
<p>The people of Makkah repeatedly asked, "Bring about the Resurrection with which you threaten us; only then shall we believe in it."In vv. 8-l5, their demand has been answered, saying:"Resurrection is no sport or fun so that whenever a jester should ask for it, it should be brought forth immediately. It is indeed the Day of Judgment to settle the account of all mankind and of all its individuals. For it Allah has fixed a specific time it will take place at its own time, and when it takes place with all its dreads and horrors, it will confound those who are demanding it for fun today. Then their cases will be decided only on the evidence of those Messengers whom these deniers of the truth are repudiating with impunity. Then they will themselves realize how they themselves are responsible for their dooms</p>
<p>In vv. 16-28 arguments have been given continuously for the occurrence and necessity of the Resurrection and Hereafter. In these it has been stated that man's own history, his own birth, and the structure of the earth on which he lives, bear the testimony that the coming of Resurrection and the establishment of the Hereafter are possible as well as the demand of Allah Almighty's wisdom. History tells us that the nations which denied the Hereafter ultimately became corrupted and met with destruction. This means that the Hereafter is a truth which if denied and contradicted by a nation by its conduct and attitude, will cause it to meet the same doom, which is met by a blind man who bushes headlong into an approaching train. And it also means that in the kingdom of the universe only physical laws are not at work but a moral law also is working in it, under which in this very world the process of retribution is operating. But since in the present life of the world retribution is not
taking place in its complete and perfect form, the moral law of the universe necessarily demands that there should come a time when it should take its full course and all those good works and evil deeds, which could not be rewarded here, or which escaped their due punishment should be fully rewarded and punished. For this it is inevitable that there should be a second life after death. If man only considers how he takes his birth in the world, his intellect, provided it is sound intellect, cannot deny that for the God Who began his creation from an insignificant sperm drop and developed him into a perfect man, it certainly possible to create the same man once again. After death the particles of man's body do not disappear but continue to exist on the same earth on which he lived his whole life. It is from the resources and treasures of this very earth that he is made and nourished and then into the same treasures of the earth he is deposited. The God who caused him to emerge from
the treasures of the earth, in the first instance, can also cause him to re-emerge from the same treasures after he has been restored to them at death. If one only considers the powers of Allah, one cannot deny that He can do this; and if one considers the wisdom of Allah, one also cannot deny that it is certainly the very demand of His wisdom to call man to account for the right and wrong use of the powers that He has granted him on the earth; it would rather be against wisdom to let him off without rendering an account.</p>
<p>Then, in vv. 28-40, the fate of the deniers of the Hereafter has been depicted, and in vv. 41-45 of those who affirming faith in it in their worldly life, endeavored to improve their Hereafter, and abstained from the evils of disbelief and thought, morality and deed, conduct and character which might be helpful in man's worldly life, but are certainly ruinous for his life hereafter.</p>
<p>In the end, the deniers of the Hereafter and those who turn away from God-worship, have been warned as if to say: "Enjoy your short-lived worldly pleasure as you may, but your end will ultimately be disastrous." The discourse concludes with the assertion that the one who fails to obtain guidance from Book like the Qur'an, can have no ether source in the world to afford him Guidance.</p>
`
