export default `
 <h2>Name</h2>
<p>The Surah takes its name Al-Anfal (The Bounties) from the first verse.</p>
<h2>The Period of Revelation</h2>
<p>It was revealed in 2 A. H. after the Battle of Badr, the first battle between Islam and <em>kufr</em>. As it contains a detailed and comprehensive review of the Battle, it appears that most probably it was revealed at one and the same time. But it is also possible that some of the verses concerning the problems arising as a result of this Battle might have been revealed later and incorporated at the proper places to make it a continuous whole. At any rate, in the whole Surah there is nothing that might show that it is a collection of a couple of discourses, that have been patched up together.</p>
<h2>Historical Background</h2>
<p>Before reviewing the Surah, it is worthwhile to consider the events that led to the Battle of Badr.</p>
<p>During the first decade or so of the Prophethood at Makkah, the Message had proved its firmness, and stability. This was the result of two things. First, the Messenger, who possessed the highest qualities of character, was performing his Mission with wisdom, foresight and magnanimity. He had shown by his conduct that he had made up his mind to carry the movement to a successful end and, therefore, was ready to face all sorts of dangers and obstacles in the way. Secondly, the Message was so charming that it attracted the minds and hearts of the people irresistibly towards itself. So much so that all obstacles of ignorance, superstition and petty prejudices failed to check, its advance. That is why the Arab upholders of the ways of "ignorance,' who looked down upon it in its initial stages, had' begun to reckon it as a serious menace during the last period of the stay of the Holy Prophet at Makkah, and were bent on crushing it with all the force at their command. But in spite of
the above-mentioned strength, the movement still lacked certain things to lead it to victory:-</p>
<p>First, it had not yet been fully proved that it had gathered round it a sufficient number of such followers who not only believed in its truth, but also had such an intense devotion to its principles that they were ready to expend all their energies and all that they possessed in the struggle for its success and establishment. So much so that they were ready to sacrifice their lives in the fight against the whole world itself even though they should be their own nearest relative. It is true that the followers of Islam had endured the severest persecutions at the hands of the Quraish of Makkah and had given a good proof of the firmness of their faith and their strong relation with Islam, yet further trials were required to show that Islam had succeeded in acquiring such a band of followers which considered nothing dearer than its ideal and was ready to sacrifice life for it.</p>
<p>Secondly, though the voice of Islam had reached' every part of the country, its effects were yet scattered and its acquired strength was spread here and there: it had not yet gathered sufficient force essential for a decisive conflict with the old established order of "ignorance".</p>
<p>Thirdly, Islam had yet no home of its own and had not established itself firmly anywhere in the land where it could consolidate its power and make it a base for further action. For the Muslims were scattered all over the country and were living among the unbelievers as aliens whom their bloodthirsty enemies wanted to uproot from their own homes.</p>
<p>Fourthly, the Muslims had not yet had an opportunity to demonstrate practically the blessings of the system of life based on Islam. There was neither any Islamic culture, nor any social, economic or political system; nor were there any established principles of war and peace for their guidance. Therefore the Muslims had no opportunity for demonstrating those moral principles on which they intended to build their entire system of life; nor had it been proved on the touchstone of trial that the Muslims as a community were sincere in their proclamation of the Message.</p>
<p>Allah created opportunities for making up these deficiencies.</p>
<p>During the last four years or so of the Prophet's stay at Makkah, the voice of Islam had been proving effective at Yathrab and the people for various reasons had been accepting the message more readily than other clans of Arabia. So much so that in the twelfth year of Prophethood on the occasion of <em>Haj</em> a deputation of 75 people met the Holy Prophet in the darkness of night. These people not only accepted Islam, but also offered to give him and his followers a home. As this was a most epoch making opportunity provided by Allah, the Holy Prophet took advantage of it.</p>
<p>The significance of this offer was quite clear to the people of Yathrab, and they fully realized that this was not an invitation to a mere fugitive, but to the Messenger of Allah so that he should become their leader and ruler. Likewise they knew that they were not inviting the Muslim refugees to give them shelter from persecution but to assemble them from all over the country for their integration with themselves to form an organized community. Thus the offer of the people of Yathrab was to make Yathrab the "City of Islam." Accordingly the Holy Prophet accepted their invitation and made it the first "City of Islam" in Arabia.</p>
<p>And the people of Yathrab were fully aware of the implications of this offer. It was indeed a declaration of war against the whole of Arabia, and an invitation to their own social and economic boycott as well. And when the <em>Ansar</em> from Yathrab declared their allegiance to the Holy Prophet at Aqabah, they knew fully well its consequences. During the course of the formal declaration of allegiance, Asad-bin- Zurarah, the youngest of all the delegates from Yathrab, stood up and said, "0 people of Yathrab! Just listen to me and consider the matter carefully in all its aspects. Though we have come to him, regarding him only as a Messenger of Allah, we should know that we shall be inviting the enmity of the whole of Arabia. For when we take him away to Yathrab, we shall be attacked and our children may be put to the sword. Therefore if you have the courage in your hearts to face it, then and then only, you should declare your allegiance to him and Allah will give you its reward.
But if you love your lives more than him and his Message, then leave this matter and frankly excuse yourselves, for at this time Allah may accept your excuses."</p>
<p>Abbas bin Ubadah bin Naalah, another member of the delegation, reiterated the same thing, saying,</p>
<p>Do you understand the implication of the declaration of your allegiance to this person?" (Voices, "Yes, we know it.") "You are challenging the whole world to war by your declaration of allegiance to him. There is every likelihood of a serious menace to your lives and properties. Therefore consider it well. If you have any idea lurking in your minds that you will then hand him over to his enemies, it is much better to leave him alone now, because that conduct shall bring shame and disgrace to you in this world and the next. On the other hand, if you have sincerely resolved that you will endure all kinds of consequences that will follow as a result of this invitation, then it would be the best thing to take the oath of allegiance to him because, by God, this will surely bring good to you in this world as well as in the next world."</p>
<p>At this all the members of the delegation cried with one voice, "We are ready and prepared to risk all our wealth and our noble kith and kin for his sake."</p>
<p>It was then that the famous oath of allegiance, which is known as the "Second Oath of Allegiance at Aqabah" was taken.</p>
<p>On the other side, the people of Makkah also understood fully well the implications of this matter from their own point of view. They realized that Muhammad (Allah's peace be upon him), who, they knew well, had a great personality and possessed extraordinary abilities, was going to gain a strong footing, by this allegiance. For this would help integrate his followers, whose constancy, determination, and unwavering fidelity to the Messenger had been tried, into a disciplined community under his wise leadership and guidance. And they knew that this would spell death for their old ways of life. They also realized the strategic importance of. Al-Madinah to their trade, which was their chief means of livelihood.</p>
<p>Its geographical position was such that the Muslims could strike with advantage at the caravans traveling on the trade route between Yemen and Syria, and thus strike at the root of their economy and that of other pagan clans very effectively. The value of the trade done by the people of Makkah alone on this route, not to count that of raif and other places, amounted to about two hundred thousand <em>dinars</em> annually.</p>
<p>As the Quraish were fully aware of the implications of the oath of allegiance at Aqabah, they were greatly perturbed when they got wind of it the same night. At first they tried to win over the people of Al-Madinah to their side. But when they saw that the Muslims were migrating to Al- Madinah in small groups, they realized that the Holy Prophet was also going to emigrate soon from there. Then they decided to adopt an extreme measure to prevent this danger.</p>
<p>A few days before his migration, the Quraish held a council to consider the matter. After a good deal of argument; they decided that one person should be taken from each of the families of Quraish other than that of Banu Hashim to put an end to the life of the Holy Prophet. This was to make it difficult for the family of the Holy Prophet to fight alone with all the other families of the Quraish and thus to force them to accept blood-money for his murder-instead of taking revenge from them, but by the grace of Allah their plot against the life of the Holy Prophet failed because of his admirable foresight and full trust in Allah, and he reached Al- Madinah safe and sound. When they could not prevent his emigration, it occurred to them to exploit Abdullah bin Ub\`ai who had begun to cherish a grievance against the Holy Prophet since his arrival at Al-Madinah. He was an influential chief of Al-Madinah and the people had agreed to make him their king. But when the majority of Aus and
Khazraj clan became Muslims and acknowledged the Holy Prophet as their leader, guide and ruler, all his hopes of becoming a king came to an end. Therefore the Quraish wrote to him, "As you have given shelter to our enemy, we tell you plainly that you should either fight with him yourself or exile him from your city otherwise we swear by God that we will invade your city, kill your males and make your females our slave girls." This letter added fuel to the flames of his jealousy and he was inclined to do some mischief, but the Holy Prophet took timely precautions and defeated his evil designs.</p>
<p>The Quraish got another opportunity to hold out a threat. When Sa'ad bin Mu'az, another chief of Al-Madinah, went to Makkah to perform \`<em>Umrah</em>, Abu Jahl interrupted him at the very door of the Kabah, saying, "Do you think we will let you perform \`<em>Umrah</em> in peace while you give shelter and help to renegades from us? Had you not been a guest of Ummayyah bin Khalf, you would not have gone alive from here." Sa'ad replied, "By Allah, if you prevent me from this, I will retaliate in a worse manner and block your route near Al-Madinah." This incident virtually led to a declaration from the people of Makkah that they would prevent the Muslims from a pilgrimage to the Kabah, and from the people of Al- Madinah that as a retaliation they would block their trade route to Syria against the opponents of Islam. As a matter of fact there was no other alternative for the Muslims than to keep a strong hold on this route so as to force the Quraish, and the other clans, whose
interests were vitally bound with this route, to reconsider their inimical and antagonistic attitude towards them. That is why the Holy Prophet attached the greatest importance to this problem. As soon as he was free from making the preliminary arrangements for organizing the newly formed Muslim Community and settling peace terms with the neighboring Jewish habitations, he adopted two measures in this connection:-</p>
<p>First, he entered into negotiations with those clans who lived between the Red Sea and this route so as to make alliances with them or at east to persuade them to make treaties of neutrality with the Muslims. He was successful in this, and he entered into a treaty of non-alignment with Juhainah, which was a very important clan of the hilly tract near the sea coast. Then, at the end of the first year of Hijrah, he made a treaty of defensive alliance with Bani Damrah, who lived near Yanb'u and Zawal Ushairah. In 2 A. H. Bani Mudlij also joined the alliance, as they were the neighbors and allies of Bani Damrah. Then ii so happened that quite a large number of these people were converted to Islam as a result of the missionary work done by the Muslims.</p>
<p>Secondly, he successively sent small bands of his men on this route to serve as a warning to the Quraish, and himself accompanied some of them. In the first year of Hijrah, four expeditions were sent there, that is, the expedition under Hamzah, the expedition under Ubaidah bin Harith, the expedition under Sa'ad bin Abi Waqqas and the Al-Abwa' expedition under the Holy Prophet himself. In the first month of the second year two more incursions were made on the same route. These are known as Buwat Expedition and Zawal Ushairah Expedition. Two things about all these expeditions are noteworthy. First, no blood was shed and no caravans were plundered in any of these expeditions. This proves that the real object of these expeditions was to show to the Quraish which way the wind was blowing. Secondly, not a single man from the people of Al-Madinah was sent by the Holy. Prophet on any of these incursions. All the bands consisted purely of the immigrants from Makkah so that the conflict
should remain between the people of the Quraish themselves and should not further spread by the involvement of other clans. On the other side, the Quraish of Makkah tried to involve others also in the conflict. When they sent bands towards Al-Madinah, they did not hesitate to plunder the people. For instance, an expedition under the leadership of Kurz bin Jabir al-Fihrl plundered the cattle of the people of Al-Madinah from the very vicinity of the city to show what their real intentions were.</p>
<p>This was the state of affairs when, in Sha'aban, 2 A. H. (February or March, 623 A. D.) a big trade caravan of the Quraish, carrying goods worth $50,000 or so, with only a guard of thirty to forty men, on its way back from Syria to Makkah, reached the territory from where it could be easily attacked from Al-Madinah. As the caravan was carrying trade goods worth thousands of pounds, and was scantily guarded, naturally Abu Sufyan, who was in charge of it, from his Past experience feared an attach from the Muslims. Accordingly, as soon as he entered the dangerous territory, he dispatched a camel rider to Makkah with a frantic appeal for help. When the rider reached Makkah, he, following an old custom of Arabia, tore open the ears of his camel, cut open his nose and overturned the saddle. Then rending his shirt from front and behind, he began to cry aloud at the top of his voice, "O people of Quraish dispatch help to protect your caravan from Syria under the charge of Abu Sufyan,
for Muhammad with his followers is in pursuit of it; otherwise I don't think you will ever get your goods. Run, run for help." This caused great excitement and anger in the whole of Makkah and all the big chiefs of the Quraish got ready for war. An army, consisting of 600 armored soldiers and cavalry of 100 riders with great pomp and show marched out for a fight. They intended not only to rescue the caravan but also to put to an end, once for all, the new menace from the Muslims who had consolidated themselves at Al-Madinah. They wanted to crush that rising power and overawe the clans surrounding the route so as to make it absolutely secure for future trade.</p>
<p>Now the Holy Prophet, who always kept himself well informed of the state of affairs, felt that the decisive hour has come and that was the right time when he must take a bold step; otherwise the Islamic Movement would become lifeless for ever and no chance would be left for it to rise again. For if the Quraish invaded Al-Madinah, the odds would be against the Muslims. The condition of the Muslim Community was still very shaky because the immigrants (<em>Muhajirin</em>) had not been able to stabilize their economy during the short period (less than two years) of their stay at Al-Madinah; their helpers, (the <em>Ansar</em>) had not yet been tried; and the neighboring Jewish clans were antagonistic. Then there was a strong group of hypocrites and <em>mushriks</em> in Al- Madinah itself; above all, the surrounding clans lived in awe of the Quraish and had all their religious sympathies with them. The Holy Prophet, therefore, felt that the consequences of this possible invasion would
not be favorable to the Muslims.</p>
<p>The second possibility was that they would not invade Al-Madinah but try only to escort their caravan safely and securely by a mere show of force. In that case, too, if the Muslim remained inactive, it would affect their reputation adversely. Obviously, this weak stand in the conflict would embolden the other Arabs also and make the position of the Muslims very insecure in the country and the surrounding clans would, at the instance of the Quraish, start hostilities against them, and the Jews, the hypocrites and the <em>mushriks</em> of Al- Madinah would openly rise against them and not only endanger their security of life, property and honor but make it difficult for them even to live there.</p>
<p>The Muslims would not be able to inspire the enemy with awe so as to keep safe from them their life, property and honor. A careful study of the situation led the Holy Prophet to make up his mind to take a decisive step and go into the battle with whatever little strength he could muster, for thus and thus only could he show whether the Muslim Community had the right to survive or was doomed to perish.</p>
<p>When he arrived at this momentous decision, he called the <em>Muhajirin</em> and the <em>Ansar</em> together and placed the whole position before them, without any reservation. He said, "Allah has promised that you will confront one of the two, the trade caravan coming from the north or the army of the Quraish marching from the south. Now tell me which of the two you want to attack!" A large majority of the people replied that they wanted to attack the caravan. But the Holy Prophet who had something else before him, repeated the same question. At this Miqdad bin 'Amr, a <em>Muhajir</em>, stood up and said, "0 Messenger of Allah! Please march to the side to which your Lord commands you; we will accompany you wherever you go. We will not say like the Israelites, 'Go and let you and your Lord fight we will wait'. In contrast to them we say, 'Let you and your Lord fight; we will fight by your side to our last breath'." Even then he did not announce any decision but waited for a reply
from the <em>Ansar</em> who had not yet taken any part in any battle of Islam. As this was the first opportunity for them to prove that they were ready to fulfill their promise of fighting for the cause of Islam, he repeated the question without directly addressing them. At this, Sa'ad bin Mu'az, an <em>Ansar</em>, stood up and said, "Sir, it appears that you are putting the question to us." When the Holy Prophet said, "Yes", the <em>Ansar</em> replied, "We have believed in you and confirmed that what you have brought is the Truth, and have made a solemn pledge with you that we will listen to you and obey you. Therefore, 0 Messenger of Allah, do whatever you intend to do. We swear by Allah Who has sent you with the Truth that we are ready to accompany you to the sea shore and if you enter it, we will plunge into it. We assure you that not a single one of us will remain behind or forsake you, for we will not hesitate at all to go to fight, even if you should lead us to the battlefield
tomorrow. We will remain steadfast in the battle and sacrifice our lives in the fight. We do hope that by the grace of Allah our behavior will gladden your heart. So, trusting in Allah's blessing, take us to the battlefield."</p>
<p>After these speeches it was decided that they should march towards the army of the Quraish and not towards the trade caravan. But it should be noted that the decision was of an ordinary nature. For the number of people, who came forward to go to the battlefield, was only a little more than three hundred (86 <em>Muhajirs</em>, 62 from Aus and 170 from Khazraj). Then the little army was ill-armed and hardly equipped for battle. Only a couple of them had horses to ride and the others had to take their turn in threes and fours on the back of a camel, out of the 70 they had in all. Above all, they had not got enough weapons for the battle; only 60 of them had armors. It is, therefore, no wonder that with the exception of those who were prepared to sacrifice their lives for the cause of Islam, the majority of those who had joined the expedition, were so filled with fear that they felt as if they were knowingly going into the jaws of death. Then there were people who always looked at
things from a selfish point of view. Though they had embraced Islam, they did not realize that their faith would demand the sacrifice of their lives and properties from them; they were of the opinion that it was a mad expedition prompted by irrational enthusiasm for religion. But the Holy Prophet and the true Believers had realized the urgency of that critical hour which required the risk of life: therefore they marched straight to the south-west, wherefrom the army of the Quraish was coming. This is a clear proof of the fact that from the very beginning they had gone out to fight with the army and not to plunder the caravan. For if they had aimed at plundering the caravan they would have taken the north- westerly direction and not the south- westerly one.</p>
<p>The two parties met in combat at Badr on the seventeenth of Ramadan. When the two armies confronted each other and the Holy Prophet noticed that the Quraish army outnumbered the Muslims by three to one and was much better equipped, he raised his hands up in supplication and made this earnest prayer with great humility: "O Allah! Here are the Quraish proud of their war material: they have come to prove that Thy Messenger is false. O Allah! now send that success that Thou hast promised to give me. O Allah! If this little army of Thy servants is destroyed, then there will be left none in the land to worship Thee."</p>
<p>In this combat the emigrants from Makkah were put to the hardest test for they had to fight against their own near and dear relatives and put to the sword their fathers, their sons, their paternal and maternal uncles and their brothers. It is obvious that only such people could have come out successful in this hardest of tests as had accepted the Truth sincerely and cut off all relations with falsehood. And in another way the test to which the <em>Ansar</em> were put was not less hard. So far they had only alienated the powerful Quraish and their allies by giving shelter to the Muslims against their wishes but now, for the first time, they were going to give fight to them and to sow the seeds of a long and bitter war with them. This was indeed a very hard test for it meant that a small town with a population of a few thousand inhabitants was going to wage a war with the whole of Arabia. It is obvious that only such people could take this bold step who believed in the Truth of
Islam so firmly that they were ready to sacrifice every personal interest for its sake.</p>
<p>So Allah accepted the self-sacrifices of the <em>Muhajirin</em> and the <em>Ansar</em> because of their true faith, and rewarded them with His success. The proud, well- armed Quraish were routed by these ill-equipped devotees of Islam. Seventy men of their army were killed and seventy captured as prisoners and their arms and equipment came into the hands of the Muslims as spoils of war. All their big chiefs, who were their best soldiers and who had led the opposition to Islam, were killed in this Battle. No wonder that this decisive victory made Islam a power to be reckoned with. A Western research scholar says that before the Battle of Badr, Islam was merely a religion and a state but after the Battle it became the state religion, nay, the state itself.</p>
<h2>Topics of Discussion</h2>
<p>It is this great Battle that has been reviewed in this Surah. But let it be noted that in some respects this review is quite different from the reviews that are usually made by the worldly commanders after a great victory.</p>
<ol>
  <li>
    <p>Instead of gloating over the victory, the moral weaknesses that had come to the surface in that expedition have been pointed out so that the Muslims should try their best to reform themselves.</p>
  </li>
  <li>
    <p>It has been impressed upon them that the victory was due to the success of Allah rather -than to their own valor and bravery so that the Muslims should learn to rely on Him and obey Allah and His Messenger alone.</p>
  </li>
  <li>
    <p>The moral lesson of the conflict between the Truth and falsehood has been enunciated and the qualities which lead to success in a conflict have been explained.</p>
  </li>
  <li>
    <p>Then the Surah addresses the <em>mushriks</em>, the hypocrites, the Jews and the prisoners of this war in a very impressive manner that should teach them a good lesson.</p>
  </li>
  <li>
    <p>It also gives instructions in regard to the spoils of war. The Muslims have bean told not to regard these as their right but as a bounty from Allah. Therefore they should accept with gratitude the share that is granted to them out of it and willingly accede to the share which Allah sets apart for His cause and for the help of the needy.</p>
  </li>
  <li>
    <p>Then it also gives normal instructions concerning the laws of peace and war for these were urgently needed to be explained at the stage which the Islamic Movement had entered. It enjoined that the Muslims should refrain from ways of "ignorance" in peace and war and thus should establish their moral superiority in the world. It also meant, to demonstrate to the world in actual practical life the morality which it had been preaching to the world from the very beginning of Islam and had been enjoining that practical life should be based on the same.</p>
  </li>
  <li>
    <p>It also states some articles of the Islamic Constitution which help differentiate the status of the Muslims living within the limits of <em>Dar-ul-Islam</em> (the Abode of Islam) from that of the Muslims living beyond its limits.</p>
  </li>
</ol>
<h2>Subject: Problems of <em>Jihad</em></h2>
<p>This surah enunciates general principles of war (one aspect of <em>Jihad</em>) and peace while reviewing the Battle of Badr and uses them for the moral training of the Muslims.</p>
<h3>Topics and their Interconnection</h3>
<p>This portion deals with the problems of the "Spoils of War". The Quran says that these are not the spoils of war but the "Bounties of Allah" and proves this by showing that the victory at Badr (and in all other battles, too,) was won by His succor and not by the efforts of the Muslims. It also declares (in v. 40) that the war aim of the Muslims should be to eliminate all unfavorable conditions for the establishment of Islam and not to gain spoils. Moreover, the spoils, being the bounties of God, belong to Allah and His Messenger and they alone are entitled to allocate them. Then after conditioning the Muslims to accept these things, the different shares have been allocated in v. 41. <strong>1 - 41</strong></p>
<p>The Battle of Badr was ordained by Allah so that Islam should triumph over "ignorance". The lesson from this is that the Muslims should trust in God and prepare themselves for war and should not be beguiled by Satan as the disbelievers were. <strong>42 - 54</strong></p>
<p>Sanctity of treaties has been enjoined and the Muslims commanded to observe them as long as the other party does not break them. <strong>55 - 59</strong></p>
<p>The Muslims should always be prepared for war on every front, but should be ready to make peace if the other party is inclined towards it. <strong>60 - 66</strong></p>
<p>In these verses, instructions about prisoners of war have been given. <strong>67 - 71</strong></p>
<p>In order to keep the Muslims joined together against their enemies, they have been taught to have cordial relations with one another. <strong>72 - 75</strong></p>
`
