export default `
 <h2>Name</h2>
<p>The Surah is so designated after the word <em>\`abasa</em> with which it opens.</p>
<h2>Period of Revelation</h2>
<p>The commentators and traditionists are unanimous about the occasion of the revelation of this Surah. According to them, once some big chiefs of Makkah were sitting in the Holy Prophet's assembly and he was earnestly engaged in trying to persuade them to accept Islam. At that very point, a blind man, named Ibn Umm Maktum, approached him to seek explanation of some point concerning Islam. The Holy Prophet (upon whom be peace) disliked his interruption and ignored him. Thereupon Allah sent down this Surah. From this historical incident the period of the revelation of this Surah can be precisely determined.</p>
<p>In the first place, it is confirmed that Hadrat Ibn Umm Maktum was one of the earliest converts to Islam. Hafiz Ibn Hajar and Hafiz Ibn Kathir have stated that he was one of those who had accepted Islam at a very early stage at Makkah.</p>
<p>Secondly, some of the traditions of the Hadith which relate this incident show that he had already accepted Islam and some others show that be was inclined to accept it and had approached the Holy Prophet in search of the truth. Hadrat Aishah states that coming to the Holy Prophet he had said: "O Messenger of Allah, guide me to the straight path." (Tirmidhi, Hakim, Ibn Hibban, Ibn Jarir, Abu Ya'la. According to Hadrat Abdullah bin Abbas, he had asked the meaning of a verse of the Qur'an and said to the Holy Prophet: "O Messenger of Allah, teach me the knowledge that Allah has taught you." Ibn Jarir, Ibn Abu Hatim). These statements show that he had acknowledged the Holy Prophet (upon whom be peace as a Messenger of Allah and the Quran as a Book of Allah. Contrary to this, Ibn Zaid has interpreted the words <em>la allahu yazzakka</em> of verse 3 to mean: <em>la allahu yuslim</em> : "maybe that he accepts Islam." (Ibn Jarir) And Allah's own words: "What would make you know that he
might reform, or heed the admonition, and admonishing might profit him?" and "The one who comes to you running, of his own will, and fears, from him you turn away", point out that by that time he had developed in himself a deep desire to learn the truth: he had come to the Holy Prophet with the belief that he was the only source of guidance and his desire would be satisfied only through him; his apparent state also reflected that if he was given instruction, he would benefit by it.</p>
<p>Thirdly, the names of the people who were sitting in the Holy Prophet's assembly at that time, have been given in different traditions. In this list we find the names of \`Utbah, Shaibah, Abu Jahl, Umayyah bin Khalaf, Ubayy bin Khalaf, who were the bitterest enemies of Islam. This shows that the incident took place in the period when these chiefs were still on meeting terms with the Holy Prophet and their antagonism to Islam had not yet grown so strong as to have stopped their paying visits to him and having dialogues with him off and on. All these arguments indicate that this is one of the very earliest Surahs to be revealed at Makkah.</p>
<h2>Theme and Subject Matter</h2>
<p>In view of the apparent style with which the discourse opens, one feels that in this Surah Allah has expressed His displeasure against the Holy Prophet (upon whom be peace) for his treating the blind man with indifference and attending to the big chiefs exclusively. But when the whole Surah is considered objectively, one finds that the displeasure, in fact, has been expressed against the disbelieving Quraish, who because of their arrogant attitude and indifference to the truth, were rejecting with contempt the message of truth being conveyed by the Holy Prophet (upon whom be peace). Then, besides teaching him the correct method of preaching, the error of the method that he was adopting at the start of his mission has also been pointed out. His treating the blind man with neglect and disregard and devoting all his attention to the Quraish chiefs was not for the reason that he regarded the rich as noble and a poor blind man as contemptible, and, God forbid, there was some rudeness
in his manner for which Allah reproved him. But, as a matter of fact, when a caller to Truth embarks on his mission of conveying his message to the people, he naturally wants the most influential people of society to accept his message so that his task becomes easy, for even if his invitation spreads among the poor and weak people, it cannot make much difference. Almost the same attitude had the Holy Prophet (upon whom be peace) also adopted in the beginning, his motive being only sincerity and a desire to promote his mission and not any idea of respect for the big people and hatred for the small people. But Allah made him realize that that was not the correct method of extending invitation to Islam, but from his mission's point of view, every man, who was a seeker after truth, was important, even if he was weak, or poor, and every man, who was heedless to the truth, was unimportant, even if he occupied a high position in society. Therefore, he should openly proclaim and convey the
teachings of Islam to all and sundry, but the people who were really worthy of his attention, were those who were inclined to accept the Truth, and his sublime and noble message was too high to be presented before those haughty people who in their arrogance and vanity thought that they did not stand in need of him but rather he stood in need of them.</p>
<p>This is the theme of vv. 1-16. From verse 17 onward the rebuke directly turns to the disbelievers, who were repudiating the invitation of the Holy Messenger of Allah (upon whom be peace). In this, first they have been reproved for their attitude which they had adopted against their Creator, Providence and Sustainer. In the end, they have been warned of the dreadful fate that they would meet in consequence of their conduct on the Day of Resurrection.</p>
`
