export default `
 <h2>Name</h2>
<p>It is derived from the word <em>inshaqqat</em> in the first verse. <em>Inshaqqat</em> is infinitive which means to split asunder, thereby implying that it is the Surah in which mention has been made of the splitting asunder of the heavens.</p>
<h2>Period of Revelation</h2>
<p>This too is one of the earliest Surahs to be revealed at Makkah. The internal evidence of its subject matter indicates that persecution of the Muslims had not yet started; however, the message of the Qur'an was being openly repudiated at Makkah and the people were refusing to acknowledge that Resurrection would ever take place when they would have to appear before their God to render an account of their deeds.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is the Resurrection and Hereafter.</p>
<p>In the first five verses not only have the state of Resurrection been described vividly but an argument of its being true and certain also have been given. It has been stated that the heavens on that Day will split asunder, the earth will be spread out plain and smooth, and it will throw out whatever lies inside it of the dead bodies of men and evidences of their deeds so as to become completely empty from within. The argument given for it is that such will be the Command of their Lord for the heavens and the earth; since both are His creation. they cannot dare disobey His Command. For them the only right and proper course is that they should obey the Command of their Lord.</p>
<p>Then, in vv 6-19 it has been said that whether man Is conscious of this fact or not, he in any case is moving willy nilly to the destination when he will appear and stand before his Lord. At that time all human beings will divide into two parts: first those whose records will be given in their right hands: they will be forgiven without any severe reckoning; second those whose records will be given them behind their back. They will wish that they should die somehow, but they will not die; instead they will be cast into Hell. They will meet with this fate because in the world they remained lost in the misunderstanding that they would never have to appear before God to render an account of their deeds, whereas their Lord was watching whatever they were doing, and there was no reason why they should escape the accountability for their deeds. Their moving gradual]y from the life of the world to the meting out of rewards and punishments in the Hereafter was as certain as the
appearance of twilight after sunset, the coming of the night after the day, the returning of men and animals to their respective abodes at night, and the growing of the crescent into full moon.</p>
<p>In conclusion, the disbelievers who repudiate the Qur'an instead of bowing down to God when they hear it, have been forewarned of a grievous punishment and the good news of limitless rewards has been given to the believers and the righteous.</p>
`
