export default `
 <h2>Name</h2>
<p>The Surah is so designated after the word <em>al buruj</em> appearing in the first verse.</p>
<h2>Period of Revelation</h2>
<p>The subject matter itself indicates that this Surah was sent down at Makkah in the period when persecution of the Muslims was at its climax and the disbelievers of Makkah were trying their utmost by tyranny and coercion to turn away the new converts from Islam.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to warn the disbelievers of the evil consequences of the persecution and tyranny that they were perpetrating on the converts to Islam, and to console the believers, so as to say: "If you remain firm and steadfast against tyranny and coercion, you will be rewarded richly for it, and Allah will certainly avenge Himself on your persecutors on your behalf."</p>
<p>In this connection, first of all the story of the people of the ditch (<em>ashab al-ukhdud</em>) had been related, who had burnt the believers to death by casting them into pits full of fire. By means of this story the believers and the disbelievers have been taught a few lessons. First, that just as the people of the ditch became worthy of Allah's curse and punishment, so are the chiefs of Makkah also becoming worthy of it. Second, that just as the believers at that time had willingly accepted to sacrifice their lives by being burnt to death in the pits of fire instead of turning away from the faith, so also the believers now should endure every persecution but should never give up the faith. Third, that Gods acknowledging Whom displeases the disbelievers and is urged on by the believers, is Dominant and Master of the Kingdom of the earth and heavens; He is self-praiseworthy and is watching what the two groups are striving for. Therefore, it is certain that the disbelievers
will not only be punished in Hell for their disbelief but, more than that, they too will suffer punishment by fire as a fit recompense for their tyranny and cruelties. Likewise, this also is certain that those, who believe and follow up their belief with good deeds, should go to Paradise and this indeed is the supreme success. Then the disbelievers have been warned, so as to say: "God's grip is very severe. If you are proud of the strength of your hosts, you should know that the hosts of Pharaoh and Thamud were even stronger and more numerous. Therefore, you should learn a lesson from the fate they met. God's power has so encompassed you that you cannot escape His encirclement, and the Qur'an that you are bent upon belying, is unchangeable: it is inscribed in the Preserved Tablet, which cannot be corrupted in any way."</p>;
`
