export default `
 <h2>Name</h2>
<p>The Surah taken its name from the word <em>at-tariq</em> in its first verse.</p>
<h2>Period of Revelation</h2>
<p>The style of its subject matter resembles that of the earliest Surahs revealed at Makkah, but this surah was sent down at a stage when the disbelievers of Makkah were employing all sorts of devices and plans to defeat and frustrate the message of the Qur'an and Muhammad (upon whom be Allah's peace and blessings).</p>
<h2>Theme and Subject Matter</h2>
<p>It discuses two themes: first that man has to appear before God after death; second, that the Qur'an is a decisive Word which no plan or device of the disbelievers can defeat or frustrate.</p>
<p>First of all, the stars of the heavens have been cited as an evidence that there is nothing in the universe which may continue to exist and survive without guardian over it. Then man has been asked to consider his own self as to how he has been brought into existence from a mere sperm drop and shaped into a living human being. Then it has been said that the God, Who has so brought him into existence, has certainly the power to create him once again, and this resurrection will be for the purpose to subject to scrutiny all the secrets of man which remained hidden in the world. At that time, man will neither be able to escape the consequences of his deeds by his own power, nor will anyone else come to his rescue.</p>
<p>In conclusion, it has been pointed out that just as the falling of rain from the sky and the sprouting of plants and crops from the earth is no child's play but a serious task, so also the truths expressed in the Qur'an are no jest but a firm and unchangeable reality. The disbelievers are involved in the misunderstanding that their plans and devices will defeat the invitation of the Qur'an, but they do not know that Allah too is devising a plan which will bring to naught all their scheming and planning. Than in one sentence the discourse has been summed up, with a word of consolation to the Holy Prophet (upon whom be peace) and a tacit warning to the disbelievers, saying: "Have patience for a while: let the disbelievers do their worst. Before long they will themselves realize whether they have been able to defeat the Qur'an by their scheming or the Qur'an has dominated them in the very place where they are exerting their utmost to defeat it."</p>
`
