export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>al-ghishiyah</em> in the first verse.</p>
<h2>Period of Revelation</h2>
<p>The whole subject matter of the Surah indicates that this too is one of the earliest Surahs to be revealed; but this was the period when the Holy Prophet (upon whom be peace) had started preaching his message publicly, and the people of Makkah were hearing it and ignoring it carelessly and thoughtlessly.</p>
<h2>Theme and Subject Matter</h2>
<p>To understand the subject matter well one should keep in view the fact that in the initial stage the preaching of the Holy Prophet (upon whom be peace) mostly centered around two points which he wanted to instill in the people's minds: <em>Tauhid</em> and the Hereafter: and the people of Makkah were repudiating both. Let us now consider the subject matter and the style of this Surah.</p>
<p>At the outset, in order to arouse the people from their heedlessness, they have been plainly asked:"Do you have any knowledge of the time when an overwhelming calamity will descend?" Immediately after this details of the impending calamity are given as to how the people will be divided into two separate groups and will meet separate ends. One group of the people will go to Hell and they will suffer punishment; the second group will go to the sublime Paradise and will be provided with, blessings.</p>
<p>After thus arousing the people the theme suddenly changes and the question is asked: Do not these people, who frown and scorn the teaching of <em>Tauhid</em> and the news of the Hereafter being given by the Qur'an, observe the common things which they experience daily in their lives? Do they never consider how the camels, on whom their whole life activity in the Arabian desert depends, came into being, endowed precisely with the same characteristics as were required for the beast needed in their desert life? When they go on their journeys, they see the sky, the mountains, or the earth. Let them ponder over these three phenomena and consider as to how the sky was stretched above them, how the mountains were erected and how the earth was spread beneath them? Has all this come about without the skill and craftsmanship of an All- Powerful, All Wise Designer? If they acknowledge that a Creator has created all this with great wisdom and power and that no one else is an associate with
Him in their creation, why then do they refuse to accept Him alone as their Lord and Sustainer? And if they acknowledge that that God had the power to create all this, then on what rational ground do they hesitate to acknowledge that that God also has the power to bring about Resurrection, to recreate man, and to make Hell and Heaven?</p>
<p>After making the truth plain by this concise and rational argument, the address turns from the disbelievers to the Holy Prophet (upon whom be peace) and he is told: "If these people do not acknowledge the truth, they may not; you have not been empowered to act with authority over them, so that you should coerce them into believing: your only task is to exhort, so exhort them. Ultimately they have to return to Us; then We shall call them to full account and shall inflict a heavy punishment on those who do not believe."</p>
`
