export default `
 <h2>Name</h2>
<p>The Surah is so designated after the word <em>wal-fajr</em> with which it opens.</p>
<h2>Period of Revelation</h2>
<p>Its contents show that it was revealed at the stage when persecution of the new converts to Islam had begun in Makkah. On that very basis the people of Makkah have been warned of the evil end of the tribes of Ad and Thamud and of Pharaoh.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to affirm the meting out of rewards and punishments in the Hereafter, which the people of Makkah were not prepared to acknowledge, Let us consider the reasoning in the order in which it has been presented.</p>
<p>First of all, swearing oaths by the dawn, the ten nights, the even and the odd, and the departing night, the listeners have been asked: "Are these things not enough to testify to the truth of that which you are refusing to acknowledge?" From the explanation that we have given of these four things in the corresponding notes, it will become clear that these things are a symbol of the regularity that exists in the night and day, and swearing oaths by these the question has been asked in the sense: Even after witnessing this wise system established by God, do you still need any other evidence to show that it is not beyond the power of that God Who has brought about this system to establish the Hereafter, and that it is the very requirement of his wisdom that He should call man to account for his deeds?</p>
<p>Then, reasoning from man's own history, the evil end of the Ad and the Thamud and Pharaoh has been cited as an example to show that when they transgressed all limits and multiplied corruption in the earth, Allah laid upon them the scourge of His chastisement. This is a proof of the fact that the system of the universe is not being run by deaf and blind forces, nor is the world a lawless kingdom of a corrupt ruler, but a Wise Ruler is ruling over it, the demand of Whose wisdom and justice is continuously visible in the world itself in man's own history that He should call to account, and reward and punish accordingly, the being whom He has blessed with reason and moral sense and given the right of appropriation in the world.</p>
<p>After this, an appraisal has been made of the general moral state of human society of which Arab paganism was a conspicuous example; two aspects of it in particular, have been criticized: first the materialistic attitude of the people on account of which overlooking the moral good and evil, they regarded only the achievement of worldly wealth, rank and position, or the absence of it, as the criterion of honor or disgrace, and had forgotten that neither riches was a reward nor poverty a punishment, but that Allah is trying man in both conditions to see what attitude he adopts when blessed with wealth and how he behaves when afflicted by poverty. Second, the people's attitude under which the orphan child in their society was left destitute on the death of the father. Nobody asked after the poor; whoever could, usurped the whole heritage left by the deceased parent, and drove away the weak heirs fraudulently. The people were so afflicted with an insatiable greed for wealth that
they were never satisfied however much they might hoard and amass. This criticism is meant to make them realize as to why the people with such an attitude and conduct in the life of the world should not be called to account for their misdeeds.</p>
<p>The discourse has been concluded with the assertion that accountability shall certainly be held and it will be held on the Day when the Divine Court will be established. At that time the deniers of the judgment will understand that which they are not understanding now in spite of instruction and admonition, but understanding then will be of no avail. The denier will regret and say, "Would that I had provided for this Day beforehand while I lived in the world." But his regrets will not save him from Allah's punishment. However, as for the people who would have accepted the Truth, which the heavenly books and the Prophets of God were presenting, with full satisfaction of the heart in the world, Allah will be pleased with them and they will be well pleased with the rewards bestowed by Allah. They will be called upon to join the righteous and enter Paradise.</p>;
`
