export default `
 <h2>Name</h2>
<p>This Surah is known by two names -- At-Taubah and Al-Bara'at. It is called At-Taubah because it enunciates the nature of <em>taubah</em> (repentance) and mentions the conditions of its acceptance.(vv. 102. 118). The second name Bara'at (Release) is taken from the first word of the Surah.</p>
<h2>Omission of <em>Bismillah</em></h2>
<p>This is the only Surah of the Quran to which <em>Bismillah</em> is not prefixed. Though the commentators have given different reasons for this, the correct one that which has been given by Imam Razi: namely,this is because the Holy Prophet himself did not dictate it at the beginning of the Surah. Therefore the Companions did not prefix it and their successors followed them., This is a further proof of the fact that utmost care has been taken to keep the Quran intact so that it should remain in its complete and original form.</p>
<h2>Discourses and Periods of Revelation</h2>
<p>This Surah comprises three discourses:-</p>
<p>The first discourse (vv. 1-37), was revealed in Zil-Qa'adah A.H. 9 or thereabout. As the importance of the subject of the discourse required its declaration on the occasion of <em>Haj</em> the Holy Prophet dispatched Hadrat Ali to follow Hadrat Abu Bakr, who had already left for Makkah as leader of the Pilgrims to the Ka'abah. He instructed Hadrat Ali to deliver the discourse before the representatives of the different clans of Arabia so as to inform them of the new policy towards the <em>mushriks</em>.</p>
<p>The second discourse (vv., 38-72) was sent down in Rajab A.H. 9 or a little before this, when the Holy Prophet was engaged in making preparations for the Campaign, of Tabuk. In this discourse, the Believers were urged to take active part in <em>Jihad</em>, and the shirkers were severely rebuked for holding back their wealth and for hesitation to sacrifice their lives in the way of Allah because of their hypocrisy, weak faith or negligence.</p>
<p>The third discourse (vv. 73-129) was revealed on his return from the Campaign of Tabuk. There are some pieces in this discourse that were sent down on different occasions during the same period and were afterwards consolidated by the Holy Prophet into the Surah in accordance with inspiration from Allah. But this caused no interruption in its continuity because they dealt with the same subject and formed part of the same series of events. This discourse warns the hypocrites of their evil deeds and rebukes those Believers who had stayed behind in the Campaign of Tabuk. Then after taking them to task, Allah pardons those true Believers who had not taken part in the <em>Jihad</em> in the Way of Allah for one reason or the other.</p>
<p>Chronologically, the first discourse should have come last; but being the most important of the three in regard to its subject matter, it was placed first in the order of compilation.</p>
<h2>Historical Background</h2>
<p>Now let us consider the historical background of the Surah. The series of events that have been discussed in this Surah took place after the Peace Treaty of Hudaibiyah. By that time, one-third of Arabia had come under the sway of Islam which had established itself as a powerful, well organized and civilized Islamic State. This Treaty afforded further opportunities to Islam to spread its influence in the comparatively peaceful atmosphere created by it. After this Treaty, two events took place, which led to very important results:</p>
<h2>Conquest of Arabia</h2>
<p>The first was the Conquest of Arabia. The Holy Prophet was able to send missions among different clans for the propagation of Islam. The result was that during the short period of two years, it became such a great power that it made the old order of ignorance' feel helpless before it. So much so that the zealous elements from among the Quraish were so exasperated that they broke the Treaty in order to encounter Islam in a decisive combat. But the Holy Prophet took prompt action after the breach so as not to allow them any opportunity to gather enough force for this. He made a sudden invasion on Makkah in the month of Ramadan in A. H. 8 and conquered it. Though this conquest broke the backbone of the order of ignorance, it made still another attack on Islam in the battle-field of Hunain, which proved to be its death-knell. The clans of Hawazin Thaqif, Naur, Jushm and others gathered their entire forces in the battle field in order to crush the reformative Revolution, but they
utterly failed in their evil designs. The defeat of 'ignorance' at Hunain paved the way for making the whole of Arabia the 'Abode of Islam' (<em>Dar-ul-Islam</em>). The result was that hardly a year had Passed after the Battle of Hunain, when the major portion of Arabia came within the fold of Islam and only a few upholders of the old order remained scattered over some corners of the country.</p>
<p>The second event that contributed towards making Islam a formidable power was the Campaign of Tabuk, which was necessitated by the provocative activities of the Christians living within or near the boundaries of the Roman Empire to the north of Arabia. Accordingly, the Holy Prophet, with an army of thirty thousand marched boldly towards the Roman Empire but the Romans evaded the encounter. The result was that the power of the Holy Prophet and Islam increased manifold and deputations from all corners of Arabia began to wait upon him on his return from Tabuk in order to offer their allegiance to Islam and obedience to him. The Holy Quran has described this triumph in Surah An-Nasr: "When the succor of Allah came and victory was attained and you saw people entering the fold of Islam in large numbers...</p>
<h2>Campaign to Tabuk</h2>
<p>The Campaign to Tabuk was the result of conflict with the Roman Empire, that had started even before the conquest of Makkah. One of the missions sent after the Treaty of Hudaibiyah to different parts of Arabia visited the clans which lived in the northern areas adjacent to Syria. The majority of these people were Christians, who were under the influence of the Roman Empire. Contrary to all the principles of the commonly accepted international law, they killed fifteen members of the delegation near a place known as Zat-u-Talah (or Zat-i-Itlah). Only Ka'ab bin Umair Ghifari, the head of the delegation, succeeded in escaping and reporting the sad incident. Besides this, Shurahbll bin Amr, the Christian governor of Busra, who was directly under the Roman Caesar, had also put to death Haritli bin Umair, the ambassador of the Holy Prophet, who had been sent to him on a similar minion.</p>
<p>These events convinced the Holy Prophet that a strong action should be taken in order to make the territory adjacent to the Roman Empire safe and secure for the Muslims. Accordingly, in the month of Jamadi-ul-Ula A. H. 8, he sent an army of three thousand towards the Syrian border. When this army reached near Ma'an, the Muslims learned that Shurahbil was marching with an army of one hundred thousand to fight-with them and that the Caesar, who himself was at Hims, had sent another army consisting of one hundred thousand soldiers under his brother Theodore. But in spite of such fearful news, the brave small band of the Muslims marched on fearlessly and encountered the big army of Shurahbil at M'utah. And the result of the encounter in which the Muslims were fighting against fearful odds (the ratio of the two armies was 1:33), as very favorable, for the enemy utterly failed to defeat them. This proved very helpful for the propagation of Islam. As a result, those Arabs who were
living in a state of semi independence in Syria and near Syria and the clans of Najd near Iraq, who were under the influence of the Iranian Empire, turned towards Islam and embraced it in thousands. For example, the people of Bani Sulaim (whose chief was Abbas bin Mirdas Sulaimi), Ashja'a, Ghatafan, Zubyan, Fazarah, etc., came into the fold of Islam at the same time. Above all, Farvah bin 'Amral Juzami, who was the commander of the Arab armies of the Roman Empire, embraced Islam during that time, and underwent the trial of his Faith in a way that filled the whole territory with wonder. When the Caesar came to know that Farvah had embraced Islam, he ordered that he should be arrested and brought to his court. Then the Caesar said to him, "You will have to choose one of the two things. Either give up your Islam and win your liberty and your former rank, or remain a Muslim and face death." He calmly chose Islam and sacrificed his life in the way of the Truth.</p>
<p>No wonder that such events as these made the Caesar realize the nature of the danger that was threatening his Empire from Arabia. Accordingly, in 9 A.H. he began to make military preparations to avenge the insult he had suffered at M'utah. The Ghassanid and other Arab chiefs also began to muster armies under him. When the Holy Prophet, who always kept himself well-informed even of the minutest things that could affect the Islamic Movement favorably or adversely, came to know of these preparations, he at once under- stood their meaning. Therefore, without the least hesitation he decided to fight against the great power of the Caesar. He knew that the show of the slightest weakness would result in the utter failure of the Movement which was facing three great dangers at that time. First the dying power of 'ignorance' that had almost been crushed in the battle-field of Hunain might revive again. Secondly, the Hypocrites of Al: Madinah, who were always on the look-out for such an
opportunity, might make full use of this to do the greatest possible harm to it. For they had already made preparations for this and had, through a monk called Abu Amir, sent secret messages of their evil designs to the Christian king of Ghassan and the Caesar himself. Besides this, they had also built a mosque near Al-Madinah for holding secret meetings for this purpose. The third danger was of an attack by the Caesar himself, who had already defeated Iran, the other great power of that period, and filled with awe the adjacent territories.</p>
<p>It is obvious that if all these three elements had been given an opportunity of taking a concerted action against the Muslims, Islam would have lost the fight it had almost won. That is why in this case the Holy Prophet made an open declaration for making preparations for the Campaign against the Roman Empire, which was one of the two greatest empires of the world of that period. The declaration was made though all the apparent circumstances were against such a decision: for there was famine in the country and the long awaited crops were about to ripen: the burning heat of the scorching summer season of Arabia was at, its height and there was not enough money for preparations in general, and for equipment and conveyance in particular. But in spite of these handicaps, when the Messenger of Allah realized the urgency of the occasion, he took this step which was to decide whether the Mission of the Truth was going to survive or perish. The very fact that he made an open declaration
for making preparations for such a campaign to Syria against the Roman Empire showed how important it was, for this was contrary to his previous practice. Usually he took every precaution not to reveal beforehand the direction to which he was going nor the name of the enemy whom he was going to attack; nay, he did not move out of Al-Madinah even in the direction of the campaign.</p>
<p>All the parties in Arabia fully realized the grave consequences of this critical decision. The remnants of the lovers of the old order of 'ignorance' were anxiously waiting for the result of the Campaign, for they had pinned all their hopes on the defeat of Islam by the Romans. The 'hypocrites' also considered it to be their last chance of crushing the power of Islam by internal rebellion, if the Muslims suffered a defeat in Syria. They had, therefore, made full use of the Mosque built by them for hatching plots and had employed all their devices to render the Campaign a failure. On the other side, the true Believers also realized fully that the fate of the Movement for which they had been exerting their utmost for the last 22 years was now hanging in the balance. If they showed courage on that critical occasion, the doors of the whole outer world would be thrown open for the Movement to spread. But if they showed weakness or cowardice, then all the work they had done in Arabia
would -end in smoke.</p>
<p>That is why these lovers of Islam began to make enthusiastic preparations for the Campaign. Everyone of them tried to surpass the other in making contributions for the provision of equipment for it. Hadrat Uthman and Hadrat Abdur Rehman bin Auf presented large sums of money for this purpose. Hadrat Umar contributed half of the earnings of his life and Hadrat Abu Bakr the entire earnings of his life. The indigent Companions did not lag behind and presented whatever they could earn by the sweat of their labor and the women parted with their ornaments. Thousands of volunteers, who were filled with the desire of sacrificing their lives for Islam, came to the Holy Prophet and requested that arrangements for weapons and conveyance be made for them so that they should join the expedition. Those who could not be provided with these shed tears of sorrow; the scene was so pathetic that it made the Holy Prophet sad because of his inability to arm them. In short, the occasion became the
touchstone for discriminating a true believer from a hypocrite. For, to lag behind in the Campaign meant that the very relationship of a person to Islam was doubtful. Accordingly, whenever a person lagged behind during the journey to Tabuk, the Holy Prophet, on being informed, would spontaneously say, "Leave him alone. If there be any good in him, Allah will again join him with you, and if there be no good in him, then thank Allah that He relieved you of his evil company".</p>
<p>In short, the Holy Prophet marched out towards Syria in Rajab A. H. 9, with thirty thousand fighters for the cause of Islam. The conditions in which the expedition was undertaken may be judged from the fact that the number of camels with them was so small that many of them were obliged to walk on foot and to wait for their turns for several had to ride at a time on each camel. To add to this, there was the burning heat of the desert and the acute shortage of water. But they were richly rewarded for their firm resolve and sincere adherence to the cause and for their perseverance in the face of those great difficulties and obstacles.</p>
<p>When they arrived at Tabuk, they learned that the Caesar and his allies had withdrawn their troops from the frontier and there was no enemy to fight with. Thus they won a moral victory that increased their prestige manifold and, that too, without shedding a drop of blood.</p>
<p>In this connection, it is pertinent to point out that the general impression given by the historians of the campaigns of the Holy Prophet about the Campaign of Tabuk is not correct. They relate the event in a way as if the news of the mustering of the Roman armies near the Arabian frontier was itself false. The fact is that the Caesar had begun to muster his armies, but the Holy Prophet forestalled him and arrived on the scene before he could make full preparations for the invasion. Therefore, believing that "discretion is the better part of valor," he withdrew his armies from the frontier. For he had not forgotten that the three thousand fighters for the cause of Islam had rendered helpless his army one hundred thousand strong at M'utah. He could not, therefore, even with an army of two hundred thousand, dare to fight against an army of thirty thousand, and that, too, under the leadership of the Holy Prophet himself.</p>
<p>When the Holy Prophet found that the Caesar had withdrawn his forces from the frontier, he considered thee question whether it would be worthwhile to march into the Syrian territory or to halt at Tabuk and turn his moral victory to political and strategical advantage. He decided on the latter course and made a halt for twenty days at Tabuk. During this time, he brought pressure on the small states that lay between the Roman Empire and the Islamic State and were at that time under the influence of the Romans, and subdued and made them the tributaries of the Islamic State. For instance, some Christian chiefs Ukaidir bin Abdul Malik Kindi of Dumatul Jaiidal, Yuhanna bin D'obah of Allah, and the chiefs of Maqna, Jarba' and Azruh also submitted and agreed to pay <em>Jizyah</em> to the Islamic State of Al- Madinah. As a result of this, the boundaries of the Islamic State were extended right up to the Roman Empire, and the majority of the Arab clans, who were being used by the Caesar
against Arabia, became the allies of the Muslims against the Romans.</p>
<p>Above all, this moral victory of Tabuk afforded a golden opportunity to the Muslims to strengthen their hold on Arabia before entering into a long conflict with the Romans. For it broke the back of those who had still been expecting that the old order of 'ignorance' might revive in the near future, whether they were the open upholders of <em>shirk</em> or the hypocrites who were hiding their <em>shirk</em> under the garb of Islam. The majority of such people were compelled by the force of circumstances to enter into the fold of Islam and, at least, make it possible for their descendants to become true Muslims. After this a mere impotent minority of the upholders of the old order was left in the field, but it could not stand in the way of the Islamic Revolution for the perfection of which Allah had sent His Messenger.</p>
<h2>Problems of the Period</h2>
<p>If we keep in view the preceding background, we can easily find out the problems that were confronting the Community at that time. They were:</p>
<ol>
  <li>
    <p>to make the whole of Arabia a perfect <em>Dar-ul-Islam</em>,</p>
  </li>
  <li>
    <p>to extend the influence of Islam to the adjoining countries,</p>
  </li>
  <li>
    <p>to crush the mischiefs of the hypocrites, and</p>
  </li>
  <li>
    <p>to prepare the Muslims for <em>Jihad</em> against the non- Muslim world.</p>
  </li>
</ol>
<ol>
  <li>
    <p>Now that the administration of the whole of Arabia had come in the hands of the Believers, and all the opposing powers had become helpless, it was necessary to make a clear declaration of that policy which was to be adopted to make her a perfect <em>Dar-ul-Islam</em>. Therefore the following measures were adopted:</p>
    <ol>
      <li>
        <p>A clear declaration was made that all the treaties with the <em>mushriks</em> were abolished and the Muslims would be released from the treaty obligations with them after a respite of four months.(vv. 1-3). This declaration was necessary for uprooting completely the system of life based on <em>shirk</em> and to make Arabia exclusively the center of Islam so that it should not in any way interfere with the spirit of Islam nor become an internal danger for it.</p>
      </li>
      <li>
        <p>A decree was issued that the guardianship of the Ka\`abah, which held central position in all the affairs of Arabia, should be wrested from the <em>mushriks</em> and placed permanently in the hands of the Believers, (vv. 12-18) that all the customs and practices of the <em>shirk</em> of the era of 'ignorance' should be forcibly abolished: that the <em>mushriks</em> should not be allowed even to come near the "House" (v. 28). This was to eradicate every trace of <em>shirk</em> from the "House" that was dedicated exclusively to the worship of Allah.</p>
      </li>
      <li>
        <p>The evil practice of <em>Nasi</em>, by which they used to tamper with the sacred months in the days of 'ignorance', was forbidden as an act of <em>kufr</em> (v. 37). This was also to serve as an example to the Muslims for eradicating every vestige of the customs of ignorance from the life of Arabia (and afterwards from the lives of the Muslims everywhere).</p>
      </li>
    </ol>
  </li>
  <li>
    <p>In order to enable the Muslims to extend the influence of Islam outside Arabia, they were enjoined to crush with sword the non- Muslim powers and to force them to accept the sovereignty of the Islamic State. As the great Roman and Iranian Empires were the biggest hindrances in the way, a conflict with them was inevitable. The object of <em>Jihad</em> was not to coerce them to accept Islam they were free to accept or not to accept it-but to prevent them from thrusting forcibly their deviations upon others and the coming generations. The Muslims were enjoined to tolerate their misguidance only to the extent that they might have the freedom to remain misguided, if they chose to be so, provided that they paid <em>Jizyah</em> (v. 29) as a sign of their subjugation to the Islamic State.</p>
  </li>
  <li>
    <p>The third important problem was to crush the mischiefs of the hypocrites, who had hitherto been tolerated in spite of their flagrant crimes. Now that there was practically no pressure upon them from outside, the Muslims were enjoined to treat them openly as disbelievers (v. 73). Accordingly, the Holy Prophet set on fire the house of Swailim, where the hypocrites used to gather for consultations in order to dissuade the people from joining the expedition to Tabuk. Likewise on his return from Tabuk, he ordered to pull down and burn the 'Mosque' that had been built to serve as a cover for the hypocrites for hatching plots against the true Believers.</p>
  </li>
  <li>
    <p>In order to prepare the Muslims for <em>Jihad</em> against the whole non-Muslim world, it was necessary to cure them even of that slight weakness of faith from which they were still suffering. For there could be no greater internal danger to the Islamic Community than the weakness of faith, especially where it was going to engage itself single-handed in a' conflict with the whole non-Muslim world. That is why those people who had lagged behind in the Campaign to Tabuk or had shown the least negligence were severely taken to task, and were considered as hypocrites if they had no plausible excuse for not fulfilling that obligation. Moreover, a clear declaration was made that in future the sole criterion of a Muslim's faith shall be the exertions he makes for the uplift of the Word of Allah and the role he plays in the conflict between Islam and <em>kufr</em>. Therefore, if anyone will show any hesitation in sacrificing his life, money, time and energies, his faith shall not be
    regarded as genuine. (vv. 81-96).</p>
    <p>If the above-mentioned important points are kept in view during the study of this Surah, it will facilitate the understanding of its contents.</p>
  </li>
</ol>
<h2>Subject: Problems of Peace and War</h2>
<p>In continuation of Surah Al-Anfal, this Surah also deals with the problems of peace and war and bases the theme on the Tabuk Expedition.</p>
<h3>Topics and their Interconnection</h3>
<p>This portion deals with the sanctity of treaties and lays down principles, rules and regulations which must be kept in view before breaking them, in case the other party does not observe them sincerely. <strong>1 - 12</strong></p>
<p>In this portion the Muslims have been urged to fight in the Way of Allah with the <em>mushrik</em> Arabs, the Jews and the Christians, who were duly warned of the consequences of their mischievous and inimical behavior. <strong>13 - 37</strong></p>
<p>In this discourse, the Muslims have been told clearly and explicitly that they will inherit the rewards promised by Allah only if they take active part in the conflict with <em>kufr</em>, for that is the criterion which distinguishes true Muslims from hypocrites. Therefore true Muslims should take active part in <em>Jihad</em>, without minding dangers, obstacles, difficulties, temptations and the like. <strong>38 - 72</strong></p>
<p>This portion deals with the problems of hypocrites and lays down rules and regulations governing the treatment that should be meted out to them and points out their distinctive marks from true Muslims. <strong>73 - 90</strong></p>
<p>This portion deals with the case of those who remained behind and did not accompany the Holy Prophet for <em>Jihad</em> to Tabuk. For this purpose they have been separated in different categories, that is, the disabled, the sick, the indigent, the hypocrites, the believers who realized their guilt and punished themselves before the return of the Holy Prophet from Tabuk and those who confessed their error. Their cases have been dealt with in accordance with the nature and extent of their offense. <strong>91 - 110</strong></p>
<p>In order to make their noble qualities look all the more conspicuous and dignified by contrast, the characteristics of the Believers have been mentioned, and they have been reassured that Allah, the Sovereign of the Universe, is their helper and guardian. Accordingly, because of their sincerity, He has forgiven the Three Believers who did not take part in the expedition. <strong>111 - 118</strong></p>
<p>In the concluding portion, general instructions have been given to the Believers for their guidance. <strong>119 - 127</strong></p>
<p>This is the conclusion: "Follow the Messenger who is gentle and compassionate and your greatest well-wisher, and trust in Allah, the Lord of the Universe". <strong>128 - 129</strong></p>;
`
