export default `
 <h2>Name</h2>
<p>The Surah takes its name from the word <em>wal-lail</em> with which it opens.</p>
<h2>Period of Revelation</h2>
<p>Its subject matter so closely resembles that of Surah Ash-Shams that each Surah seems to be an explanation of the other. It is one and the same thing which has been explained in Surah Ash-Shams in one way and in this Surah in another. This indicates that both these Surahs were sent down in about the same period.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to distinguish between the two different ways of life and to explain the contrast between their ultimate ends and results. In view of the subject matter this Surah consists of two parts, the first part consisting of vv. 1-11 and the second of vv. 12-21.</p>
<p>In the first part, at the outset it has been pointed out that the strivings and doings that the individuals, nations and groups of mankind are engaged in in the world, are, in respect of their moral nature, as divergent as the day is from the night, and the male from the female. After this, according to the general style of the brief Surahs of the Quran, three moral characteristics of one kind and three moral characteristics of the other kind have been presented as an illustration from among a vast collection of the strivings and activities of man, from which every man can judge which style of life is represented by one kind of the characteristics and which style of life by the other kind. Both these styles have been described in such brief, elegant. and pithy sentences that they move the heart and go down into memory as soon as one hears them. Characteristics of the first kind are that one should spend one's wealth, adopt God-consciousness and piety, and acknowledge the good as
good. The second kind of the characteristics are that one should be miserly, should least care for God's pleasure and His displeasure, and should repudiate what is good and right. Then it has been stated that these two modes of action which are clearly divergent, cannot be equal and alike in respect of their results. But, just as they are divergent in their nature, so they are divergent in their results. The person (or group of persons) who adopts the first mode of action, Allah will make easy for him the correct way of life, so much so that doing good will become easy for him and doing evil difficult. On the contrary, he who adopts the second mode of life, Allah will make easy for him the difficult and hard way of life, so much so that doing evil will become easy for him and doing good difficult. This passage has been concluded with a most effective and touching sentence, saying: "This worldly wealth for the sake of which man is even prepared to risk his life will not go down with
him into the grave; therefore, what will it avail him after death?"</p>
<p>In the second part also three truths have been stated equally briefly. First, that Allah has not left man uninformed in the examination hall of the world, but He has taken on Himself the responsibility to tell him which one is the straight and right way out of the different ways of life. Here, there was no need to point out that by sending His Messenger and His Book He has fulfilled His this responsibility, for both the Messenger and the Book were present to afford the guidance. Second, that the Master of both the world and the Hereafter is Allah alone. If you seek the world, it is He Who will give it, and if you seek the Hereafter, again it is He Who will give it. Now, it is for you to decide what you should seek from Him. The third truth that has been stated is that the wretched one who rejects the good, which is being presented through the Messenger and the Book, and turns away from it, will have a blazing fire ready for him. As for the God fearing person who spends his
wealth in a good cause, without any selfish motive, only for the sake of winning his Lord's good pleasure, his Lord will be pleased with him and will bless him with so much that he will be well pleased with Him.</p>;
`
