export default `
 <h2>Name</h2>
<p>The Surah takes its name <em>Ad-Duha</em> from the very first word.</p>
<h2>Period of Revelation</h2>
<p>Its subject matter clearly indicates that it belongs to the earliest period at Makkah. Traditions also show that the revelations were suspended for a time, which caused the Holy Prophet (upon whom be Allah's peace) to be deeply distressed and grieved. On this account he felt very anxious that perhaps he had committed some error because of which his Lord had become angry with him and had forsaken him. Thereupon he was given the consolation that revelation had not been stopped because of some displeasure but this was necessitated by the same expediency as underlies the peace and stillness of the night after the bright day, as if to say: "If you had continuously been exposed to the intensely bright light of Revelation (<em>Wahi</em>) your nerves could not have endured it. Therefore, an interval was given in order to afford you peace and tranquility." This state was experienced by the Holy Prophet in the initial stage of the Prophethood when he was not yet accustomed to hear the
intensity of Revelation. On this basis, observance of a pause in between was necessary. This we have already explained in the introduction to Surah Al Muddaththir; and in E. N. 5 of Surah Al-Muzzammil also we have explained what great burden of the coming down of Revelation he had to bear. Later, when the Holy Prophet developed the power to bear this burden, there was no longer any need for long gaps.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to console the Holy Prophet (upon whom be peace) and its object to remove his anxiety and distress, which he had been caused by the suspension of Revelation. First of all, swearing an oath by the bright morning and the stillness of night, he has been reassured, so as to say: "Your Lord has not at all forsaken you, nor is he displeased with you." Then, he has been given the good news that the hardships that he was experiencing in the initial stage of his mission, would not last long, for every later period of life for him would be better than the former period, and before long Allah would bless him so abundantly that he would be well pleased. This is one of the express prophecies of the Quran, which proved literally true, afterwards, whereas when this prophecy was made there seemed not to be the remotest chance that the helpless and powerless man who had come out to wage a war against the ignorance and paganism of the entire nation, would ever achieve such wonderful
success.</p>
<p>Then, addressing His Holy Prophet (upon whom be peace) Allah says:"O My dear Prophet, what has caused you the anxiety and distress that your Lord has forsaken you, and that We are displeased with you? Whereas the fact is that We have been good to you with kindness after kindness ever since the day of your birth. You were born an orphan, We made the best arrangement for your upbringing and care: you were unaware of the Way, We showed you the Way; you were indigent, We made you rich. All this shows that you have been favored by Us from the very beginning and Our grace and bounty has been constantly focused on you."Here, one should also keep in view vv. 37-42 of Surah Ta Ha, where Allah, while sending the Prophet Moses to confront a tyrant like Pharaoh, encouraged and consoled him, saying: "We have been looking after you with kindness ever since your birth; therefore, you should be satisfied that you will not be left alone in this dreadful mission. Our bounty will constantly be
with you."</p>
<p>In conclusion, Allah has instructed His Prophet (upon whom be peace) telling him how he should treat the creatures of God to repay for the favors He has done him and how he should render thanks for the blessings He has bestowed on him.</p>
`
