export default `
 <h2>Name</h2>
<p>The Surah is so designated after the first sentence.</p>
<h2>Period of Revelation</h2>
<p>Its subject matter so closely resembles that of Surah Ad-Duha that both these Surah seem to have been revealed in about the same period under similar conditions. According to Hadrat Abdullah bin Abbas, it was sent down in Makkah just after wad-Duha.</p>
<h2>Theme and Subject Matter</h2>
<p>The aim and object of this Surah too is to console and encourage the Holy Messenger (upon whom be Allah's peace). Before his call he never had to encounter the conditions which he suddenly had to encounter after it when he embarked on his mission of inviting the people to Islam. This was by itself a great revolution in his own life of which he had no idea in his life before Prophethood. No sooner had he started preaching the message of Islam than the same society which had esteemed him with unique honor, turned hostile to him. The same relatives and friends, the same clansmen and neighbors, who used to treat him with the highest respect, began to shower him with abuse and invective. No one in Makkah was prepared to listen to him; he began to be ridiculed and mocked in the street and on the road; and at every step he had to face new difficulties. Although gradually he became accustomed to the hardships, even much severer ones, yet the initial stage was very discouraging for him.
That is why first Surah Ad-Duha was sent down to console him, and then this Surah.</p>
<p>In it, at the outset, Allah says: "We have favored you, O Prophet, with three great blessings; therefore you have no cause to be disheartened. The first is the blessing of <em>Sharh Sadr</em> (opening up of the breast), the second of removing from you the heavy burden that was weighing down your back before the call, and the third of exalting your renown the like of which has never been granted to any man before. Further below in the notes we have explained what is implied by each of these blessings and how great and unique these blessings indeed are!</p>
<p>After this, the Lord and Sustainer of the universe has reassured His Servant and Messenger (upon whom be peace) that the period of hardships which he is passing through, is not very long, but following close behind it there is also a period of ease. This same thing has been described in Surah Ad-Duha, saying: "Every later period is better for you than the former period, and soon your Lord will give you so much that you will be well pleased."</p>
<p>In conclusion, the Holy Prophet has been instructed, so as to say, "You can develop the power to bear and resist the hardships of the initial stage only by one means, and it is this: \`When you are free from your occupations, you should devote yourself to the labor and toil of worship, and turn all your attention exclusively to your Lord'."This same instruction has been given him in much greater detail in Surah Al-Muzzammil 1-9.</p>
`
