export default `
 <h2>Name</h2>
<p>The Surah has been so designated after the word <em>al-qadr</em> in the very first verse.</p>
<h2>Period of Revelation</h2>
<p>Whether it is a Makki or a Madani revelation is disputed. Abu Hayyan in <em>Al-Bahr al-Muhti</em> has made the claim that the majority of scholars regard it as a Madani Surah. Ali bin Ahmad al-Wahidi in his commentary says that this is the first Surah to be sent down in Madinah. Contrary to this, Al Mawardi says that according to the majority of scholars it is a Makki revelation, and the same view has Imam Suyuti expressed in <em>Al-Itqan</em>. Ibn Mardayah has cited Ibn Abbas, lbn Az Zubair and Hadrat Aishah as saying that this Surah was revealed at Makkah. A study of the contents also shows that it should have been revealed at Makkah as we shall explain below.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is to acquaint man with the value, worth and importance of the Quran. Its being placed just after Surah Al-Alaq in the arrangement of the Quran by itself explains that the Holy Book, the revelation of which began with the first five verses of Surah Al-Alaq. was sent down in a destiny making night. It is a glorious Book and its revelation for mankind is full of blessings.</p>
<p>At the outset, Allah says: "We have sent it down." That is, it is not a composition of Muhammad (upon whom be Allah's peace and blessing) himself, but We Ourself have revealed it.</p>
<p>Then, it is said that "We sent it down in the Night of Destiny." Night of Destiny lies two meanings and both are implied here. First, that it is the night during which destinies are decided; or, in other words, it is not an ordinary night like the other nights, but a night in which destinies are made or marred. The revelation of this Book in this night is not merely the revelation of a book but an event which will change the destiny of not only the Quraish, or of Arabia, but of, the entire world. The same thing has been said in Surah Ad-Dukhan for which please see Introduction to that Surah and E. N. 3 thereof. The other meaning is that this is, a night of unique honor, dignity and glory; so much so that it is better than a thousand months. Thus, the disbelievers of Makkah have been warned, as if to say: "You on account of your ignorance regard this Book, which Muhammad (upon whom be Allah's peace and blessings) has presented, as a calamity for yourselves and complain that a
disaster has befallen you, whereas the night in which it was decreed to be sent down was such a blessed night that a task was accomplished in it for the well being of mankind, which had never been accomplished even during a thousand months of history. This also has been said in verse 3 of Ad-Dukhan in another way, which we have explained in the introduction to that Surah.</p>
<p>In conclusion, it has been stated that in this night the angels and Gabriel descend with every decree (which in verse 4 of Surah Ad- Dukhan has been described as arm-hakim: wise decree) by the leave of their Lord, and it is all peace from evening till morning; that is, there is no interference of evil in it, for all decrees of Allah are intended to promote good and not evil. So much so that even if a decision to destroy a nation is taken, it is taken for the sake of ultimate good, not evil.</p>
`
