export default `
 <h2>Name</h2>
<p>It is derived from the word <em>zilzal</em> in the first verse.</p>
<h2>Period of Revelation</h2>
<p>Whether or not it was revealed, at Makkah or Madinah, is disputed. Ibn Masud, Ata, Jabir, and Mjahid say that it is a Makki Surah and a statement of Ibn Abbas also supports this view. On the contrary, Qatadah and Muqatil say that it is Madani and another statement of Ibn Abbas also has been cited in support of this view. That it is a Madani Surah is reasoned from a tradition from Hadrat Abu Said Khudri, which Ibn Abi Hatim has related from him. He says: "When the verse <em>Fa-man ya mal mithqala dharratin khairan yarah, wa man ya mal mithqala dharratin sharran yarah</em>, was revealed, I said: "O Messenger of Allah, shall I really see my deeds? The Holy Messenger replied in the affirmative. I submitted: And every major sin? He replied yes. I said: And the minor sins too? He replied yes. Thereupon I exclaimed that I would then be ruined. The Holy Prophet said: Rejoice, O Abu Sa'id, for each good act will be equal to ten good acts like it." The basis of the argument for this
Surah's being Madani is that Hadrat Abu Sa'ld Khudri was an inhabitant of Madinah and reached maturity after the Battle of Uhud. Therefore, if this Surah was revealed in his presence, as is apparent from his statement, it must be a Madani Surah. However, the practice that the Companions and their immediate successors followed in respect of the occasion of the revelation of the verses and Surahs, has already been explained in the Introduction to Surah Ad-Dahr above. Therefore, a Companion's saying that a verse was sent down on this or that particular occasion is no proof that it was sent down on that very occasion. It may well be that after coming of age when Hadrat Abu Sa'id heard this Surah for the first time from the Holy Prophet, terrified by its last portion he might have asked the Holy Prophet the questions which we have cited above, and he might have narrated the incident saying that when this verse was revealed he put this and this question to the Holy Prophet. In the
absence of this tradition every reader who reads the Qur'an with understandings will feel that it is a Makki Surah. More than that: from its theme and style he would feel that it must have been sent down in the earliest stage at Makkah when the fundamental principles and beliefs of Islam were being presented before the people in a concise but highly effective way.</p>
<h2>Theme and Subject Matter</h2>
<p>Its theme is the second life after death and presentation in it before man of the full record of the deeds done by him in the world. In the first three sentences it has been told briefly how the second life after death will take place and how confounding it will be for man. In the next two sentences it has been said that this very earth on which man has lived and performed all kinds of deeds thoughtlessly, and about which he never could fancy that this lifeless thing would at some time in the future bear witness to his deeds, will speak out on that Day by Allah's command and will state in respect of each individual person what act he had committed at a particular time and place. Then, it has been said that men on that Day, rising from their graves, will come out in their varied groups from all corners of the earth, to be shown their deeds and works, and their presentation of the deeds will be so complete and detailed that not an atom's weight of any good or evil act will be left
unnoticed or hidden from his eyes.</p>
`
