/* eslint-disable */
module.exports = {
  "verbose": false,
  "debug": false,
  "preBootstrapCustomizations": "./src/styles/variables.scss",
  "mainSass": "./src/styles/main.scss",
  "scripts": {
    "transition": false,
    "alert": false,
    "button": false,
    "carousel": false,
    "collapse": false,
    "dropdown": false,
    "modal": false,
    "tooltip": false,
    "popover": false,
    "scrollspy": false,
    "tab": false,
    "affix": false
  },
  "styles": {
    "mixins": true,
    "normalize": true,
    "print": false,
    "scaffolding": true,
    "type": true,
    "code": true,
    "grid": true,
    "tables": true,
    "forms": true,
    "buttons": true,
    "component-animations": true,
    "glyphicons": false,
    "dropdowns": true,
    "button-groups": false,
    "input-groups": false,
    "navs": true,
    "navbar": true,
    "breadcrumbs": false,
    "pagination": true,
    "pager": true,
    "labels": true,
    "badges": true,
    "jumbotron": false,
    "thumbnails": false,
    "alerts": false,
    "progress-bars": false,
    "media": false,
    "list-group": true,
    "panels": true,
    "wells": false,
    "responsive-embed": true,
    "close": true,

    "modals": true,
    "tooltip": true,
    "popovers": true,
    "carousel": false,

    "utilities": true,
    "responsive-utilities": true
  }
};
